import { isSpotterRenderParametersV1, type SpotterRenderParametersV1 } from "./spotter-contracts";
import { LIVE_ENGINEER_AUDIO_CATALOG } from "./engineer-audio-catalog.generated";

export const LIVE_ENGINEER_PROTOCOL_VERSION = 2 as const;
export const LIVE_ENGINEER_RENDERING_VERSION = "opponent-pace-v1" as const;
export const SPOTTER_RENDERING_VERSION = "spotter-v1" as const;
export type OpponentPaceRelationV1 = "fastest-in-class" | "setting-race-pace" | "within-class-pace" | "off-class-pace" | "outlier-lap";
export type OpponentPaceTextKeyV1 = "live_engineer_opponent_fastest" | "live_engineer_opponent_setting_race_pace" | "live_engineer_opponent_within_pace" | "live_engineer_opponent_off_pace" | "live_engineer_opponent_outlier";
export type SpotterTextKeyV1 = "live_engineer_spotter_car_left" | "live_engineer_spotter_car_right" | "live_engineer_spotter_still_there" | "live_engineer_spotter_three_wide_left" | "live_engineer_spotter_three_wide_right" | "live_engineer_spotter_clear_left" | "live_engineer_spotter_clear_right";
export type LiveEngineerPriorityV1 = "high" | "normal" | "low";
export type LiveEngineerVoiceModeV1 = "automatic" | "exact-response";
export interface LiveEngineerCandidateV1 { candidateId: string; actionKey: "opponent-pace-status"; cooldownGroup: "opponent-pace"; sourceFactIds: readonly string[]; policyVersion: "opponent-pace-v1"; renderParameters: OpponentPaceRenderParametersV1; }
export type LiveEngineerDecisionReasonV1 = "selected" | "expired" | "wrong-session" | "ineligible-evidence" | "context-blocked" | "semantic-duplicate" | "cooldown-active" | "lower-priority" | "queue-capacity";
export type OpponentPaceBenchmarkKindV1 = "session-best" | "recent-race-pace";
export interface OpponentPaceRenderParametersV1 { relation: OpponentPaceRelationV1; scope: "class" | "overall"; playerLapNumber: number; playerLapTimeMs: number; benchmarkLapTimeMs: number; deltaMs: number; benchmarkKind: OpponentPaceBenchmarkKindV1; benchmarkDriverName?: string; className?: string; }
interface LiveEngineerCalloutCommonV2 { type: "live-engineer-callout"; protocolVersion: 2; decisionId: string; candidateId: string; sessionId: string; timelineEpoch: number; sourceSequence: number; priority: LiveEngineerPriorityV1; createdSessionTimeMs: number; expiresSessionTimeMs: number; }
export interface OpponentPaceCalloutMessageV2 extends LiveEngineerCalloutCommonV2 { family: "opponent-pace"; render: { renderingVersion: "opponent-pace-v1"; textKey: OpponentPaceTextKeyV1; parameters: OpponentPaceRenderParametersV1 }; }
export interface SpotterCalloutMessageV2 extends LiveEngineerCalloutCommonV2 { family: "spotter"; render: { renderingVersion: "spotter-v1"; textKey: SpotterTextKeyV1; parameters: SpotterRenderParametersV1 }; }
export type LiveEngineerCalloutMessageV2 = OpponentPaceCalloutMessageV2 | SpotterCalloutMessageV2;
export type LiveEngineerVoiceLineOptions = { mode: "automatic" } | { mode: "exact-response"; requestId: string };
export interface LiveEngineerVoiceLineMessageV2 { type: "live-engineer-voice-line"; protocolVersion: 2; deliveryId: string; decisionId: string; requestId?: string; family: "opponent-pace" | "spotter"; mode: "automatic" | "exact-response"; priority: LiveEngineerPriorityV1; sourceSequence: number; catalogVersion: string; segmentIds: readonly string[]; }
export interface LiveEngineerVoiceRequestV2 { type: "live-engineer-voice-request"; protocolVersion: 2; action: "exact-pace"; requestId: string; decisionId: string; }
export interface LiveEngineerDeliveryStatusV2 { type: "live-engineer-delivery-status"; protocolVersion: 2; deliveryId: string; status: "started" | "completed" | "failed" | "muted" | "preempted" | "unsupported"; reason?: "radio-disabled" | "audio-blocked" | "asset-missing" | "decode-failed" | "catalog-mismatch" | "superseded"; }
const record = (v: unknown): Record<string, unknown> | undefined => v !== null && typeof v === "object" ? v as Record<string, unknown> : undefined;
const nonNegative = (v: unknown): v is number => typeof v === "number" && Number.isFinite(v) && v >= 0;
const relations: readonly OpponentPaceRelationV1[] = ["fastest-in-class", "setting-race-pace", "within-class-pace", "off-class-pace", "outlier-lap"];
const textKeys: readonly OpponentPaceTextKeyV1[] = ["live_engineer_opponent_fastest", "live_engineer_opponent_setting_race_pace", "live_engineer_opponent_within_pace", "live_engineer_opponent_off_pace", "live_engineer_opponent_outlier"];
const spotterKeys: readonly SpotterTextKeyV1[] = ["live_engineer_spotter_car_left", "live_engineer_spotter_car_right", "live_engineer_spotter_still_there", "live_engineer_spotter_three_wide_left", "live_engineer_spotter_three_wide_right", "live_engineer_spotter_clear_left", "live_engineer_spotter_clear_right"];
export function isOpponentPaceRenderParametersV1(v: unknown): v is OpponentPaceRenderParametersV1 { const p = record(v); return !!p && relations.includes(p.relation as OpponentPaceRelationV1) && (p.scope === "class" || p.scope === "overall") && nonNegative(p.playerLapNumber) && nonNegative(p.playerLapTimeMs) && nonNegative(p.benchmarkLapTimeMs) && Number.isInteger(p.deltaMs) && p.deltaMs === (p.playerLapTimeMs as number) - (p.benchmarkLapTimeMs as number) && (p.benchmarkKind === "session-best" || p.benchmarkKind === "recent-race-pace"); }
export function isLiveEngineerCalloutMessageV2(v: unknown): v is LiveEngineerCalloutMessageV2 { const x = record(v), r = record(x?.render); if (!x || x.type !== "live-engineer-callout" || x.protocolVersion !== 2 || typeof x.decisionId !== "string" || typeof x.candidateId !== "string" || typeof x.sessionId !== "string" || !nonNegative(x.timelineEpoch) || !nonNegative(x.sourceSequence) || !["high", "normal", "low"].includes(x.priority as string) || !nonNegative(x.createdSessionTimeMs) || !nonNegative(x.expiresSessionTimeMs) || x.expiresSessionTimeMs <= x.createdSessionTimeMs || !r) return false; return x.family === "opponent-pace" ? r.renderingVersion === "opponent-pace-v1" && textKeys.includes(r.textKey as OpponentPaceTextKeyV1) && isOpponentPaceRenderParametersV1(r.parameters) : x.family === "spotter" && r.renderingVersion === "spotter-v1" && spotterKeys.includes(r.textKey as SpotterTextKeyV1) && isSpotterRenderParametersV1(r.parameters); }
export function isLiveEngineerVoiceLineMessageV2(v: unknown): v is LiveEngineerVoiceLineMessageV2 { const x = record(v); return !!x && x.type === "live-engineer-voice-line" && x.protocolVersion === 2 && typeof x.deliveryId === "string" && typeof x.decisionId === "string" && ["opponent-pace", "spotter"].includes(x.family as string) && ["automatic", "exact-response"].includes(x.mode as string) && ["high", "normal", "low"].includes(x.priority as string) && nonNegative(x.sourceSequence) && typeof x.catalogVersion === "string" && Array.isArray(x.segmentIds) && x.segmentIds.length > 0 && x.segmentIds.every((id) => typeof id === "string" && id.length > 0); }
export function isLiveEngineerVoiceRequestV2(v: unknown): v is LiveEngineerVoiceRequestV2 { const x = record(v); return !!x && x.type === "live-engineer-voice-request" && x.protocolVersion === 2 && x.action === "exact-pace" && typeof x.requestId === "string" && typeof x.decisionId === "string"; }
export function isLiveEngineerDeliveryStatusV2(v: unknown): v is LiveEngineerDeliveryStatusV2 { const x = record(v); return !!x && x.type === "live-engineer-delivery-status" && x.protocolVersion === 2 && typeof x.deliveryId === "string" && ["started", "completed", "failed", "muted", "preempted", "unsupported"].includes(x.status as string); }
export function createLiveEngineerVoiceLine(callout: LiveEngineerCalloutMessageV2, segmentIds: readonly string[], options: LiveEngineerVoiceLineOptions): LiveEngineerVoiceLineMessageV2 { const known = new Set((LIVE_ENGINEER_AUDIO_CATALOG.segments as readonly { segmentId: string }[]).map((s) => s.segmentId)); if (!segmentIds.length || segmentIds.some((id) => !known.has(id))) throw new Error("Unknown or empty audio segments"); return { type: "live-engineer-voice-line", protocolVersion: 2, deliveryId: options.mode === "automatic" ? `${callout.decisionId}/automatic` : `${callout.decisionId}/exact/${options.requestId}`, decisionId: callout.decisionId, ...(options.mode === "exact-response" ? { requestId: options.requestId } : {}), family: callout.family, mode: options.mode, priority: callout.priority, sourceSequence: callout.sourceSequence, catalogVersion: LIVE_ENGINEER_AUDIO_CATALOG.catalogVersion, segmentIds: [...segmentIds] }; }
