import { expect, test } from "bun:test";
import type { SpotterCalloutMessageV2 } from "../../shared/racing/live/engineer-contracts";
import { useLiveEngineerStore } from "../src/stores/live-engineer";

const callout = (decisionId: string, sourceSequence: number): SpotterCalloutMessageV2 => ({ type: "live-engineer-callout", protocolVersion: 2, family: "spotter", decisionId, candidateId: `candidate-${decisionId}`, sessionId: "s", timelineEpoch: 1, sourceSequence, priority: "high", createdSessionTimeMs: sourceSequence, expiresSessionTimeMs: sourceSequence + 2_000, render: { renderingVersion: "spotter-v1", textKey: "live_engineer_spotter_car_left", parameters: { state: "car-left", side: "left", overlapCount: 1 } } });
const voiceBase = { protocolVersion: 3, mode: "automatic", priority: "normal", sourceSequence: 1, catalogVersion: "v1", segmentIds: ["pace.one"], sessionId: "s", timelineEpoch: 1, createdSessionTimeMs: 0, expiresSessionTimeMs: 1000 } as const;
const resetStore = () => { useLiveEngineerStore.setState({ current: null, voiceCurrent: null, queue: [], voiceQueue: [], history: [], playback: "idle", outbound: [] }); return useLiveEngineerStore.getState(); };

test("dismisses each callout once while keeping bounded history separate", () => { const store = resetStore(); store.receiveCallout(callout("a", 1)); store.receiveCallout(callout("b", 2)); expect(useLiveEngineerStore.getState().current?.decisionId).toBe("a"); expect(useLiveEngineerStore.getState().queue.map((item) => item.decisionId)).toEqual(["b"]); store.dismiss(); expect(useLiveEngineerStore.getState().current?.decisionId).toBe("b"); store.dismiss(); expect(useLiveEngineerStore.getState().current).toBeNull(); expect(useLiveEngineerStore.getState().history.map((item) => item.decisionId)).toEqual(["b", "a"]); });
test("rejects expired voice lines with terminal expired status", () => { const store = resetStore(); store.receiveVoiceLine({ type: "live-engineer-voice-line", deliveryId: "expired", decisionId: "expired-decision", family: "opponent-pace", ...voiceBase, createdSessionTimeMs: 100, expiresSessionTimeMs: 200 } as never, 300); expect(useLiveEngineerStore.getState().voiceCurrent).toBeNull(); expect(store.takeOutbound()).toMatchObject({ deliveryId: "expired", status: "failed", reason: "expired" }); });
test("browser retains no second automatic race-engineer voice line", () => { const store = resetStore(); store.receiveVoiceLine({ type: "live-engineer-voice-line", family: "opponent-pace", deliveryId: "one", decisionId: "one", ...voiceBase }, 500); store.receiveVoiceLine({ type: "live-engineer-voice-line", family: "opponent-pace", deliveryId: "two", decisionId: "two", ...voiceBase }, 500); expect(useLiveEngineerStore.getState().voiceQueue).toHaveLength(0); expect(store.takeOutbound()).toMatchObject({ deliveryId: "two", reason: "superseded" }); });
test("Spotter preempts race-engineer voice and reports superseded terminal status", () => { const store = resetStore(); store.receiveVoiceLine({ type: "live-engineer-voice-line", family: "opponent-pace", deliveryId: "race", decisionId: "race", ...voiceBase, segmentIds: ["line.one"] }, 500); store.receiveVoiceLine({ type: "live-engineer-voice-line", family: "spotter", deliveryId: "spot", decisionId: "spot", ...voiceBase, segmentIds: ["line.one"] }, 500); expect(useLiveEngineerStore.getState().voiceCurrent?.family).toBe("spotter"); expect(store.takeOutbound()).toMatchObject({ deliveryId: "race", status: "preempted", reason: "superseded" }); });
test("bounds visible history and tracks outbound controls", () => { const store = resetStore(); for (let i = 0; i < 7; i += 1) store.receiveCallout(callout(`d${i}`, i)); expect(useLiveEngineerStore.getState().history).toHaveLength(5); store.enqueueControl({ type: "live-engineer-delivery-status", protocolVersion: 2, deliveryId: "d4", status: "started" }); expect(store.takeOutbound()?.type).toBe("live-engineer-delivery-status"); });
