import { describe, expect, it } from "bun:test";
import { buildLiveTelemetryView, indexTelemetrySchema, readIndexedValue } from "../src/lib/live-telemetry-view";
import type { LiveTelemetryFrameMessageV1, LiveTelemetrySchemaMessageV1 } from "../../shared/telemetry/live/contracts";
const schema = { type:"telemetry-schema", protocolVersion:1, schemaId:"s", simulator:"acc", catalogVersion:"c", catalogHash:"h", catalogSchemaVersion:"1", parserVersion:"p", resolverVersion:"r", derivationVersion:"d", definitions:["motion.speed","tires.tire-pressure","timing.lap-fraction","fuel.remaining-volume","fuel.remaining-fraction","fuel.remaining-percent","fuel.capacity","inputs.throttle","inputs.brake","inputs.clutch","inputs.handbrake","inputs.steering","inputs.gear"].map(semanticId=>({semanticId,unit:null,mappingStatus:"direct",schemaVersion:"1",limitations:[]})) } as LiveTelemetrySchemaMessageV1;
const f1Schema = { ...schema, schemaId:"f1", simulator:"f1-2025", definitions:["tires.blistering","race.competitor.pit-status","race.competitor.on-pit-road"].map(semanticId=>({semanticId,unit:null,mappingStatus:"direct",schemaVersion:"1",limitations:[]})) } as LiveTelemetrySchemaMessageV1;
const frame = (values: unknown[], schemaId="s", states?: Record<number, any>) => ({type:"telemetry-frame",protocolVersion:1,schemaId,streamId:"x",sessionId:null,sequence:1,observedAt:{domain:"session",milliseconds:2},receivedAtMs:3,values,states}) as LiveTelemetryFrameMessageV1;
describe("live telemetry view",()=>{
 it("indexes semantic values and rejects schema mismatch",()=>{const i=indexTelemetrySchema(schema); expect(readIndexedValue(i,frame([4,[1,2,3,4],.5]),"motion.speed")).toBe(4); expect(buildLiveTelemetryView(schema,frame([4,5,6],"other"))).toBeUndefined();});
 it("returns undefined for non-ok values and preserves sparse state",()=>{const f=frame([4,5,.5],"s",{1:"stale"}); const v=buildLiveTelemetryView(schema,f)!; expect(v.motion.speedMps).toBe(4); expect(v.tires.pressurePsi).toBeUndefined(); expect(v.stateBySemanticId["tires.tire-pressure"]).toBe("stale");});
 it("builds scalar view",()=>{const v=buildLiveTelemetryView(schema,frame([12,[1,2,3,4],.25,42,.42,42,100,.8,.2,.3,.4,-.5,4]))!; expect(v.motion.speedMps).toBe(12); expect(v.timing.lapFraction).toBe(.25); expect(v.fuel).toEqual({remainingVolumeL:42,remainingFraction:.42,remainingPercent:42,capacityL:100}); expect(v.inputs).toEqual({throttle:.8,brake:.2,clutch:.3,handbrake:.4,steering:-.5,gear:4});});
 it("builds F1 blistering and normalized competitor pit state",()=>{const v=buildLiveTelemetryView(f1Schema,frame([[11,22,33,44],["none","pitting","in-pit-area"],[false,true,true]],"f1"))!; expect(v.tires.blistering).toEqual({fl:11,fr:22,rl:33,rr:44}); expect(v.competitors).toEqual([{pitStatus:"none",onPitRoad:false},{pitStatus:"pitting",onPitRoad:true},{pitStatus:"in-pit-area",onPitRoad:true}]);});
});
