import { m } from "@/paraglide/messages";
import type { CarStats, F1Team } from "./types";

export const teams: F1Team[] = [
  {
    id: 8,
    name: "McLaren",
    fullName: "McLaren Formula 1 Team",
    chassis: "MCL39",
    powerUnit: "Mercedes",
    teamPrincipal: "Andrea Stella",
    base: "Woking, UK",
    image: "/car-images/f1/mclaren.png",
    drivers: [
      { name: "Lando Norris", number: 4, nationality: "GB" },
      { name: "Oscar Piastri", number: 81, nationality: "AU" },
    ],
    stats: { overallRating: 95, pace: 96, straightLineSpeed: 93, cornerSpeed: 97, braking: 94, traction: 95, aeroEfficiency: 96, reliability: 92 },
  },
  {
    id: 1,
    name: "Ferrari",
    fullName: "Scuderia Ferrari HP",
    chassis: "SF-25",
    powerUnit: "Ferrari",
    teamPrincipal: "Frederic Vasseur",
    base: "Maranello, Italy",
    image: "/car-images/f1/ferrari.png",
    drivers: [
      { name: "Charles Leclerc", number: 16, nationality: "MC" },
      { name: "Lewis Hamilton", number: 44, nationality: "GB" },
    ],
    stats: { overallRating: 94, pace: 95, straightLineSpeed: 95, cornerSpeed: 93, braking: 93, traction: 94, aeroEfficiency: 93, reliability: 94 },
  },
  {
    id: 2,
    name: "Red Bull Racing",
    fullName: "Oracle Red Bull Racing",
    chassis: "RB21",
    powerUnit: "Honda RBPT",
    teamPrincipal: "Christian Horner",
    base: "Milton Keynes, UK",
    image: "/car-images/f1/redbullracing.png",
    drivers: [
      { name: "Max Verstappen", number: 1, nationality: "NL" },
      { name: "Liam Lawson", number: 30, nationality: "NZ" },
    ],
    stats: { overallRating: 93, pace: 94, straightLineSpeed: 94, cornerSpeed: 94, braking: 92, traction: 93, aeroEfficiency: 95, reliability: 90 },
  },
  {
    id: 0,
    name: "Mercedes",
    fullName: "Mercedes-AMG Petronas F1 Team",
    chassis: "W16",
    powerUnit: "Mercedes",
    teamPrincipal: "Toto Wolff",
    base: "Brackley, UK",
    image: "/car-images/f1/mercedes.png",
    drivers: [
      { name: "George Russell", number: 63, nationality: "GB" },
      { name: "Andrea Kimi Antonelli", number: 12, nationality: "IT" },
    ],
    stats: { overallRating: 91, pace: 92, straightLineSpeed: 93, cornerSpeed: 90, braking: 91, traction: 90, aeroEfficiency: 91, reliability: 93 },
  },
  {
    id: 4,
    name: "Aston Martin",
    fullName: "Aston Martin Aramco F1 Team",
    chassis: "AMR25",
    powerUnit: "Mercedes",
    teamPrincipal: "Andy Cowell",
    base: "Silverstone, UK",
    image: "/car-images/f1/astonmartin.png",
    drivers: [
      { name: "Fernando Alonso", number: 14, nationality: "ES" },
      { name: "Lance Stroll", number: 18, nationality: "CA" },
    ],
    stats: { overallRating: 85, pace: 85, straightLineSpeed: 86, cornerSpeed: 84, braking: 85, traction: 84, aeroEfficiency: 86, reliability: 88 },
  },
  {
    id: 5,
    name: "Alpine",
    fullName: "BWT Alpine F1 Team",
    chassis: "A525",
    powerUnit: "Mercedes",
    teamPrincipal: "Oliver Oakes",
    base: "Enstone, UK",
    image: "/car-images/f1/alpine.png",
    drivers: [
      { name: "Pierre Gasly", number: 10, nationality: "FR" },
      { name: "Jack Doohan", number: 7, nationality: "AU" },
    ],
    stats: { overallRating: 82, pace: 82, straightLineSpeed: 83, cornerSpeed: 81, braking: 82, traction: 81, aeroEfficiency: 82, reliability: 85 },
  },
  {
    id: 7,
    name: "Haas",
    fullName: "MoneyGram Haas F1 Team",
    chassis: "VF-25",
    powerUnit: "Ferrari",
    teamPrincipal: "Ayao Komatsu",
    base: "Kannapolis, USA",
    image: "/car-images/f1/haas.png",
    drivers: [
      { name: "Oliver Bearman", number: 87, nationality: "GB" },
      { name: "Esteban Ocon", number: 31, nationality: "FR" },
    ],
    stats: { overallRating: 83, pace: 83, straightLineSpeed: 84, cornerSpeed: 82, braking: 83, traction: 82, aeroEfficiency: 81, reliability: 86 },
  },
  {
    id: 6,
    name: "Racing Bulls",
    fullName: "Visa Cash App Racing Bulls",
    chassis: "VCARB 02",
    powerUnit: "Honda RBPT",
    teamPrincipal: "Laurent Mekies",
    base: "Faenza, Italy",
    image: "/car-images/f1/racingbulls.png",
    drivers: [
      { name: "Yuki Tsunoda", number: 22, nationality: "JP" },
      { name: "Isack Hadjar", number: 6, nationality: "FR" },
    ],
    stats: { overallRating: 84, pace: 84, straightLineSpeed: 85, cornerSpeed: 83, braking: 84, traction: 83, aeroEfficiency: 83, reliability: 87 },
  },
  {
    id: 3,
    name: "Williams",
    fullName: "Williams Racing",
    chassis: "FW47",
    powerUnit: "Mercedes",
    teamPrincipal: "James Vowles",
    base: "Grove, UK",
    image: "/car-images/f1/williams.png",
    drivers: [
      { name: "Alexander Albon", number: 23, nationality: "TH" },
      { name: "Carlos Sainz", number: 55, nationality: "ES" },
    ],
    stats: { overallRating: 81, pace: 81, straightLineSpeed: 84, cornerSpeed: 79, braking: 80, traction: 80, aeroEfficiency: 80, reliability: 84 },
  },
  {
    id: 9,
    name: "Sauber",
    fullName: "Stake F1 Team Kick Sauber",
    chassis: "C45",
    powerUnit: "Ferrari",
    teamPrincipal: "Mattia Binotto",
    base: "Hinwil, Switzerland",
    image: "/car-images/f1/sauber.png",
    drivers: [
      { name: "Nico Hulkenberg", number: 27, nationality: "DE" },
      { name: "Gabriel Bortoleto", number: 5, nationality: "BR" },
    ],
    stats: { overallRating: 78, pace: 78, straightLineSpeed: 80, cornerSpeed: 76, braking: 78, traction: 77, aeroEfficiency: 77, reliability: 83 },
  },
];

export const regulations = {
  engine: "1.6L V6 Turbo Hybrid",
  totalPower: "~1,000+ HP (ICE + ERS)",
  ers: "MGU-K + MGU-H, 4 MJ deployment/lap",
  weight: "798 kg minimum",
  fuelCapacity: "110 kg max",
  gearbox: "8-speed sequential + reverse",
  tyres: "Pirelli (C1-C5, Intermediates, Wets)",
  drs: "Drag Reduction System (rear wing)",
};
export const powerUnitGroups = [
  { name: "Mercedes", teams: ["Mercedes", "McLaren", "Aston Martin", "Williams", "Alpine"] },
  { name: "Ferrari", teams: ["Ferrari", "Haas", "Sauber"] },
  { name: "Honda RBPT", teams: ["Red Bull Racing", "Racing Bulls"] },
];
export const statLabels: { key: keyof CarStats; label: string }[] = [
  { key: "overallRating", label: m.f1cars_overall() },
  { key: "pace", label: m.label_pace() },
  { key: "straightLineSpeed", label: m.f1cars_straight_speed() },
  { key: "cornerSpeed", label: m.f1cars_corner_speed() },
  { key: "braking", label: m.label_braking() },
  { key: "traction", label: m.f1cars_traction() },
  { key: "aeroEfficiency", label: m.f1cars_aero_efficiency() },
  { key: "reliability", label: m.f1cars_reliability() },
];
