import type { IRacingSessionInfoCatalogField } from "./contracts";
import { setupField } from "./setup-builders";

export const IRACING_CAPTURED_SETUP_FIELDS: readonly IRacingSessionInfoCatalogField[] = [
  setupField(
    "UpdateCount",
    "Setup update count",
    "count",
    "Revision counter for active iRacing setup.",
    "setup.metadata.update-count",
  ),
  setupField(
    "Chassis.BrakesInCar.AbsSetting",
    "ABS",
    "level",
    "Configured ABS level from iRacing in-car controls.",
    "setup.electronics.abs",
  ),
  setupField(
    "Chassis.BrakesInCar.BrakePads",
    "Brake pads",
    "enum",
    "Configured brake-pad compound from iRacing in-car controls.",
    "setup.brakes.pad-compound",
  ),
  setupField(
    "Chassis.BrakesInCar.BrakePressureBias",
    "Brake bias",
    "value-with-unit",
    "Configured brake-pressure bias from iRacing in-car controls.",
    "setup.brakes.bias",
  ),
  setupField(
    "Chassis.BrakesInCar.DashDisplayPage",
    "Display page",
    "configuration",
    "Configured dashboard display page.",
    "setup.electronics.display-page",
  ),
  setupField(
    "Chassis.BrakesInCar.EngineMapSetting",
    "Engine map",
    "level",
    "Configured engine-map level from iRacing in-car controls.",
    "setup.electronics.engine-map",
  ),
  setupField(
    "Chassis.BrakesInCar.FrontMasterCyl",
    "Front master cylinder",
    "value-with-unit",
    "Configured front brake master-cylinder setting.",
    "setup.brakes.front-master-cylinder",
  ),
  setupField(
    "Chassis.BrakesInCar.RearMasterCyl",
    "Rear master cylinder",
    "value-with-unit",
    "Configured rear brake master-cylinder setting.",
    "setup.brakes.rear-master-cylinder",
  ),
  setupField(
    "Chassis.BrakesInCar.TcSetting",
    "Traction control",
    "level",
    "Configured traction-control level from iRacing in-car controls.",
    "setup.electronics.traction-control",
  ),
  setupField(
    "Chassis.Front.FarbConnection",
    "Front anti-roll-bar connection",
    "configuration",
    "Configured front anti-roll-bar connection.",
    "setup.suspension.front-anti-roll-bar.connection",
  ),
  setupField(
    "Chassis.Front.FarbRate",
    "Front anti-roll-bar rate",
    "configuration",
    "Configured front anti-roll-bar rate.",
    "setup.suspension.front-anti-roll-bar.rate",
  ),
  setupField(
    "Chassis.Front.NoseWeight",
    "Front weight distribution",
    "value-with-unit",
    "Configured front weight distribution.",
    "setup.weight.front-distribution",
  ),
  setupField(
    "Chassis.Front.TotalToeIn",
    "Front total toe",
    "value-with-unit",
    "Configured total front toe-in.",
    "setup.alignment.toe",
  ),
  setupField(
    "Chassis.Front.EnduranceLights",
    "Endurance lights",
    "configuration",
    "Configured endurance-light package.",
    "setup.electronics.endurance-lights",
  ),
  setupField(
    "Chassis.Front.LeftSideLedStrips",
    "Left-side LED strips",
    "configuration",
    "Configured left-side LED strip state.",
    "setup.electronics.left-side-led-strips",
  ),
  setupField(
    "Chassis.Front.RightSideLedStrips",
    "Right-side LED strips",
    "configuration",
    "Configured right-side LED strip state.",
    "setup.electronics.right-side-led-strips",
  ),
  setupField(
    "Chassis.Rear.DiffClutchPlates",
    "Differential clutch plates",
    "count",
    "Configured differential clutch-plate count.",
    "setup.drivetrain.differential-clutch-plates",
  ),
  setupField(
    "Chassis.Rear.RarbConnection",
    "Rear anti-roll-bar connection",
    "configuration",
    "Configured rear anti-roll-bar connection.",
    "setup.suspension.rear-anti-roll-bar.connection",
  ),
  setupField(
    "Chassis.Rear.RarbRate",
    "Rear anti-roll-bar rate",
    "configuration",
    "Configured rear anti-roll-bar rate.",
    "setup.suspension.rear-anti-roll-bar.rate",
  ),
];
