import type { IRacingSessionInfoCatalogField } from "./contracts";
import {
  setupCornerFields,
  setupField,
  setupTemperatureFields,
  type SetupLeaf,
} from "./setup-builders";
import { IRACING_SUSPENSION_TIRE_LEAVES } from "./setup-tires";

const CORNER_SETUP_LEAVES: readonly SetupLeaf[] = [
  {
    field: "CornerWeight",
    label: "corner weight",
    unit: "value-with-unit",
    description: "Static corner weight",
    semanticId: "setup.weight.corner-weight",
  },
  {
    field: "RideHeight",
    label: "ride height",
    unit: "value-with-unit",
    description: "Static setup ride height",
    semanticId: "setup.suspension.ride-height",
  },
  {
    field: "ShockDeflection",
    label: "shock deflection",
    unit: "value-with-unit",
    description: "Static setup shock deflection",
    semanticId: "setup.suspension.shock-deflection",
  },
  {
    field: "SpringPerchOffset",
    label: "spring perch offset",
    unit: "value-with-unit",
    description: "Spring perch offset",
    semanticId: "setup.suspension.spring-perch-offset",
  },
  {
    field: "SpringRate",
    label: "spring rate",
    unit: "value-with-unit",
    description: "Spring-rate setting",
    semanticId: "setup.suspension.spring-rate",
  },
  {
    field: "SpringSelected",
    label: "spring selection",
    unit: "index",
    description: "Discrete spring selection",
    semanticId: "setup.suspension.spring-selection",
  },
  {
    field: "BumpStiffness",
    label: "bump stiffness",
    unit: "level",
    description: "Single-rate compression damping",
    semanticId: "setup.dampers.compression",
  },
  {
    field: "ReboundStiffness",
    label: "rebound stiffness",
    unit: "level",
    description: "Single-rate rebound damping",
    semanticId: "setup.dampers.rebound",
  },
  {
    field: "CompDamping",
    label: "compression damping",
    unit: "level",
    description: "Single-rate compression damping",
    semanticId: "setup.dampers.compression",
  },
  {
    field: "RbdDamping",
    label: "rebound damping",
    unit: "level",
    description: "Single-rate rebound damping",
    semanticId: "setup.dampers.rebound",
  },
  {
    field: "LsCompDamping",
    label: "slow compression damping",
    unit: "level",
    description: "Low-speed compression damping",
    semanticId: "setup.dampers.slow-compression",
  },
  {
    field: "HsCompDamping",
    label: "fast compression damping",
    unit: "level",
    description: "High-speed compression damping",
    semanticId: "setup.dampers.fast-compression",
  },
  {
    field: "LsRbdDamping",
    label: "slow rebound damping",
    unit: "level",
    description: "Low-speed rebound damping",
    semanticId: "setup.dampers.slow-rebound",
  },
  {
    field: "HsRbdDamping",
    label: "fast rebound damping",
    unit: "level",
    description: "High-speed rebound damping",
    semanticId: "setup.dampers.fast-rebound",
  },
  {
    field: "Camber",
    label: "camber",
    unit: "value-with-unit",
    description: "Static camber",
    semanticId: "setup.alignment.camber",
  },
  {
    field: "Caster",
    label: "caster",
    unit: "value-with-unit",
    description: "Static caster",
    semanticId: "setup.alignment.caster",
  },
  {
    field: "ToeIn",
    label: "toe",
    unit: "value-with-unit",
    description: "Static toe-in",
    semanticId: "setup.alignment.toe",
  },
];

const FRONT_SETUP_LEAVES: readonly SetupLeaf[] = [
  {
    field: "ArbArms",
    label: "front ARB arms",
    unit: "count",
    description: "Front anti-roll-bar arm count or position",
    semanticId: "setup.suspension.front-anti-roll-bar.arms",
  },
  {
    field: "ArbBlades",
    label: "front ARB blades",
    unit: "level",
    description: "Front anti-roll-bar blade setting",
    semanticId: "setup.suspension.front-anti-roll-bar.blades",
  },
  {
    field: "ArbDiameter",
    label: "front ARB diameter",
    unit: "value-with-unit",
    description: "Front anti-roll-bar diameter",
    semanticId: "setup.suspension.front-anti-roll-bar.diameter",
  },
  {
    field: "ArbOuterDiameter",
    label: "front ARB outer diameter",
    unit: "value-with-unit",
    description: "Front anti-roll-bar outer diameter",
    semanticId: "setup.suspension.front-anti-roll-bar.outer-diameter",
  },
  {
    field: "AntiRollBar",
    label: "front anti-roll bar",
    unit: "configuration",
    description: "Front anti-roll-bar setting",
    semanticId: "setup.suspension.front-anti-roll-bar.setting",
  },
  {
    field: "BrakeBias",
    label: "brake bias",
    unit: "value-with-unit",
    description: "Configured front brake bias",
    semanticId: "setup.brakes.bias",
  },
  {
    field: "BrakePads",
    label: "brake pads",
    unit: "enum",
    description: "Configured brake-pad compound",
    semanticId: "setup.brakes.pad-compound",
  },
  {
    field: "FrontMasterCyl",
    label: "front master cylinder",
    unit: "value-with-unit",
    description: "Front brake master-cylinder setting",
    semanticId: "setup.brakes.front-master-cylinder",
  },
  {
    field: "RearMasterCyl",
    label: "rear master cylinder",
    unit: "value-with-unit",
    description: "Rear brake master-cylinder setting",
    semanticId: "setup.brakes.rear-master-cylinder",
  },
  {
    field: "ToeIn",
    label: "front toe",
    unit: "value-with-unit",
    description: "Front-axle toe-in",
    semanticId: "setup.alignment.toe",
  },
  {
    field: "SteeringRatio",
    label: "steering ratio",
    unit: "ratio",
    description: "Steering ratio",
    semanticId: "setup.alignment.steering-ratio",
  },
  {
    field: "CrossWeight",
    label: "cross weight",
    unit: "value-with-unit",
    description: "Diagonal cross-weight percentage",
    semanticId: "setup.weight.cross-weight",
  },
];

const REAR_SETUP_LEAVES: readonly SetupLeaf[] = [
  {
    field: "FuelLevel",
    label: "fuel level",
    unit: "value-with-unit",
    description: "Configured starting fuel volume",
    semanticId: "setup.strategy.fuel-volume",
  },
  {
    field: "ArbArms",
    label: "rear ARB arms",
    unit: "count",
    description: "Rear anti-roll-bar arm count or position",
    semanticId: "setup.suspension.rear-anti-roll-bar.arms",
  },
  {
    field: "ArbBlades",
    label: "rear ARB blades",
    unit: "level",
    description: "Rear anti-roll-bar blade setting",
    semanticId: "setup.suspension.rear-anti-roll-bar.blades",
  },
  {
    field: "ArbDiameter",
    label: "rear ARB diameter",
    unit: "value-with-unit",
    description: "Rear anti-roll-bar diameter",
    semanticId: "setup.suspension.rear-anti-roll-bar.diameter",
  },
  {
    field: "ArbOuterDiameter",
    label: "rear ARB outer diameter",
    unit: "value-with-unit",
    description: "Rear anti-roll-bar outer diameter",
    semanticId: "setup.suspension.rear-anti-roll-bar.outer-diameter",
  },
  {
    field: "AntiRollBar",
    label: "rear anti-roll bar",
    unit: "configuration",
    description: "Rear anti-roll-bar setting",
    semanticId: "setup.suspension.rear-anti-roll-bar.setting",
  },
  {
    field: "ToeIn",
    label: "rear toe",
    unit: "value-with-unit",
    description: "Rear-axle toe-in",
    semanticId: "setup.alignment.toe",
  },
  {
    field: "DiffPreload",
    label: "differential preload",
    unit: "value-with-unit",
    description: "Mechanical differential preload",
    semanticId: "setup.drivetrain.differential-preload",
  },
  {
    field: "WingAngle",
    label: "rear wing angle",
    unit: "value-with-unit",
    description: "Rear wing angle",
    semanticId: "setup.aero.rear-wing.angle",
  },
  {
    field: "WingSetting",
    label: "rear wing setting",
    unit: "configuration",
    description: "Rear wing setting",
    semanticId: "setup.aero.rear-wing.setting",
  },
  {
    field: "FrictionFaces",
    label: "differential friction faces",
    unit: "count",
    description: "Number of differential friction faces",
    semanticId: "setup.drivetrain.differential-clutch-plates",
  },
  {
    field: "SixthGear",
    label: "sixth gear",
    unit: "ratio",
    description: "Sixth-gear ratio or selection",
    semanticId: "setup.drivetrain.gear-ratios",
  },
];

export const IRACING_CHASSIS_SETUP_FIELDS: readonly IRacingSessionInfoCatalogField[] = [
  ...setupCornerFields("Chassis", CORNER_SETUP_LEAVES),
  ...setupCornerFields("Suspension", [
    ...IRACING_SUSPENSION_TIRE_LEAVES,
    ...CORNER_SETUP_LEAVES,
  ]),
  ...setupTemperatureFields("Suspension"),
  ...FRONT_SETUP_LEAVES.flatMap((leaf) => [
    setupField(
      `Chassis.Front.${leaf.field}`,
      leaf.label,
      leaf.unit,
      `${leaf.description} from iRacing chassis setup.`,
      leaf.semanticId,
    ),
    setupField(
      `Suspension.Front.${leaf.field}`,
      leaf.label,
      leaf.unit,
      `${leaf.description} from iRacing suspension setup.`,
      leaf.semanticId,
    ),
  ]),
  ...REAR_SETUP_LEAVES.flatMap((leaf) => [
    setupField(
      `Chassis.Rear.${leaf.field}`,
      leaf.label,
      leaf.unit,
      `${leaf.description} from iRacing chassis setup.`,
      leaf.semanticId,
    ),
    setupField(
      `Suspension.Rear.${leaf.field}`,
      leaf.label,
      leaf.unit,
      `${leaf.description} from iRacing suspension setup.`,
      leaf.semanticId,
    ),
  ]),
];
