/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameidRouteImport } from './routes/$gameid'
import { Route as AcEvoRouteImport } from './routes/ac-evo'
import { Route as AccRouteImport } from './routes/acc'
import { Route as DevRouteImport } from './routes/dev'
import { Route as F125RouteImport } from './routes/f125'
import { Route as Fm23RouteImport } from './routes/fm23'
import { Route as IracingRouteImport } from './routes/iracing'
import { Route as GameLiveRouteImport } from './routes/$game/live'
import { Route as GameidCarsRouteImport } from './routes/$gameid/cars'
import { Route as GameidCompareRouteImport } from './routes/$gameid/compare'
import { Route as GameidTracksRouteImport } from './routes/$gameid/tracks'
import { Route as AcEvoIndexRouteImport } from './routes/ac-evo/index'
import { Route as AcEvoAnalyseRouteImport } from './routes/ac-evo/analyse'
import { Route as AcEvoChatsRouteImport } from './routes/ac-evo/chats'
import { Route as AcEvoDriverRouteImport } from './routes/ac-evo/driver'
import { Route as AcEvoExperimentsRouteImport } from './routes/ac-evo/experiments'
import { Route as AcEvoRawRouteImport } from './routes/ac-evo/raw'
import { Route as AcEvoSessionsRouteImport } from './routes/ac-evo/sessions'
import { Route as AcEvoSetupsRouteImport } from './routes/ac-evo/setups'
import { Route as AccIndexRouteImport } from './routes/acc/index'
import { Route as AccAnalyseRouteImport } from './routes/acc/analyse'
import { Route as AccChatsRouteImport } from './routes/acc/chats'
import { Route as AccDriverRouteImport } from './routes/acc/driver'
import { Route as AccExperimentsRouteImport } from './routes/acc/experiments'
import { Route as AccRawRouteImport } from './routes/acc/raw'
import { Route as AccSessionsRouteImport } from './routes/acc/sessions'
import { Route as AccSetupsRouteImport } from './routes/acc/setups'
import { Route as DashIndexRouteImport } from './routes/dash.index'
import { Route as DashCombo1RouteImport } from './routes/dash.combo-1'
import { Route as DashCombo2RouteImport } from './routes/dash.combo-2'
import { Route as F125IndexRouteImport } from './routes/f125/index'
import { Route as F125AnalyseRouteImport } from './routes/f125/analyse'
import { Route as F125ChatsRouteImport } from './routes/f125/chats'
import { Route as F125DriverRouteImport } from './routes/f125/driver'
import { Route as F125ExperimentsRouteImport } from './routes/f125/experiments'
import { Route as F125RawRouteImport } from './routes/f125/raw'
import { Route as F125SessionsRouteImport } from './routes/f125/sessions'
import { Route as F125SetupsRouteImport } from './routes/f125/setups'
import { Route as F125TunesRouteImport } from './routes/f125/tunes'
import { Route as Fm23IndexRouteImport } from './routes/fm23/index'
import { Route as Fm23AnalyseRouteImport } from './routes/fm23/analyse'
import { Route as Fm23ChatsRouteImport } from './routes/fm23/chats'
import { Route as Fm23DriverRouteImport } from './routes/fm23/driver'
import { Route as Fm23LiveRouteImport } from './routes/fm23/live'
import { Route as Fm23RawRouteImport } from './routes/fm23/raw'
import { Route as Fm23SessionsRouteImport } from './routes/fm23/sessions'
import { Route as Fm23SetupsRouteImport } from './routes/fm23/setups'
import { Route as IracingIndexRouteImport } from './routes/iracing/index'
import { Route as IracingAnalyseRouteImport } from './routes/iracing/analyse'
import { Route as IracingChatsRouteImport } from './routes/iracing/chats'
import { Route as IracingLiveRouteImport } from './routes/iracing/live'
import { Route as IracingRawRouteImport } from './routes/iracing/raw'
import { Route as IracingSessionsRouteImport } from './routes/iracing/sessions'
import { Route as GameidTracksIndexRouteImport } from './routes/$gameid/tracks.index'
import { Route as AcEvoExperimentsIndexRouteImport } from './routes/ac-evo/experiments.index'
import { Route as AcEvoExperimentsExperimentIdRouteImport } from './routes/ac-evo/experiments.$experimentId'
import { Route as AcEvoSetupsIndexRouteImport } from './routes/ac-evo/setups/index'
import { Route as AcEvoSetupsImportRouteImport } from './routes/ac-evo/setups/import'
import { Route as AcEvoSetupsNewRouteImport } from './routes/ac-evo/setups/new'
import { Route as AccExperimentsIndexRouteImport } from './routes/acc/experiments.index'
import { Route as AccExperimentsExperimentIdRouteImport } from './routes/acc/experiments.$experimentId'
import { Route as AccSetupsIndexRouteImport } from './routes/acc/setups/index'
import { Route as AccSetupsImportRouteImport } from './routes/acc/setups/import'
import { Route as AccSetupsNewRouteImport } from './routes/acc/setups/new'
import { Route as F125ExperimentsIndexRouteImport } from './routes/f125/experiments.index'
import { Route as F125ExperimentsExperimentIdRouteImport } from './routes/f125/experiments.$experimentId'
import { Route as F125SetupsIndexRouteImport } from './routes/f125/setups/index'
import { Route as F125TunesIndexRouteImport } from './routes/f125/tunes/index'
import { Route as Fm23CarsCarOrdinalRouteImport } from './routes/fm23/cars_.$carOrdinal'
import { Route as Fm23LiveDriverRouteImport } from './routes/fm23/live/driver'
import { Route as Fm23LivePitRouteImport } from './routes/fm23/live/pit'
import { Route as Fm23SetupsIndexRouteImport } from './routes/fm23/setups/index'
import { Route as Fm23SetupsCatalogRouteImport } from './routes/fm23/setups/catalog'
import { Route as Fm23SetupsNewRouteImport } from './routes/fm23/setups/new'
import { Route as IracingLiveDriverRouteImport } from './routes/iracing/live/driver'
import { Route as IracingLivePitRouteImport } from './routes/iracing/live/pit'
import { Route as GameidTracksTrackOrdinalIndexRouteImport } from './routes/$gameid/tracks.$trackOrdinal.index'
import { Route as GameidTracksTrackOrdinalTabRouteImport } from './routes/$gameid/tracks.$trackOrdinal.$tab'
import { Route as AcEvoExperimentsExperimentIdReviewRouteImport } from './routes/ac-evo/experiments.$experimentId_.review'
import { Route as AcEvoSetupsEditTuneIdRouteImport } from './routes/ac-evo/setups/edit.$tuneId'
import { Route as AccExperimentsExperimentIdReviewRouteImport } from './routes/acc/experiments.$experimentId_.review'
import { Route as AccSetupsEditTuneIdRouteImport } from './routes/acc/setups/edit.$tuneId'
import { Route as F125ExperimentsExperimentIdReviewRouteImport } from './routes/f125/experiments.$experimentId_.review'
import { Route as Fm23SetupsEditTuneIdRouteImport } from './routes/fm23/setups/edit.$tuneId'
import { Route as Fm23SetupsWheelIndexRouteImport } from './routes/fm23/setups/wheel/index'
import { Route as Fm23SetupsWheelProfileIdRouteImport } from './routes/fm23/setups/wheel/$profileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameidRoute = GameidRouteImport.update({
  id: '/$gameid',
  path: '/$gameid',
  getParentRoute: () => rootRouteImport,
} as any)
const AcEvoRoute = AcEvoRouteImport.update({
  id: '/ac-evo',
  path: '/ac-evo',
  getParentRoute: () => rootRouteImport,
} as any)
const AccRoute = AccRouteImport.update({
  id: '/acc',
  path: '/acc',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const F125Route = F125RouteImport.update({
  id: '/f125',
  path: '/f125',
  getParentRoute: () => rootRouteImport,
} as any)
const Fm23Route = Fm23RouteImport.update({
  id: '/fm23',
  path: '/fm23',
  getParentRoute: () => rootRouteImport,
} as any)
const IracingRoute = IracingRouteImport.update({
  id: '/iracing',
  path: '/iracing',
  getParentRoute: () => rootRouteImport,
} as any)
const GameLiveRoute = GameLiveRouteImport.update({
  id: '/$game/live',
  path: '/$game/live',
  getParentRoute: () => rootRouteImport,
} as any)
const GameidCarsRoute = GameidCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => GameidRoute,
} as any)
const GameidCompareRoute = GameidCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => GameidRoute,
} as any)
const GameidTracksRoute = GameidTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => GameidRoute,
} as any)
const AcEvoIndexRoute = AcEvoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoAnalyseRoute = AcEvoAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoChatsRoute = AcEvoChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoDriverRoute = AcEvoDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoExperimentsRoute = AcEvoExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoRawRoute = AcEvoRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoSessionsRoute = AcEvoSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoSetupsRoute = AcEvoSetupsRouteImport.update({
  id: '/setups',
  path: '/setups',
  getParentRoute: () => AcEvoRoute,
} as any)
const AccIndexRoute = AccIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccRoute,
} as any)
const AccAnalyseRoute = AccAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => AccRoute,
} as any)
const AccChatsRoute = AccChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AccRoute,
} as any)
const AccDriverRoute = AccDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AccRoute,
} as any)
const AccExperimentsRoute = AccExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => AccRoute,
} as any)
const AccRawRoute = AccRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => AccRoute,
} as any)
const AccSessionsRoute = AccSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AccRoute,
} as any)
const AccSetupsRoute = AccSetupsRouteImport.update({
  id: '/setups',
  path: '/setups',
  getParentRoute: () => AccRoute,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/dash/',
  path: '/dash/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashCombo1Route = DashCombo1RouteImport.update({
  id: '/dash/combo-1',
  path: '/dash/combo-1',
  getParentRoute: () => rootRouteImport,
} as any)
const DashCombo2Route = DashCombo2RouteImport.update({
  id: '/dash/combo-2',
  path: '/dash/combo-2',
  getParentRoute: () => rootRouteImport,
} as any)
const F125IndexRoute = F125IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => F125Route,
} as any)
const F125AnalyseRoute = F125AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => F125Route,
} as any)
const F125ChatsRoute = F125ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => F125Route,
} as any)
const F125DriverRoute = F125DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => F125Route,
} as any)
const F125ExperimentsRoute = F125ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => F125Route,
} as any)
const F125RawRoute = F125RawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => F125Route,
} as any)
const F125SessionsRoute = F125SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => F125Route,
} as any)
const F125SetupsRoute = F125SetupsRouteImport.update({
  id: '/setups',
  path: '/setups',
  getParentRoute: () => F125Route,
} as any)
const F125TunesRoute = F125TunesRouteImport.update({
  id: '/tunes',
  path: '/tunes',
  getParentRoute: () => F125Route,
} as any)
const Fm23IndexRoute = Fm23IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23AnalyseRoute = Fm23AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23ChatsRoute = Fm23ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23DriverRoute = Fm23DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23LiveRoute = Fm23LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23RawRoute = Fm23RawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23SessionsRoute = Fm23SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23SetupsRoute = Fm23SetupsRouteImport.update({
  id: '/setups',
  path: '/setups',
  getParentRoute: () => Fm23Route,
} as any)
const IracingIndexRoute = IracingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IracingRoute,
} as any)
const IracingAnalyseRoute = IracingAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => IracingRoute,
} as any)
const IracingChatsRoute = IracingChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => IracingRoute,
} as any)
const IracingLiveRoute = IracingLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => IracingRoute,
} as any)
const IracingRawRoute = IracingRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => IracingRoute,
} as any)
const IracingSessionsRoute = IracingSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => IracingRoute,
} as any)
const GameidTracksIndexRoute = GameidTracksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameidTracksRoute,
} as any)
const AcEvoExperimentsIndexRoute = AcEvoExperimentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcEvoExperimentsRoute,
} as any)
const AcEvoExperimentsExperimentIdRoute =
  AcEvoExperimentsExperimentIdRouteImport.update({
    id: '/$experimentId',
    path: '/$experimentId',
    getParentRoute: () => AcEvoExperimentsRoute,
  } as any)
const AcEvoSetupsIndexRoute = AcEvoSetupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcEvoSetupsRoute,
} as any)
const AcEvoSetupsImportRoute = AcEvoSetupsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AcEvoSetupsRoute,
} as any)
const AcEvoSetupsNewRoute = AcEvoSetupsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AcEvoSetupsRoute,
} as any)
const AccExperimentsIndexRoute = AccExperimentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccExperimentsRoute,
} as any)
const AccExperimentsExperimentIdRoute =
  AccExperimentsExperimentIdRouteImport.update({
    id: '/$experimentId',
    path: '/$experimentId',
    getParentRoute: () => AccExperimentsRoute,
  } as any)
const AccSetupsIndexRoute = AccSetupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccSetupsRoute,
} as any)
const AccSetupsImportRoute = AccSetupsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AccSetupsRoute,
} as any)
const AccSetupsNewRoute = AccSetupsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AccSetupsRoute,
} as any)
const F125ExperimentsIndexRoute = F125ExperimentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => F125ExperimentsRoute,
} as any)
const F125ExperimentsExperimentIdRoute =
  F125ExperimentsExperimentIdRouteImport.update({
    id: '/$experimentId',
    path: '/$experimentId',
    getParentRoute: () => F125ExperimentsRoute,
  } as any)
const F125SetupsIndexRoute = F125SetupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => F125SetupsRoute,
} as any)
const F125TunesIndexRoute = F125TunesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => F125TunesRoute,
} as any)
const Fm23CarsCarOrdinalRoute = Fm23CarsCarOrdinalRouteImport.update({
  id: '/cars_/$carOrdinal',
  path: '/cars/$carOrdinal',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23LiveDriverRoute = Fm23LiveDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => Fm23LiveRoute,
} as any)
const Fm23LivePitRoute = Fm23LivePitRouteImport.update({
  id: '/pit',
  path: '/pit',
  getParentRoute: () => Fm23LiveRoute,
} as any)
const Fm23SetupsIndexRoute = Fm23SetupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Fm23SetupsRoute,
} as any)
const Fm23SetupsCatalogRoute = Fm23SetupsCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => Fm23SetupsRoute,
} as any)
const Fm23SetupsNewRoute = Fm23SetupsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => Fm23SetupsRoute,
} as any)
const IracingLiveDriverRoute = IracingLiveDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => IracingLiveRoute,
} as any)
const IracingLivePitRoute = IracingLivePitRouteImport.update({
  id: '/pit',
  path: '/pit',
  getParentRoute: () => IracingLiveRoute,
} as any)
const GameidTracksTrackOrdinalIndexRoute =
  GameidTracksTrackOrdinalIndexRouteImport.update({
    id: '/$trackOrdinal/',
    path: '/$trackOrdinal/',
    getParentRoute: () => GameidTracksRoute,
  } as any)
const GameidTracksTrackOrdinalTabRoute =
  GameidTracksTrackOrdinalTabRouteImport.update({
    id: '/$trackOrdinal/$tab',
    path: '/$trackOrdinal/$tab',
    getParentRoute: () => GameidTracksRoute,
  } as any)
const AcEvoExperimentsExperimentIdReviewRoute =
  AcEvoExperimentsExperimentIdReviewRouteImport.update({
    id: '/$experimentId_/review',
    path: '/$experimentId/review',
    getParentRoute: () => AcEvoExperimentsRoute,
  } as any)
const AcEvoSetupsEditTuneIdRoute = AcEvoSetupsEditTuneIdRouteImport.update({
  id: '/edit/$tuneId',
  path: '/edit/$tuneId',
  getParentRoute: () => AcEvoSetupsRoute,
} as any)
const AccExperimentsExperimentIdReviewRoute =
  AccExperimentsExperimentIdReviewRouteImport.update({
    id: '/$experimentId_/review',
    path: '/$experimentId/review',
    getParentRoute: () => AccExperimentsRoute,
  } as any)
const AccSetupsEditTuneIdRoute = AccSetupsEditTuneIdRouteImport.update({
  id: '/edit/$tuneId',
  path: '/edit/$tuneId',
  getParentRoute: () => AccSetupsRoute,
} as any)
const F125ExperimentsExperimentIdReviewRoute =
  F125ExperimentsExperimentIdReviewRouteImport.update({
    id: '/$experimentId_/review',
    path: '/$experimentId/review',
    getParentRoute: () => F125ExperimentsRoute,
  } as any)
const Fm23SetupsEditTuneIdRoute = Fm23SetupsEditTuneIdRouteImport.update({
  id: '/edit/$tuneId',
  path: '/edit/$tuneId',
  getParentRoute: () => Fm23SetupsRoute,
} as any)
const Fm23SetupsWheelIndexRoute = Fm23SetupsWheelIndexRouteImport.update({
  id: '/wheel/',
  path: '/wheel/',
  getParentRoute: () => Fm23SetupsRoute,
} as any)
const Fm23SetupsWheelProfileIdRoute =
  Fm23SetupsWheelProfileIdRouteImport.update({
    id: '/wheel/$profileId',
    path: '/wheel/$profileId',
    getParentRoute: () => Fm23SetupsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$gameid': typeof GameidRouteWithChildren
  '/ac-evo': typeof AcEvoRouteWithChildren
  '/acc': typeof AccRouteWithChildren
  '/dev': typeof DevRoute
  '/f125': typeof F125RouteWithChildren
  '/fm23': typeof Fm23RouteWithChildren
  '/iracing': typeof IracingRouteWithChildren
  '/$game/live': typeof GameLiveRoute
  '/$gameid/cars': typeof GameidCarsRoute
  '/$gameid/compare': typeof GameidCompareRoute
  '/$gameid/tracks': typeof GameidTracksRouteWithChildren
  '/ac-evo/analyse': typeof AcEvoAnalyseRoute
  '/ac-evo/chats': typeof AcEvoChatsRoute
  '/ac-evo/driver': typeof AcEvoDriverRoute
  '/ac-evo/experiments': typeof AcEvoExperimentsRouteWithChildren
  '/ac-evo/raw': typeof AcEvoRawRoute
  '/ac-evo/sessions': typeof AcEvoSessionsRoute
  '/ac-evo/setups': typeof AcEvoSetupsRouteWithChildren
  '/acc/analyse': typeof AccAnalyseRoute
  '/acc/chats': typeof AccChatsRoute
  '/acc/driver': typeof AccDriverRoute
  '/acc/experiments': typeof AccExperimentsRouteWithChildren
  '/acc/raw': typeof AccRawRoute
  '/acc/sessions': typeof AccSessionsRoute
  '/acc/setups': typeof AccSetupsRouteWithChildren
  '/dash/combo-1': typeof DashCombo1Route
  '/dash/combo-2': typeof DashCombo2Route
  '/f125/analyse': typeof F125AnalyseRoute
  '/f125/chats': typeof F125ChatsRoute
  '/f125/driver': typeof F125DriverRoute
  '/f125/experiments': typeof F125ExperimentsRouteWithChildren
  '/f125/raw': typeof F125RawRoute
  '/f125/sessions': typeof F125SessionsRoute
  '/f125/setups': typeof F125SetupsRouteWithChildren
  '/f125/tunes': typeof F125TunesRouteWithChildren
  '/fm23/analyse': typeof Fm23AnalyseRoute
  '/fm23/chats': typeof Fm23ChatsRoute
  '/fm23/driver': typeof Fm23DriverRoute
  '/fm23/live': typeof Fm23LiveRouteWithChildren
  '/fm23/raw': typeof Fm23RawRoute
  '/fm23/sessions': typeof Fm23SessionsRoute
  '/fm23/setups': typeof Fm23SetupsRouteWithChildren
  '/iracing/analyse': typeof IracingAnalyseRoute
  '/iracing/chats': typeof IracingChatsRoute
  '/iracing/live': typeof IracingLiveRouteWithChildren
  '/iracing/raw': typeof IracingRawRoute
  '/iracing/sessions': typeof IracingSessionsRoute
  '/ac-evo/': typeof AcEvoIndexRoute
  '/acc/': typeof AccIndexRoute
  '/dash/': typeof DashIndexRoute
  '/f125/': typeof F125IndexRoute
  '/fm23/': typeof Fm23IndexRoute
  '/iracing/': typeof IracingIndexRoute
  '/ac-evo/experiments/$experimentId': typeof AcEvoExperimentsExperimentIdRoute
  '/ac-evo/setups/import': typeof AcEvoSetupsImportRoute
  '/ac-evo/setups/new': typeof AcEvoSetupsNewRoute
  '/acc/experiments/$experimentId': typeof AccExperimentsExperimentIdRoute
  '/acc/setups/import': typeof AccSetupsImportRoute
  '/acc/setups/new': typeof AccSetupsNewRoute
  '/f125/experiments/$experimentId': typeof F125ExperimentsExperimentIdRoute
  '/fm23/cars/$carOrdinal': typeof Fm23CarsCarOrdinalRoute
  '/fm23/live/driver': typeof Fm23LiveDriverRoute
  '/fm23/live/pit': typeof Fm23LivePitRoute
  '/fm23/setups/catalog': typeof Fm23SetupsCatalogRoute
  '/fm23/setups/new': typeof Fm23SetupsNewRoute
  '/iracing/live/driver': typeof IracingLiveDriverRoute
  '/iracing/live/pit': typeof IracingLivePitRoute
  '/$gameid/tracks/': typeof GameidTracksIndexRoute
  '/ac-evo/experiments/': typeof AcEvoExperimentsIndexRoute
  '/ac-evo/setups/': typeof AcEvoSetupsIndexRoute
  '/acc/experiments/': typeof AccExperimentsIndexRoute
  '/acc/setups/': typeof AccSetupsIndexRoute
  '/f125/experiments/': typeof F125ExperimentsIndexRoute
  '/f125/setups/': typeof F125SetupsIndexRoute
  '/f125/tunes/': typeof F125TunesIndexRoute
  '/fm23/setups/': typeof Fm23SetupsIndexRoute
  '/$gameid/tracks/$trackOrdinal/$tab': typeof GameidTracksTrackOrdinalTabRoute
  '/ac-evo/experiments/$experimentId/review': typeof AcEvoExperimentsExperimentIdReviewRoute
  '/ac-evo/setups/edit/$tuneId': typeof AcEvoSetupsEditTuneIdRoute
  '/acc/experiments/$experimentId/review': typeof AccExperimentsExperimentIdReviewRoute
  '/acc/setups/edit/$tuneId': typeof AccSetupsEditTuneIdRoute
  '/f125/experiments/$experimentId/review': typeof F125ExperimentsExperimentIdReviewRoute
  '/fm23/setups/edit/$tuneId': typeof Fm23SetupsEditTuneIdRoute
  '/fm23/setups/wheel/$profileId': typeof Fm23SetupsWheelProfileIdRoute
  '/$gameid/tracks/$trackOrdinal/': typeof GameidTracksTrackOrdinalIndexRoute
  '/fm23/setups/wheel/': typeof Fm23SetupsWheelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$gameid': typeof GameidRouteWithChildren
  '/dev': typeof DevRoute
  '/$game/live': typeof GameLiveRoute
  '/$gameid/cars': typeof GameidCarsRoute
  '/$gameid/compare': typeof GameidCompareRoute
  '/ac-evo/analyse': typeof AcEvoAnalyseRoute
  '/ac-evo/chats': typeof AcEvoChatsRoute
  '/ac-evo/driver': typeof AcEvoDriverRoute
  '/ac-evo/raw': typeof AcEvoRawRoute
  '/ac-evo/sessions': typeof AcEvoSessionsRoute
  '/acc/analyse': typeof AccAnalyseRoute
  '/acc/chats': typeof AccChatsRoute
  '/acc/driver': typeof AccDriverRoute
  '/acc/raw': typeof AccRawRoute
  '/acc/sessions': typeof AccSessionsRoute
  '/dash/combo-1': typeof DashCombo1Route
  '/dash/combo-2': typeof DashCombo2Route
  '/f125/analyse': typeof F125AnalyseRoute
  '/f125/chats': typeof F125ChatsRoute
  '/f125/driver': typeof F125DriverRoute
  '/f125/raw': typeof F125RawRoute
  '/f125/sessions': typeof F125SessionsRoute
  '/fm23/analyse': typeof Fm23AnalyseRoute
  '/fm23/chats': typeof Fm23ChatsRoute
  '/fm23/driver': typeof Fm23DriverRoute
  '/fm23/live': typeof Fm23LiveRouteWithChildren
  '/fm23/raw': typeof Fm23RawRoute
  '/fm23/sessions': typeof Fm23SessionsRoute
  '/iracing/analyse': typeof IracingAnalyseRoute
  '/iracing/chats': typeof IracingChatsRoute
  '/iracing/live': typeof IracingLiveRouteWithChildren
  '/iracing/raw': typeof IracingRawRoute
  '/iracing/sessions': typeof IracingSessionsRoute
  '/ac-evo': typeof AcEvoIndexRoute
  '/acc': typeof AccIndexRoute
  '/dash': typeof DashIndexRoute
  '/f125': typeof F125IndexRoute
  '/fm23': typeof Fm23IndexRoute
  '/iracing': typeof IracingIndexRoute
  '/ac-evo/experiments/$experimentId': typeof AcEvoExperimentsExperimentIdRoute
  '/ac-evo/setups/import': typeof AcEvoSetupsImportRoute
  '/ac-evo/setups/new': typeof AcEvoSetupsNewRoute
  '/acc/experiments/$experimentId': typeof AccExperimentsExperimentIdRoute
  '/acc/setups/import': typeof AccSetupsImportRoute
  '/acc/setups/new': typeof AccSetupsNewRoute
  '/f125/experiments/$experimentId': typeof F125ExperimentsExperimentIdRoute
  '/fm23/cars/$carOrdinal': typeof Fm23CarsCarOrdinalRoute
  '/fm23/live/driver': typeof Fm23LiveDriverRoute
  '/fm23/live/pit': typeof Fm23LivePitRoute
  '/fm23/setups/catalog': typeof Fm23SetupsCatalogRoute
  '/fm23/setups/new': typeof Fm23SetupsNewRoute
  '/iracing/live/driver': typeof IracingLiveDriverRoute
  '/iracing/live/pit': typeof IracingLivePitRoute
  '/$gameid/tracks': typeof GameidTracksIndexRoute
  '/ac-evo/experiments': typeof AcEvoExperimentsIndexRoute
  '/ac-evo/setups': typeof AcEvoSetupsIndexRoute
  '/acc/experiments': typeof AccExperimentsIndexRoute
  '/acc/setups': typeof AccSetupsIndexRoute
  '/f125/experiments': typeof F125ExperimentsIndexRoute
  '/f125/setups': typeof F125SetupsIndexRoute
  '/f125/tunes': typeof F125TunesIndexRoute
  '/fm23/setups': typeof Fm23SetupsIndexRoute
  '/$gameid/tracks/$trackOrdinal/$tab': typeof GameidTracksTrackOrdinalTabRoute
  '/ac-evo/experiments/$experimentId/review': typeof AcEvoExperimentsExperimentIdReviewRoute
  '/ac-evo/setups/edit/$tuneId': typeof AcEvoSetupsEditTuneIdRoute
  '/acc/experiments/$experimentId/review': typeof AccExperimentsExperimentIdReviewRoute
  '/acc/setups/edit/$tuneId': typeof AccSetupsEditTuneIdRoute
  '/f125/experiments/$experimentId/review': typeof F125ExperimentsExperimentIdReviewRoute
  '/fm23/setups/edit/$tuneId': typeof Fm23SetupsEditTuneIdRoute
  '/fm23/setups/wheel/$profileId': typeof Fm23SetupsWheelProfileIdRoute
  '/$gameid/tracks/$trackOrdinal': typeof GameidTracksTrackOrdinalIndexRoute
  '/fm23/setups/wheel': typeof Fm23SetupsWheelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$gameid': typeof GameidRouteWithChildren
  '/ac-evo': typeof AcEvoRouteWithChildren
  '/acc': typeof AccRouteWithChildren
  '/dev': typeof DevRoute
  '/f125': typeof F125RouteWithChildren
  '/fm23': typeof Fm23RouteWithChildren
  '/iracing': typeof IracingRouteWithChildren
  '/$game/live': typeof GameLiveRoute
  '/$gameid/cars': typeof GameidCarsRoute
  '/$gameid/compare': typeof GameidCompareRoute
  '/$gameid/tracks': typeof GameidTracksRouteWithChildren
  '/ac-evo/analyse': typeof AcEvoAnalyseRoute
  '/ac-evo/chats': typeof AcEvoChatsRoute
  '/ac-evo/driver': typeof AcEvoDriverRoute
  '/ac-evo/experiments': typeof AcEvoExperimentsRouteWithChildren
  '/ac-evo/raw': typeof AcEvoRawRoute
  '/ac-evo/sessions': typeof AcEvoSessionsRoute
  '/ac-evo/setups': typeof AcEvoSetupsRouteWithChildren
  '/acc/analyse': typeof AccAnalyseRoute
  '/acc/chats': typeof AccChatsRoute
  '/acc/driver': typeof AccDriverRoute
  '/acc/experiments': typeof AccExperimentsRouteWithChildren
  '/acc/raw': typeof AccRawRoute
  '/acc/sessions': typeof AccSessionsRoute
  '/acc/setups': typeof AccSetupsRouteWithChildren
  '/dash/combo-1': typeof DashCombo1Route
  '/dash/combo-2': typeof DashCombo2Route
  '/f125/analyse': typeof F125AnalyseRoute
  '/f125/chats': typeof F125ChatsRoute
  '/f125/driver': typeof F125DriverRoute
  '/f125/experiments': typeof F125ExperimentsRouteWithChildren
  '/f125/raw': typeof F125RawRoute
  '/f125/sessions': typeof F125SessionsRoute
  '/f125/setups': typeof F125SetupsRouteWithChildren
  '/f125/tunes': typeof F125TunesRouteWithChildren
  '/fm23/analyse': typeof Fm23AnalyseRoute
  '/fm23/chats': typeof Fm23ChatsRoute
  '/fm23/driver': typeof Fm23DriverRoute
  '/fm23/live': typeof Fm23LiveRouteWithChildren
  '/fm23/raw': typeof Fm23RawRoute
  '/fm23/sessions': typeof Fm23SessionsRoute
  '/fm23/setups': typeof Fm23SetupsRouteWithChildren
  '/iracing/analyse': typeof IracingAnalyseRoute
  '/iracing/chats': typeof IracingChatsRoute
  '/iracing/live': typeof IracingLiveRouteWithChildren
  '/iracing/raw': typeof IracingRawRoute
  '/iracing/sessions': typeof IracingSessionsRoute
  '/ac-evo/': typeof AcEvoIndexRoute
  '/acc/': typeof AccIndexRoute
  '/dash/': typeof DashIndexRoute
  '/f125/': typeof F125IndexRoute
  '/fm23/': typeof Fm23IndexRoute
  '/iracing/': typeof IracingIndexRoute
  '/ac-evo/experiments/$experimentId': typeof AcEvoExperimentsExperimentIdRoute
  '/ac-evo/setups/import': typeof AcEvoSetupsImportRoute
  '/ac-evo/setups/new': typeof AcEvoSetupsNewRoute
  '/acc/experiments/$experimentId': typeof AccExperimentsExperimentIdRoute
  '/acc/setups/import': typeof AccSetupsImportRoute
  '/acc/setups/new': typeof AccSetupsNewRoute
  '/f125/experiments/$experimentId': typeof F125ExperimentsExperimentIdRoute
  '/fm23/cars_/$carOrdinal': typeof Fm23CarsCarOrdinalRoute
  '/fm23/live/driver': typeof Fm23LiveDriverRoute
  '/fm23/live/pit': typeof Fm23LivePitRoute
  '/fm23/setups/catalog': typeof Fm23SetupsCatalogRoute
  '/fm23/setups/new': typeof Fm23SetupsNewRoute
  '/iracing/live/driver': typeof IracingLiveDriverRoute
  '/iracing/live/pit': typeof IracingLivePitRoute
  '/$gameid/tracks/': typeof GameidTracksIndexRoute
  '/ac-evo/experiments/': typeof AcEvoExperimentsIndexRoute
  '/ac-evo/setups/': typeof AcEvoSetupsIndexRoute
  '/acc/experiments/': typeof AccExperimentsIndexRoute
  '/acc/setups/': typeof AccSetupsIndexRoute
  '/f125/experiments/': typeof F125ExperimentsIndexRoute
  '/f125/setups/': typeof F125SetupsIndexRoute
  '/f125/tunes/': typeof F125TunesIndexRoute
  '/fm23/setups/': typeof Fm23SetupsIndexRoute
  '/$gameid/tracks/$trackOrdinal/$tab': typeof GameidTracksTrackOrdinalTabRoute
  '/ac-evo/experiments/$experimentId_/review': typeof AcEvoExperimentsExperimentIdReviewRoute
  '/ac-evo/setups/edit/$tuneId': typeof AcEvoSetupsEditTuneIdRoute
  '/acc/experiments/$experimentId_/review': typeof AccExperimentsExperimentIdReviewRoute
  '/acc/setups/edit/$tuneId': typeof AccSetupsEditTuneIdRoute
  '/f125/experiments/$experimentId_/review': typeof F125ExperimentsExperimentIdReviewRoute
  '/fm23/setups/edit/$tuneId': typeof Fm23SetupsEditTuneIdRoute
  '/fm23/setups/wheel/$profileId': typeof Fm23SetupsWheelProfileIdRoute
  '/$gameid/tracks/$trackOrdinal/': typeof GameidTracksTrackOrdinalIndexRoute
  '/fm23/setups/wheel/': typeof Fm23SetupsWheelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$gameid'
    | '/ac-evo'
    | '/acc'
    | '/dev'
    | '/f125'
    | '/fm23'
    | '/iracing'
    | '/$game/live'
    | '/$gameid/cars'
    | '/$gameid/compare'
    | '/$gameid/tracks'
    | '/ac-evo/analyse'
    | '/ac-evo/chats'
    | '/ac-evo/driver'
    | '/ac-evo/experiments'
    | '/ac-evo/raw'
    | '/ac-evo/sessions'
    | '/ac-evo/setups'
    | '/acc/analyse'
    | '/acc/chats'
    | '/acc/driver'
    | '/acc/experiments'
    | '/acc/raw'
    | '/acc/sessions'
    | '/acc/setups'
    | '/dash/combo-1'
    | '/dash/combo-2'
    | '/f125/analyse'
    | '/f125/chats'
    | '/f125/driver'
    | '/f125/experiments'
    | '/f125/raw'
    | '/f125/sessions'
    | '/f125/setups'
    | '/f125/tunes'
    | '/fm23/analyse'
    | '/fm23/chats'
    | '/fm23/driver'
    | '/fm23/live'
    | '/fm23/raw'
    | '/fm23/sessions'
    | '/fm23/setups'
    | '/iracing/analyse'
    | '/iracing/chats'
    | '/iracing/live'
    | '/iracing/raw'
    | '/iracing/sessions'
    | '/ac-evo/'
    | '/acc/'
    | '/dash/'
    | '/f125/'
    | '/fm23/'
    | '/iracing/'
    | '/ac-evo/experiments/$experimentId'
    | '/ac-evo/setups/import'
    | '/ac-evo/setups/new'
    | '/acc/experiments/$experimentId'
    | '/acc/setups/import'
    | '/acc/setups/new'
    | '/f125/experiments/$experimentId'
    | '/fm23/cars/$carOrdinal'
    | '/fm23/live/driver'
    | '/fm23/live/pit'
    | '/fm23/setups/catalog'
    | '/fm23/setups/new'
    | '/iracing/live/driver'
    | '/iracing/live/pit'
    | '/$gameid/tracks/'
    | '/ac-evo/experiments/'
    | '/ac-evo/setups/'
    | '/acc/experiments/'
    | '/acc/setups/'
    | '/f125/experiments/'
    | '/f125/setups/'
    | '/f125/tunes/'
    | '/fm23/setups/'
    | '/$gameid/tracks/$trackOrdinal/$tab'
    | '/ac-evo/experiments/$experimentId/review'
    | '/ac-evo/setups/edit/$tuneId'
    | '/acc/experiments/$experimentId/review'
    | '/acc/setups/edit/$tuneId'
    | '/f125/experiments/$experimentId/review'
    | '/fm23/setups/edit/$tuneId'
    | '/fm23/setups/wheel/$profileId'
    | '/$gameid/tracks/$trackOrdinal/'
    | '/fm23/setups/wheel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$gameid'
    | '/dev'
    | '/$game/live'
    | '/$gameid/cars'
    | '/$gameid/compare'
    | '/ac-evo/analyse'
    | '/ac-evo/chats'
    | '/ac-evo/driver'
    | '/ac-evo/raw'
    | '/ac-evo/sessions'
    | '/acc/analyse'
    | '/acc/chats'
    | '/acc/driver'
    | '/acc/raw'
    | '/acc/sessions'
    | '/dash/combo-1'
    | '/dash/combo-2'
    | '/f125/analyse'
    | '/f125/chats'
    | '/f125/driver'
    | '/f125/raw'
    | '/f125/sessions'
    | '/fm23/analyse'
    | '/fm23/chats'
    | '/fm23/driver'
    | '/fm23/live'
    | '/fm23/raw'
    | '/fm23/sessions'
    | '/iracing/analyse'
    | '/iracing/chats'
    | '/iracing/live'
    | '/iracing/raw'
    | '/iracing/sessions'
    | '/ac-evo'
    | '/acc'
    | '/dash'
    | '/f125'
    | '/fm23'
    | '/iracing'
    | '/ac-evo/experiments/$experimentId'
    | '/ac-evo/setups/import'
    | '/ac-evo/setups/new'
    | '/acc/experiments/$experimentId'
    | '/acc/setups/import'
    | '/acc/setups/new'
    | '/f125/experiments/$experimentId'
    | '/fm23/cars/$carOrdinal'
    | '/fm23/live/driver'
    | '/fm23/live/pit'
    | '/fm23/setups/catalog'
    | '/fm23/setups/new'
    | '/iracing/live/driver'
    | '/iracing/live/pit'
    | '/$gameid/tracks'
    | '/ac-evo/experiments'
    | '/ac-evo/setups'
    | '/acc/experiments'
    | '/acc/setups'
    | '/f125/experiments'
    | '/f125/setups'
    | '/f125/tunes'
    | '/fm23/setups'
    | '/$gameid/tracks/$trackOrdinal/$tab'
    | '/ac-evo/experiments/$experimentId/review'
    | '/ac-evo/setups/edit/$tuneId'
    | '/acc/experiments/$experimentId/review'
    | '/acc/setups/edit/$tuneId'
    | '/f125/experiments/$experimentId/review'
    | '/fm23/setups/edit/$tuneId'
    | '/fm23/setups/wheel/$profileId'
    | '/$gameid/tracks/$trackOrdinal'
    | '/fm23/setups/wheel'
  id:
    | '__root__'
    | '/'
    | '/$gameid'
    | '/ac-evo'
    | '/acc'
    | '/dev'
    | '/f125'
    | '/fm23'
    | '/iracing'
    | '/$game/live'
    | '/$gameid/cars'
    | '/$gameid/compare'
    | '/$gameid/tracks'
    | '/ac-evo/analyse'
    | '/ac-evo/chats'
    | '/ac-evo/driver'
    | '/ac-evo/experiments'
    | '/ac-evo/raw'
    | '/ac-evo/sessions'
    | '/ac-evo/setups'
    | '/acc/analyse'
    | '/acc/chats'
    | '/acc/driver'
    | '/acc/experiments'
    | '/acc/raw'
    | '/acc/sessions'
    | '/acc/setups'
    | '/dash/combo-1'
    | '/dash/combo-2'
    | '/f125/analyse'
    | '/f125/chats'
    | '/f125/driver'
    | '/f125/experiments'
    | '/f125/raw'
    | '/f125/sessions'
    | '/f125/setups'
    | '/f125/tunes'
    | '/fm23/analyse'
    | '/fm23/chats'
    | '/fm23/driver'
    | '/fm23/live'
    | '/fm23/raw'
    | '/fm23/sessions'
    | '/fm23/setups'
    | '/iracing/analyse'
    | '/iracing/chats'
    | '/iracing/live'
    | '/iracing/raw'
    | '/iracing/sessions'
    | '/ac-evo/'
    | '/acc/'
    | '/dash/'
    | '/f125/'
    | '/fm23/'
    | '/iracing/'
    | '/ac-evo/experiments/$experimentId'
    | '/ac-evo/setups/import'
    | '/ac-evo/setups/new'
    | '/acc/experiments/$experimentId'
    | '/acc/setups/import'
    | '/acc/setups/new'
    | '/f125/experiments/$experimentId'
    | '/fm23/cars_/$carOrdinal'
    | '/fm23/live/driver'
    | '/fm23/live/pit'
    | '/fm23/setups/catalog'
    | '/fm23/setups/new'
    | '/iracing/live/driver'
    | '/iracing/live/pit'
    | '/$gameid/tracks/'
    | '/ac-evo/experiments/'
    | '/ac-evo/setups/'
    | '/acc/experiments/'
    | '/acc/setups/'
    | '/f125/experiments/'
    | '/f125/setups/'
    | '/f125/tunes/'
    | '/fm23/setups/'
    | '/$gameid/tracks/$trackOrdinal/$tab'
    | '/ac-evo/experiments/$experimentId_/review'
    | '/ac-evo/setups/edit/$tuneId'
    | '/acc/experiments/$experimentId_/review'
    | '/acc/setups/edit/$tuneId'
    | '/f125/experiments/$experimentId_/review'
    | '/fm23/setups/edit/$tuneId'
    | '/fm23/setups/wheel/$profileId'
    | '/$gameid/tracks/$trackOrdinal/'
    | '/fm23/setups/wheel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameidRoute: typeof GameidRouteWithChildren
  AcEvoRoute: typeof AcEvoRouteWithChildren
  AccRoute: typeof AccRouteWithChildren
  DevRoute: typeof DevRoute
  F125Route: typeof F125RouteWithChildren
  Fm23Route: typeof Fm23RouteWithChildren
  IracingRoute: typeof IracingRouteWithChildren
  GameLiveRoute: typeof GameLiveRoute
  DashCombo1Route: typeof DashCombo1Route
  DashCombo2Route: typeof DashCombo2Route
  DashIndexRoute: typeof DashIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$gameid': {
      id: '/$gameid'
      path: '/$gameid'
      fullPath: '/$gameid'
      preLoaderRoute: typeof GameidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ac-evo': {
      id: '/ac-evo'
      path: '/ac-evo'
      fullPath: '/ac-evo'
      preLoaderRoute: typeof AcEvoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acc': {
      id: '/acc'
      path: '/acc'
      fullPath: '/acc'
      preLoaderRoute: typeof AccRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f125': {
      id: '/f125'
      path: '/f125'
      fullPath: '/f125'
      preLoaderRoute: typeof F125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fm23': {
      id: '/fm23'
      path: '/fm23'
      fullPath: '/fm23'
      preLoaderRoute: typeof Fm23RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iracing': {
      id: '/iracing'
      path: '/iracing'
      fullPath: '/iracing'
      preLoaderRoute: typeof IracingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$game/live': {
      id: '/$game/live'
      path: '/$game/live'
      fullPath: '/$game/live'
      preLoaderRoute: typeof GameLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$gameid/cars': {
      id: '/$gameid/cars'
      path: '/cars'
      fullPath: '/$gameid/cars'
      preLoaderRoute: typeof GameidCarsRouteImport
      parentRoute: typeof GameidRoute
    }
    '/$gameid/compare': {
      id: '/$gameid/compare'
      path: '/compare'
      fullPath: '/$gameid/compare'
      preLoaderRoute: typeof GameidCompareRouteImport
      parentRoute: typeof GameidRoute
    }
    '/$gameid/tracks': {
      id: '/$gameid/tracks'
      path: '/tracks'
      fullPath: '/$gameid/tracks'
      preLoaderRoute: typeof GameidTracksRouteImport
      parentRoute: typeof GameidRoute
    }
    '/ac-evo/': {
      id: '/ac-evo/'
      path: '/'
      fullPath: '/ac-evo/'
      preLoaderRoute: typeof AcEvoIndexRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/analyse': {
      id: '/ac-evo/analyse'
      path: '/analyse'
      fullPath: '/ac-evo/analyse'
      preLoaderRoute: typeof AcEvoAnalyseRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/chats': {
      id: '/ac-evo/chats'
      path: '/chats'
      fullPath: '/ac-evo/chats'
      preLoaderRoute: typeof AcEvoChatsRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/driver': {
      id: '/ac-evo/driver'
      path: '/driver'
      fullPath: '/ac-evo/driver'
      preLoaderRoute: typeof AcEvoDriverRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/experiments': {
      id: '/ac-evo/experiments'
      path: '/experiments'
      fullPath: '/ac-evo/experiments'
      preLoaderRoute: typeof AcEvoExperimentsRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/raw': {
      id: '/ac-evo/raw'
      path: '/raw'
      fullPath: '/ac-evo/raw'
      preLoaderRoute: typeof AcEvoRawRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/sessions': {
      id: '/ac-evo/sessions'
      path: '/sessions'
      fullPath: '/ac-evo/sessions'
      preLoaderRoute: typeof AcEvoSessionsRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/setups': {
      id: '/ac-evo/setups'
      path: '/setups'
      fullPath: '/ac-evo/setups'
      preLoaderRoute: typeof AcEvoSetupsRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/acc/': {
      id: '/acc/'
      path: '/'
      fullPath: '/acc/'
      preLoaderRoute: typeof AccIndexRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/analyse': {
      id: '/acc/analyse'
      path: '/analyse'
      fullPath: '/acc/analyse'
      preLoaderRoute: typeof AccAnalyseRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/chats': {
      id: '/acc/chats'
      path: '/chats'
      fullPath: '/acc/chats'
      preLoaderRoute: typeof AccChatsRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/driver': {
      id: '/acc/driver'
      path: '/driver'
      fullPath: '/acc/driver'
      preLoaderRoute: typeof AccDriverRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/experiments': {
      id: '/acc/experiments'
      path: '/experiments'
      fullPath: '/acc/experiments'
      preLoaderRoute: typeof AccExperimentsRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/raw': {
      id: '/acc/raw'
      path: '/raw'
      fullPath: '/acc/raw'
      preLoaderRoute: typeof AccRawRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/sessions': {
      id: '/acc/sessions'
      path: '/sessions'
      fullPath: '/acc/sessions'
      preLoaderRoute: typeof AccSessionsRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/setups': {
      id: '/acc/setups'
      path: '/setups'
      fullPath: '/acc/setups'
      preLoaderRoute: typeof AccSetupsRouteImport
      parentRoute: typeof AccRoute
    }
    '/dash/': {
      id: '/dash/'
      path: '/dash'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/combo-1': {
      id: '/dash/combo-1'
      path: '/dash/combo-1'
      fullPath: '/dash/combo-1'
      preLoaderRoute: typeof DashCombo1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/combo-2': {
      id: '/dash/combo-2'
      path: '/dash/combo-2'
      fullPath: '/dash/combo-2'
      preLoaderRoute: typeof DashCombo2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f125/': {
      id: '/f125/'
      path: '/'
      fullPath: '/f125/'
      preLoaderRoute: typeof F125IndexRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/analyse': {
      id: '/f125/analyse'
      path: '/analyse'
      fullPath: '/f125/analyse'
      preLoaderRoute: typeof F125AnalyseRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/chats': {
      id: '/f125/chats'
      path: '/chats'
      fullPath: '/f125/chats'
      preLoaderRoute: typeof F125ChatsRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/driver': {
      id: '/f125/driver'
      path: '/driver'
      fullPath: '/f125/driver'
      preLoaderRoute: typeof F125DriverRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/experiments': {
      id: '/f125/experiments'
      path: '/experiments'
      fullPath: '/f125/experiments'
      preLoaderRoute: typeof F125ExperimentsRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/raw': {
      id: '/f125/raw'
      path: '/raw'
      fullPath: '/f125/raw'
      preLoaderRoute: typeof F125RawRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/sessions': {
      id: '/f125/sessions'
      path: '/sessions'
      fullPath: '/f125/sessions'
      preLoaderRoute: typeof F125SessionsRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/setups': {
      id: '/f125/setups'
      path: '/setups'
      fullPath: '/f125/setups'
      preLoaderRoute: typeof F125SetupsRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/tunes': {
      id: '/f125/tunes'
      path: '/tunes'
      fullPath: '/f125/tunes'
      preLoaderRoute: typeof F125TunesRouteImport
      parentRoute: typeof F125Route
    }
    '/fm23/': {
      id: '/fm23/'
      path: '/'
      fullPath: '/fm23/'
      preLoaderRoute: typeof Fm23IndexRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/analyse': {
      id: '/fm23/analyse'
      path: '/analyse'
      fullPath: '/fm23/analyse'
      preLoaderRoute: typeof Fm23AnalyseRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/chats': {
      id: '/fm23/chats'
      path: '/chats'
      fullPath: '/fm23/chats'
      preLoaderRoute: typeof Fm23ChatsRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/driver': {
      id: '/fm23/driver'
      path: '/driver'
      fullPath: '/fm23/driver'
      preLoaderRoute: typeof Fm23DriverRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/live': {
      id: '/fm23/live'
      path: '/live'
      fullPath: '/fm23/live'
      preLoaderRoute: typeof Fm23LiveRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/raw': {
      id: '/fm23/raw'
      path: '/raw'
      fullPath: '/fm23/raw'
      preLoaderRoute: typeof Fm23RawRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/sessions': {
      id: '/fm23/sessions'
      path: '/sessions'
      fullPath: '/fm23/sessions'
      preLoaderRoute: typeof Fm23SessionsRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/setups': {
      id: '/fm23/setups'
      path: '/setups'
      fullPath: '/fm23/setups'
      preLoaderRoute: typeof Fm23SetupsRouteImport
      parentRoute: typeof Fm23Route
    }
    '/iracing/': {
      id: '/iracing/'
      path: '/'
      fullPath: '/iracing/'
      preLoaderRoute: typeof IracingIndexRouteImport
      parentRoute: typeof IracingRoute
    }
    '/iracing/analyse': {
      id: '/iracing/analyse'
      path: '/analyse'
      fullPath: '/iracing/analyse'
      preLoaderRoute: typeof IracingAnalyseRouteImport
      parentRoute: typeof IracingRoute
    }
    '/iracing/chats': {
      id: '/iracing/chats'
      path: '/chats'
      fullPath: '/iracing/chats'
      preLoaderRoute: typeof IracingChatsRouteImport
      parentRoute: typeof IracingRoute
    }
    '/iracing/live': {
      id: '/iracing/live'
      path: '/live'
      fullPath: '/iracing/live'
      preLoaderRoute: typeof IracingLiveRouteImport
      parentRoute: typeof IracingRoute
    }
    '/iracing/raw': {
      id: '/iracing/raw'
      path: '/raw'
      fullPath: '/iracing/raw'
      preLoaderRoute: typeof IracingRawRouteImport
      parentRoute: typeof IracingRoute
    }
    '/iracing/sessions': {
      id: '/iracing/sessions'
      path: '/sessions'
      fullPath: '/iracing/sessions'
      preLoaderRoute: typeof IracingSessionsRouteImport
      parentRoute: typeof IracingRoute
    }
    '/$gameid/tracks/': {
      id: '/$gameid/tracks/'
      path: '/'
      fullPath: '/$gameid/tracks/'
      preLoaderRoute: typeof GameidTracksIndexRouteImport
      parentRoute: typeof GameidTracksRoute
    }
    '/ac-evo/experiments/': {
      id: '/ac-evo/experiments/'
      path: '/'
      fullPath: '/ac-evo/experiments/'
      preLoaderRoute: typeof AcEvoExperimentsIndexRouteImport
      parentRoute: typeof AcEvoExperimentsRoute
    }
    '/ac-evo/experiments/$experimentId': {
      id: '/ac-evo/experiments/$experimentId'
      path: '/$experimentId'
      fullPath: '/ac-evo/experiments/$experimentId'
      preLoaderRoute: typeof AcEvoExperimentsExperimentIdRouteImport
      parentRoute: typeof AcEvoExperimentsRoute
    }
    '/ac-evo/setups/': {
      id: '/ac-evo/setups/'
      path: '/'
      fullPath: '/ac-evo/setups/'
      preLoaderRoute: typeof AcEvoSetupsIndexRouteImport
      parentRoute: typeof AcEvoSetupsRoute
    }
    '/ac-evo/setups/import': {
      id: '/ac-evo/setups/import'
      path: '/import'
      fullPath: '/ac-evo/setups/import'
      preLoaderRoute: typeof AcEvoSetupsImportRouteImport
      parentRoute: typeof AcEvoSetupsRoute
    }
    '/ac-evo/setups/new': {
      id: '/ac-evo/setups/new'
      path: '/new'
      fullPath: '/ac-evo/setups/new'
      preLoaderRoute: typeof AcEvoSetupsNewRouteImport
      parentRoute: typeof AcEvoSetupsRoute
    }
    '/acc/experiments/': {
      id: '/acc/experiments/'
      path: '/'
      fullPath: '/acc/experiments/'
      preLoaderRoute: typeof AccExperimentsIndexRouteImport
      parentRoute: typeof AccExperimentsRoute
    }
    '/acc/experiments/$experimentId': {
      id: '/acc/experiments/$experimentId'
      path: '/$experimentId'
      fullPath: '/acc/experiments/$experimentId'
      preLoaderRoute: typeof AccExperimentsExperimentIdRouteImport
      parentRoute: typeof AccExperimentsRoute
    }
    '/acc/setups/': {
      id: '/acc/setups/'
      path: '/'
      fullPath: '/acc/setups/'
      preLoaderRoute: typeof AccSetupsIndexRouteImport
      parentRoute: typeof AccSetupsRoute
    }
    '/acc/setups/import': {
      id: '/acc/setups/import'
      path: '/import'
      fullPath: '/acc/setups/import'
      preLoaderRoute: typeof AccSetupsImportRouteImport
      parentRoute: typeof AccSetupsRoute
    }
    '/acc/setups/new': {
      id: '/acc/setups/new'
      path: '/new'
      fullPath: '/acc/setups/new'
      preLoaderRoute: typeof AccSetupsNewRouteImport
      parentRoute: typeof AccSetupsRoute
    }
    '/f125/experiments/': {
      id: '/f125/experiments/'
      path: '/'
      fullPath: '/f125/experiments/'
      preLoaderRoute: typeof F125ExperimentsIndexRouteImport
      parentRoute: typeof F125ExperimentsRoute
    }
    '/f125/experiments/$experimentId': {
      id: '/f125/experiments/$experimentId'
      path: '/$experimentId'
      fullPath: '/f125/experiments/$experimentId'
      preLoaderRoute: typeof F125ExperimentsExperimentIdRouteImport
      parentRoute: typeof F125ExperimentsRoute
    }
    '/f125/setups/': {
      id: '/f125/setups/'
      path: '/'
      fullPath: '/f125/setups/'
      preLoaderRoute: typeof F125SetupsIndexRouteImport
      parentRoute: typeof F125SetupsRoute
    }
    '/f125/tunes/': {
      id: '/f125/tunes/'
      path: '/'
      fullPath: '/f125/tunes/'
      preLoaderRoute: typeof F125TunesIndexRouteImport
      parentRoute: typeof F125TunesRoute
    }
    '/fm23/cars_/$carOrdinal': {
      id: '/fm23/cars_/$carOrdinal'
      path: '/cars/$carOrdinal'
      fullPath: '/fm23/cars/$carOrdinal'
      preLoaderRoute: typeof Fm23CarsCarOrdinalRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/live/driver': {
      id: '/fm23/live/driver'
      path: '/driver'
      fullPath: '/fm23/live/driver'
      preLoaderRoute: typeof Fm23LiveDriverRouteImport
      parentRoute: typeof Fm23LiveRoute
    }
    '/fm23/live/pit': {
      id: '/fm23/live/pit'
      path: '/pit'
      fullPath: '/fm23/live/pit'
      preLoaderRoute: typeof Fm23LivePitRouteImport
      parentRoute: typeof Fm23LiveRoute
    }
    '/fm23/setups/': {
      id: '/fm23/setups/'
      path: '/'
      fullPath: '/fm23/setups/'
      preLoaderRoute: typeof Fm23SetupsIndexRouteImport
      parentRoute: typeof Fm23SetupsRoute
    }
    '/fm23/setups/catalog': {
      id: '/fm23/setups/catalog'
      path: '/catalog'
      fullPath: '/fm23/setups/catalog'
      preLoaderRoute: typeof Fm23SetupsCatalogRouteImport
      parentRoute: typeof Fm23SetupsRoute
    }
    '/fm23/setups/new': {
      id: '/fm23/setups/new'
      path: '/new'
      fullPath: '/fm23/setups/new'
      preLoaderRoute: typeof Fm23SetupsNewRouteImport
      parentRoute: typeof Fm23SetupsRoute
    }
    '/iracing/live/driver': {
      id: '/iracing/live/driver'
      path: '/driver'
      fullPath: '/iracing/live/driver'
      preLoaderRoute: typeof IracingLiveDriverRouteImport
      parentRoute: typeof IracingLiveRoute
    }
    '/iracing/live/pit': {
      id: '/iracing/live/pit'
      path: '/pit'
      fullPath: '/iracing/live/pit'
      preLoaderRoute: typeof IracingLivePitRouteImport
      parentRoute: typeof IracingLiveRoute
    }
    '/$gameid/tracks/$trackOrdinal/': {
      id: '/$gameid/tracks/$trackOrdinal/'
      path: '/$trackOrdinal'
      fullPath: '/$gameid/tracks/$trackOrdinal/'
      preLoaderRoute: typeof GameidTracksTrackOrdinalIndexRouteImport
      parentRoute: typeof GameidTracksRoute
    }
    '/$gameid/tracks/$trackOrdinal/$tab': {
      id: '/$gameid/tracks/$trackOrdinal/$tab'
      path: '/$trackOrdinal/$tab'
      fullPath: '/$gameid/tracks/$trackOrdinal/$tab'
      preLoaderRoute: typeof GameidTracksTrackOrdinalTabRouteImport
      parentRoute: typeof GameidTracksRoute
    }
    '/ac-evo/experiments/$experimentId_/review': {
      id: '/ac-evo/experiments/$experimentId_/review'
      path: '/$experimentId/review'
      fullPath: '/ac-evo/experiments/$experimentId/review'
      preLoaderRoute: typeof AcEvoExperimentsExperimentIdReviewRouteImport
      parentRoute: typeof AcEvoExperimentsRoute
    }
    '/ac-evo/setups/edit/$tuneId': {
      id: '/ac-evo/setups/edit/$tuneId'
      path: '/edit/$tuneId'
      fullPath: '/ac-evo/setups/edit/$tuneId'
      preLoaderRoute: typeof AcEvoSetupsEditTuneIdRouteImport
      parentRoute: typeof AcEvoSetupsRoute
    }
    '/acc/experiments/$experimentId_/review': {
      id: '/acc/experiments/$experimentId_/review'
      path: '/$experimentId/review'
      fullPath: '/acc/experiments/$experimentId/review'
      preLoaderRoute: typeof AccExperimentsExperimentIdReviewRouteImport
      parentRoute: typeof AccExperimentsRoute
    }
    '/acc/setups/edit/$tuneId': {
      id: '/acc/setups/edit/$tuneId'
      path: '/edit/$tuneId'
      fullPath: '/acc/setups/edit/$tuneId'
      preLoaderRoute: typeof AccSetupsEditTuneIdRouteImport
      parentRoute: typeof AccSetupsRoute
    }
    '/f125/experiments/$experimentId_/review': {
      id: '/f125/experiments/$experimentId_/review'
      path: '/$experimentId/review'
      fullPath: '/f125/experiments/$experimentId/review'
      preLoaderRoute: typeof F125ExperimentsExperimentIdReviewRouteImport
      parentRoute: typeof F125ExperimentsRoute
    }
    '/fm23/setups/edit/$tuneId': {
      id: '/fm23/setups/edit/$tuneId'
      path: '/edit/$tuneId'
      fullPath: '/fm23/setups/edit/$tuneId'
      preLoaderRoute: typeof Fm23SetupsEditTuneIdRouteImport
      parentRoute: typeof Fm23SetupsRoute
    }
    '/fm23/setups/wheel/': {
      id: '/fm23/setups/wheel/'
      path: '/wheel'
      fullPath: '/fm23/setups/wheel/'
      preLoaderRoute: typeof Fm23SetupsWheelIndexRouteImport
      parentRoute: typeof Fm23SetupsRoute
    }
    '/fm23/setups/wheel/$profileId': {
      id: '/fm23/setups/wheel/$profileId'
      path: '/wheel/$profileId'
      fullPath: '/fm23/setups/wheel/$profileId'
      preLoaderRoute: typeof Fm23SetupsWheelProfileIdRouteImport
      parentRoute: typeof Fm23SetupsRoute
    }
  }
}

interface GameidTracksRouteChildren {
  GameidTracksIndexRoute: typeof GameidTracksIndexRoute
  GameidTracksTrackOrdinalTabRoute: typeof GameidTracksTrackOrdinalTabRoute
  GameidTracksTrackOrdinalIndexRoute: typeof GameidTracksTrackOrdinalIndexRoute
}

const GameidTracksRouteChildren: GameidTracksRouteChildren = {
  GameidTracksIndexRoute: GameidTracksIndexRoute,
  GameidTracksTrackOrdinalTabRoute: GameidTracksTrackOrdinalTabRoute,
  GameidTracksTrackOrdinalIndexRoute: GameidTracksTrackOrdinalIndexRoute,
}

const GameidTracksRouteWithChildren = GameidTracksRoute._addFileChildren(
  GameidTracksRouteChildren,
)

interface GameidRouteChildren {
  GameidCarsRoute: typeof GameidCarsRoute
  GameidCompareRoute: typeof GameidCompareRoute
  GameidTracksRoute: typeof GameidTracksRouteWithChildren
}

const GameidRouteChildren: GameidRouteChildren = {
  GameidCarsRoute: GameidCarsRoute,
  GameidCompareRoute: GameidCompareRoute,
  GameidTracksRoute: GameidTracksRouteWithChildren,
}

const GameidRouteWithChildren =
  GameidRoute._addFileChildren(GameidRouteChildren)

interface AcEvoExperimentsRouteChildren {
  AcEvoExperimentsExperimentIdRoute: typeof AcEvoExperimentsExperimentIdRoute
  AcEvoExperimentsIndexRoute: typeof AcEvoExperimentsIndexRoute
  AcEvoExperimentsExperimentIdReviewRoute: typeof AcEvoExperimentsExperimentIdReviewRoute
}

const AcEvoExperimentsRouteChildren: AcEvoExperimentsRouteChildren = {
  AcEvoExperimentsExperimentIdRoute: AcEvoExperimentsExperimentIdRoute,
  AcEvoExperimentsIndexRoute: AcEvoExperimentsIndexRoute,
  AcEvoExperimentsExperimentIdReviewRoute:
    AcEvoExperimentsExperimentIdReviewRoute,
}

const AcEvoExperimentsRouteWithChildren =
  AcEvoExperimentsRoute._addFileChildren(AcEvoExperimentsRouteChildren)

interface AcEvoSetupsRouteChildren {
  AcEvoSetupsImportRoute: typeof AcEvoSetupsImportRoute
  AcEvoSetupsNewRoute: typeof AcEvoSetupsNewRoute
  AcEvoSetupsIndexRoute: typeof AcEvoSetupsIndexRoute
  AcEvoSetupsEditTuneIdRoute: typeof AcEvoSetupsEditTuneIdRoute
}

const AcEvoSetupsRouteChildren: AcEvoSetupsRouteChildren = {
  AcEvoSetupsImportRoute: AcEvoSetupsImportRoute,
  AcEvoSetupsNewRoute: AcEvoSetupsNewRoute,
  AcEvoSetupsIndexRoute: AcEvoSetupsIndexRoute,
  AcEvoSetupsEditTuneIdRoute: AcEvoSetupsEditTuneIdRoute,
}

const AcEvoSetupsRouteWithChildren = AcEvoSetupsRoute._addFileChildren(
  AcEvoSetupsRouteChildren,
)

interface AcEvoRouteChildren {
  AcEvoAnalyseRoute: typeof AcEvoAnalyseRoute
  AcEvoChatsRoute: typeof AcEvoChatsRoute
  AcEvoDriverRoute: typeof AcEvoDriverRoute
  AcEvoExperimentsRoute: typeof AcEvoExperimentsRouteWithChildren
  AcEvoRawRoute: typeof AcEvoRawRoute
  AcEvoSessionsRoute: typeof AcEvoSessionsRoute
  AcEvoSetupsRoute: typeof AcEvoSetupsRouteWithChildren
  AcEvoIndexRoute: typeof AcEvoIndexRoute
}

const AcEvoRouteChildren: AcEvoRouteChildren = {
  AcEvoAnalyseRoute: AcEvoAnalyseRoute,
  AcEvoChatsRoute: AcEvoChatsRoute,
  AcEvoDriverRoute: AcEvoDriverRoute,
  AcEvoExperimentsRoute: AcEvoExperimentsRouteWithChildren,
  AcEvoRawRoute: AcEvoRawRoute,
  AcEvoSessionsRoute: AcEvoSessionsRoute,
  AcEvoSetupsRoute: AcEvoSetupsRouteWithChildren,
  AcEvoIndexRoute: AcEvoIndexRoute,
}

const AcEvoRouteWithChildren = AcEvoRoute._addFileChildren(AcEvoRouteChildren)

interface AccExperimentsRouteChildren {
  AccExperimentsExperimentIdRoute: typeof AccExperimentsExperimentIdRoute
  AccExperimentsIndexRoute: typeof AccExperimentsIndexRoute
  AccExperimentsExperimentIdReviewRoute: typeof AccExperimentsExperimentIdReviewRoute
}

const AccExperimentsRouteChildren: AccExperimentsRouteChildren = {
  AccExperimentsExperimentIdRoute: AccExperimentsExperimentIdRoute,
  AccExperimentsIndexRoute: AccExperimentsIndexRoute,
  AccExperimentsExperimentIdReviewRoute: AccExperimentsExperimentIdReviewRoute,
}

const AccExperimentsRouteWithChildren = AccExperimentsRoute._addFileChildren(
  AccExperimentsRouteChildren,
)

interface AccSetupsRouteChildren {
  AccSetupsImportRoute: typeof AccSetupsImportRoute
  AccSetupsNewRoute: typeof AccSetupsNewRoute
  AccSetupsIndexRoute: typeof AccSetupsIndexRoute
  AccSetupsEditTuneIdRoute: typeof AccSetupsEditTuneIdRoute
}

const AccSetupsRouteChildren: AccSetupsRouteChildren = {
  AccSetupsImportRoute: AccSetupsImportRoute,
  AccSetupsNewRoute: AccSetupsNewRoute,
  AccSetupsIndexRoute: AccSetupsIndexRoute,
  AccSetupsEditTuneIdRoute: AccSetupsEditTuneIdRoute,
}

const AccSetupsRouteWithChildren = AccSetupsRoute._addFileChildren(
  AccSetupsRouteChildren,
)

interface AccRouteChildren {
  AccAnalyseRoute: typeof AccAnalyseRoute
  AccChatsRoute: typeof AccChatsRoute
  AccDriverRoute: typeof AccDriverRoute
  AccExperimentsRoute: typeof AccExperimentsRouteWithChildren
  AccRawRoute: typeof AccRawRoute
  AccSessionsRoute: typeof AccSessionsRoute
  AccSetupsRoute: typeof AccSetupsRouteWithChildren
  AccIndexRoute: typeof AccIndexRoute
}

const AccRouteChildren: AccRouteChildren = {
  AccAnalyseRoute: AccAnalyseRoute,
  AccChatsRoute: AccChatsRoute,
  AccDriverRoute: AccDriverRoute,
  AccExperimentsRoute: AccExperimentsRouteWithChildren,
  AccRawRoute: AccRawRoute,
  AccSessionsRoute: AccSessionsRoute,
  AccSetupsRoute: AccSetupsRouteWithChildren,
  AccIndexRoute: AccIndexRoute,
}

const AccRouteWithChildren = AccRoute._addFileChildren(AccRouteChildren)

interface F125ExperimentsRouteChildren {
  F125ExperimentsExperimentIdRoute: typeof F125ExperimentsExperimentIdRoute
  F125ExperimentsIndexRoute: typeof F125ExperimentsIndexRoute
  F125ExperimentsExperimentIdReviewRoute: typeof F125ExperimentsExperimentIdReviewRoute
}

const F125ExperimentsRouteChildren: F125ExperimentsRouteChildren = {
  F125ExperimentsExperimentIdRoute: F125ExperimentsExperimentIdRoute,
  F125ExperimentsIndexRoute: F125ExperimentsIndexRoute,
  F125ExperimentsExperimentIdReviewRoute:
    F125ExperimentsExperimentIdReviewRoute,
}

const F125ExperimentsRouteWithChildren = F125ExperimentsRoute._addFileChildren(
  F125ExperimentsRouteChildren,
)

interface F125SetupsRouteChildren {
  F125SetupsIndexRoute: typeof F125SetupsIndexRoute
}

const F125SetupsRouteChildren: F125SetupsRouteChildren = {
  F125SetupsIndexRoute: F125SetupsIndexRoute,
}

const F125SetupsRouteWithChildren = F125SetupsRoute._addFileChildren(
  F125SetupsRouteChildren,
)

interface F125TunesRouteChildren {
  F125TunesIndexRoute: typeof F125TunesIndexRoute
}

const F125TunesRouteChildren: F125TunesRouteChildren = {
  F125TunesIndexRoute: F125TunesIndexRoute,
}

const F125TunesRouteWithChildren = F125TunesRoute._addFileChildren(
  F125TunesRouteChildren,
)

interface F125RouteChildren {
  F125AnalyseRoute: typeof F125AnalyseRoute
  F125ChatsRoute: typeof F125ChatsRoute
  F125DriverRoute: typeof F125DriverRoute
  F125ExperimentsRoute: typeof F125ExperimentsRouteWithChildren
  F125RawRoute: typeof F125RawRoute
  F125SessionsRoute: typeof F125SessionsRoute
  F125SetupsRoute: typeof F125SetupsRouteWithChildren
  F125TunesRoute: typeof F125TunesRouteWithChildren
  F125IndexRoute: typeof F125IndexRoute
}

const F125RouteChildren: F125RouteChildren = {
  F125AnalyseRoute: F125AnalyseRoute,
  F125ChatsRoute: F125ChatsRoute,
  F125DriverRoute: F125DriverRoute,
  F125ExperimentsRoute: F125ExperimentsRouteWithChildren,
  F125RawRoute: F125RawRoute,
  F125SessionsRoute: F125SessionsRoute,
  F125SetupsRoute: F125SetupsRouteWithChildren,
  F125TunesRoute: F125TunesRouteWithChildren,
  F125IndexRoute: F125IndexRoute,
}

const F125RouteWithChildren = F125Route._addFileChildren(F125RouteChildren)

interface Fm23LiveRouteChildren {
  Fm23LiveDriverRoute: typeof Fm23LiveDriverRoute
  Fm23LivePitRoute: typeof Fm23LivePitRoute
}

const Fm23LiveRouteChildren: Fm23LiveRouteChildren = {
  Fm23LiveDriverRoute: Fm23LiveDriverRoute,
  Fm23LivePitRoute: Fm23LivePitRoute,
}

const Fm23LiveRouteWithChildren = Fm23LiveRoute._addFileChildren(
  Fm23LiveRouteChildren,
)

interface Fm23SetupsRouteChildren {
  Fm23SetupsCatalogRoute: typeof Fm23SetupsCatalogRoute
  Fm23SetupsNewRoute: typeof Fm23SetupsNewRoute
  Fm23SetupsIndexRoute: typeof Fm23SetupsIndexRoute
  Fm23SetupsEditTuneIdRoute: typeof Fm23SetupsEditTuneIdRoute
  Fm23SetupsWheelProfileIdRoute: typeof Fm23SetupsWheelProfileIdRoute
  Fm23SetupsWheelIndexRoute: typeof Fm23SetupsWheelIndexRoute
}

const Fm23SetupsRouteChildren: Fm23SetupsRouteChildren = {
  Fm23SetupsCatalogRoute: Fm23SetupsCatalogRoute,
  Fm23SetupsNewRoute: Fm23SetupsNewRoute,
  Fm23SetupsIndexRoute: Fm23SetupsIndexRoute,
  Fm23SetupsEditTuneIdRoute: Fm23SetupsEditTuneIdRoute,
  Fm23SetupsWheelProfileIdRoute: Fm23SetupsWheelProfileIdRoute,
  Fm23SetupsWheelIndexRoute: Fm23SetupsWheelIndexRoute,
}

const Fm23SetupsRouteWithChildren = Fm23SetupsRoute._addFileChildren(
  Fm23SetupsRouteChildren,
)

interface Fm23RouteChildren {
  Fm23AnalyseRoute: typeof Fm23AnalyseRoute
  Fm23ChatsRoute: typeof Fm23ChatsRoute
  Fm23DriverRoute: typeof Fm23DriverRoute
  Fm23LiveRoute: typeof Fm23LiveRouteWithChildren
  Fm23RawRoute: typeof Fm23RawRoute
  Fm23SessionsRoute: typeof Fm23SessionsRoute
  Fm23SetupsRoute: typeof Fm23SetupsRouteWithChildren
  Fm23IndexRoute: typeof Fm23IndexRoute
  Fm23CarsCarOrdinalRoute: typeof Fm23CarsCarOrdinalRoute
}

const Fm23RouteChildren: Fm23RouteChildren = {
  Fm23AnalyseRoute: Fm23AnalyseRoute,
  Fm23ChatsRoute: Fm23ChatsRoute,
  Fm23DriverRoute: Fm23DriverRoute,
  Fm23LiveRoute: Fm23LiveRouteWithChildren,
  Fm23RawRoute: Fm23RawRoute,
  Fm23SessionsRoute: Fm23SessionsRoute,
  Fm23SetupsRoute: Fm23SetupsRouteWithChildren,
  Fm23IndexRoute: Fm23IndexRoute,
  Fm23CarsCarOrdinalRoute: Fm23CarsCarOrdinalRoute,
}

const Fm23RouteWithChildren = Fm23Route._addFileChildren(Fm23RouteChildren)

interface IracingLiveRouteChildren {
  IracingLiveDriverRoute: typeof IracingLiveDriverRoute
  IracingLivePitRoute: typeof IracingLivePitRoute
}

const IracingLiveRouteChildren: IracingLiveRouteChildren = {
  IracingLiveDriverRoute: IracingLiveDriverRoute,
  IracingLivePitRoute: IracingLivePitRoute,
}

const IracingLiveRouteWithChildren = IracingLiveRoute._addFileChildren(
  IracingLiveRouteChildren,
)

interface IracingRouteChildren {
  IracingAnalyseRoute: typeof IracingAnalyseRoute
  IracingChatsRoute: typeof IracingChatsRoute
  IracingLiveRoute: typeof IracingLiveRouteWithChildren
  IracingRawRoute: typeof IracingRawRoute
  IracingSessionsRoute: typeof IracingSessionsRoute
  IracingIndexRoute: typeof IracingIndexRoute
}

const IracingRouteChildren: IracingRouteChildren = {
  IracingAnalyseRoute: IracingAnalyseRoute,
  IracingChatsRoute: IracingChatsRoute,
  IracingLiveRoute: IracingLiveRouteWithChildren,
  IracingRawRoute: IracingRawRoute,
  IracingSessionsRoute: IracingSessionsRoute,
  IracingIndexRoute: IracingIndexRoute,
}

const IracingRouteWithChildren =
  IracingRoute._addFileChildren(IracingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameidRoute: GameidRouteWithChildren,
  AcEvoRoute: AcEvoRouteWithChildren,
  AccRoute: AccRouteWithChildren,
  DevRoute: DevRoute,
  F125Route: F125RouteWithChildren,
  Fm23Route: Fm23RouteWithChildren,
  IracingRoute: IracingRouteWithChildren,
  GameLiveRoute: GameLiveRoute,
  DashCombo1Route: DashCombo1Route,
  DashCombo2Route: DashCombo2Route,
  DashIndexRoute: DashIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
