/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Fm23RouteImport } from './routes/fm23'
import { Route as F125RouteImport } from './routes/f125'
import { Route as DevRouteImport } from './routes/dev'
import { Route as AccRouteImport } from './routes/acc'
import { Route as AcEvoRouteImport } from './routes/ac-evo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Fm23IndexRouteImport } from './routes/fm23/index'
import { Route as F125IndexRouteImport } from './routes/f125/index'
import { Route as DashIndexRouteImport } from './routes/dash.index'
import { Route as AccIndexRouteImport } from './routes/acc/index'
import { Route as AcEvoIndexRouteImport } from './routes/ac-evo/index'
import { Route as Fm23TracksRouteImport } from './routes/fm23/tracks'
import { Route as Fm23SetupsRouteImport } from './routes/fm23/setups'
import { Route as Fm23SessionsRouteImport } from './routes/fm23/sessions'
import { Route as Fm23RawRouteImport } from './routes/fm23/raw'
import { Route as Fm23LiveRouteImport } from './routes/fm23/live'
import { Route as Fm23CompareRouteImport } from './routes/fm23/compare'
import { Route as Fm23ChatsRouteImport } from './routes/fm23/chats'
import { Route as Fm23CarsRouteImport } from './routes/fm23/cars'
import { Route as Fm23AnalyseRouteImport } from './routes/fm23/analyse'
import { Route as F125TunesRouteImport } from './routes/f125/tunes'
import { Route as F125TracksRouteImport } from './routes/f125/tracks'
import { Route as F125SetupsRouteImport } from './routes/f125/setups'
import { Route as F125SessionsRouteImport } from './routes/f125/sessions'
import { Route as F125RawRouteImport } from './routes/f125/raw'
import { Route as F125LiveRouteImport } from './routes/f125/live'
import { Route as F125CompareRouteImport } from './routes/f125/compare'
import { Route as F125ChatsRouteImport } from './routes/f125/chats'
import { Route as F125CarsRouteImport } from './routes/f125/cars'
import { Route as F125AnalyseRouteImport } from './routes/f125/analyse'
import { Route as DashCombo2RouteImport } from './routes/dash.combo-2'
import { Route as DashCombo1RouteImport } from './routes/dash.combo-1'
import { Route as AccTracksRouteImport } from './routes/acc/tracks'
import { Route as AccSetupsRouteImport } from './routes/acc/setups'
import { Route as AccSessionsRouteImport } from './routes/acc/sessions'
import { Route as AccRawRouteImport } from './routes/acc/raw'
import { Route as AccLiveRouteImport } from './routes/acc/live'
import { Route as AccCompareRouteImport } from './routes/acc/compare'
import { Route as AccChatsRouteImport } from './routes/acc/chats'
import { Route as AccCarsRouteImport } from './routes/acc/cars'
import { Route as AccAnalyseRouteImport } from './routes/acc/analyse'
import { Route as AcEvoTracksRouteImport } from './routes/ac-evo/tracks'
import { Route as AcEvoSetupsRouteImport } from './routes/ac-evo/setups'
import { Route as AcEvoSessionsRouteImport } from './routes/ac-evo/sessions'
import { Route as AcEvoRawRouteImport } from './routes/ac-evo/raw'
import { Route as AcEvoLiveRouteImport } from './routes/ac-evo/live'
import { Route as AcEvoCompareRouteImport } from './routes/ac-evo/compare'
import { Route as AcEvoChatsRouteImport } from './routes/ac-evo/chats'
import { Route as AcEvoCarsRouteImport } from './routes/ac-evo/cars'
import { Route as AcEvoAnalyseRouteImport } from './routes/ac-evo/analyse'
import { Route as Fm23SetupsIndexRouteImport } from './routes/fm23/setups/index'
import { Route as F125TunesIndexRouteImport } from './routes/f125/tunes/index'
import { Route as F125SetupsIndexRouteImport } from './routes/f125/setups/index'
import { Route as AccSetupsIndexRouteImport } from './routes/acc/setups/index'
import { Route as AcEvoSetupsIndexRouteImport } from './routes/ac-evo/setups/index'
import { Route as Fm23SetupsNewRouteImport } from './routes/fm23/setups/new'
import { Route as Fm23SetupsCatalogRouteImport } from './routes/fm23/setups/catalog'
import { Route as Fm23LivePitRouteImport } from './routes/fm23/live/pit'
import { Route as Fm23LiveDriverRouteImport } from './routes/fm23/live/driver'
import { Route as Fm23CarsCarOrdinalRouteImport } from './routes/fm23/cars_.$carOrdinal'
import { Route as AccSetupsNewRouteImport } from './routes/acc/setups/new'
import { Route as AccSetupsImportRouteImport } from './routes/acc/setups/import'
import { Route as AcEvoSetupsNewRouteImport } from './routes/ac-evo/setups/new'
import { Route as AcEvoSetupsImportRouteImport } from './routes/ac-evo/setups/import'
import { Route as Fm23SetupsWheelIndexRouteImport } from './routes/fm23/setups/wheel/index'
import { Route as Fm23SetupsWheelProfileIdRouteImport } from './routes/fm23/setups/wheel/$profileId'
import { Route as Fm23SetupsEditTuneIdRouteImport } from './routes/fm23/setups/edit.$tuneId'
import { Route as AccSetupsEditTuneIdRouteImport } from './routes/acc/setups/edit.$tuneId'
import { Route as AcEvoSetupsEditTuneIdRouteImport } from './routes/ac-evo/setups/edit.$tuneId'

const Fm23Route = Fm23RouteImport.update({
  id: '/fm23',
  path: '/fm23',
  getParentRoute: () => rootRouteImport,
} as any)
const F125Route = F125RouteImport.update({
  id: '/f125',
  path: '/f125',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AccRoute = AccRouteImport.update({
  id: '/acc',
  path: '/acc',
  getParentRoute: () => rootRouteImport,
} as any)
const AcEvoRoute = AcEvoRouteImport.update({
  id: '/ac-evo',
  path: '/ac-evo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Fm23IndexRoute = Fm23IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Fm23Route,
} as any)
const F125IndexRoute = F125IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => F125Route,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/dash/',
  path: '/dash/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccIndexRoute = AccIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccRoute,
} as any)
const AcEvoIndexRoute = AcEvoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcEvoRoute,
} as any)
const Fm23TracksRoute = Fm23TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23SetupsRoute = Fm23SetupsRouteImport.update({
  id: '/setups',
  path: '/setups',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23SessionsRoute = Fm23SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23RawRoute = Fm23RawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23LiveRoute = Fm23LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23CompareRoute = Fm23CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23ChatsRoute = Fm23ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23CarsRoute = Fm23CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23AnalyseRoute = Fm23AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => Fm23Route,
} as any)
const F125TunesRoute = F125TunesRouteImport.update({
  id: '/tunes',
  path: '/tunes',
  getParentRoute: () => F125Route,
} as any)
const F125TracksRoute = F125TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => F125Route,
} as any)
const F125SetupsRoute = F125SetupsRouteImport.update({
  id: '/setups',
  path: '/setups',
  getParentRoute: () => F125Route,
} as any)
const F125SessionsRoute = F125SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => F125Route,
} as any)
const F125RawRoute = F125RawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => F125Route,
} as any)
const F125LiveRoute = F125LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => F125Route,
} as any)
const F125CompareRoute = F125CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => F125Route,
} as any)
const F125ChatsRoute = F125ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => F125Route,
} as any)
const F125CarsRoute = F125CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => F125Route,
} as any)
const F125AnalyseRoute = F125AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => F125Route,
} as any)
const DashCombo2Route = DashCombo2RouteImport.update({
  id: '/dash/combo-2',
  path: '/dash/combo-2',
  getParentRoute: () => rootRouteImport,
} as any)
const DashCombo1Route = DashCombo1RouteImport.update({
  id: '/dash/combo-1',
  path: '/dash/combo-1',
  getParentRoute: () => rootRouteImport,
} as any)
const AccTracksRoute = AccTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AccRoute,
} as any)
const AccSetupsRoute = AccSetupsRouteImport.update({
  id: '/setups',
  path: '/setups',
  getParentRoute: () => AccRoute,
} as any)
const AccSessionsRoute = AccSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AccRoute,
} as any)
const AccRawRoute = AccRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => AccRoute,
} as any)
const AccLiveRoute = AccLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AccRoute,
} as any)
const AccCompareRoute = AccCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AccRoute,
} as any)
const AccChatsRoute = AccChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AccRoute,
} as any)
const AccCarsRoute = AccCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AccRoute,
} as any)
const AccAnalyseRoute = AccAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => AccRoute,
} as any)
const AcEvoTracksRoute = AcEvoTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoSetupsRoute = AcEvoSetupsRouteImport.update({
  id: '/setups',
  path: '/setups',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoSessionsRoute = AcEvoSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoRawRoute = AcEvoRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoLiveRoute = AcEvoLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoCompareRoute = AcEvoCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoChatsRoute = AcEvoChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoCarsRoute = AcEvoCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoAnalyseRoute = AcEvoAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => AcEvoRoute,
} as any)
const Fm23SetupsIndexRoute = Fm23SetupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Fm23SetupsRoute,
} as any)
const F125TunesIndexRoute = F125TunesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => F125TunesRoute,
} as any)
const F125SetupsIndexRoute = F125SetupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => F125SetupsRoute,
} as any)
const AccSetupsIndexRoute = AccSetupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccSetupsRoute,
} as any)
const AcEvoSetupsIndexRoute = AcEvoSetupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcEvoSetupsRoute,
} as any)
const Fm23SetupsNewRoute = Fm23SetupsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => Fm23SetupsRoute,
} as any)
const Fm23SetupsCatalogRoute = Fm23SetupsCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => Fm23SetupsRoute,
} as any)
const Fm23LivePitRoute = Fm23LivePitRouteImport.update({
  id: '/pit',
  path: '/pit',
  getParentRoute: () => Fm23LiveRoute,
} as any)
const Fm23LiveDriverRoute = Fm23LiveDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => Fm23LiveRoute,
} as any)
const Fm23CarsCarOrdinalRoute = Fm23CarsCarOrdinalRouteImport.update({
  id: '/cars_/$carOrdinal',
  path: '/cars/$carOrdinal',
  getParentRoute: () => Fm23Route,
} as any)
const AccSetupsNewRoute = AccSetupsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AccSetupsRoute,
} as any)
const AccSetupsImportRoute = AccSetupsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AccSetupsRoute,
} as any)
const AcEvoSetupsNewRoute = AcEvoSetupsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AcEvoSetupsRoute,
} as any)
const AcEvoSetupsImportRoute = AcEvoSetupsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AcEvoSetupsRoute,
} as any)
const Fm23SetupsWheelIndexRoute = Fm23SetupsWheelIndexRouteImport.update({
  id: '/wheel/',
  path: '/wheel/',
  getParentRoute: () => Fm23SetupsRoute,
} as any)
const Fm23SetupsWheelProfileIdRoute =
  Fm23SetupsWheelProfileIdRouteImport.update({
    id: '/wheel/$profileId',
    path: '/wheel/$profileId',
    getParentRoute: () => Fm23SetupsRoute,
  } as any)
const Fm23SetupsEditTuneIdRoute = Fm23SetupsEditTuneIdRouteImport.update({
  id: '/edit/$tuneId',
  path: '/edit/$tuneId',
  getParentRoute: () => Fm23SetupsRoute,
} as any)
const AccSetupsEditTuneIdRoute = AccSetupsEditTuneIdRouteImport.update({
  id: '/edit/$tuneId',
  path: '/edit/$tuneId',
  getParentRoute: () => AccSetupsRoute,
} as any)
const AcEvoSetupsEditTuneIdRoute = AcEvoSetupsEditTuneIdRouteImport.update({
  id: '/edit/$tuneId',
  path: '/edit/$tuneId',
  getParentRoute: () => AcEvoSetupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ac-evo': typeof AcEvoRouteWithChildren
  '/acc': typeof AccRouteWithChildren
  '/dev': typeof DevRoute
  '/f125': typeof F125RouteWithChildren
  '/fm23': typeof Fm23RouteWithChildren
  '/ac-evo/analyse': typeof AcEvoAnalyseRoute
  '/ac-evo/cars': typeof AcEvoCarsRoute
  '/ac-evo/chats': typeof AcEvoChatsRoute
  '/ac-evo/compare': typeof AcEvoCompareRoute
  '/ac-evo/live': typeof AcEvoLiveRoute
  '/ac-evo/raw': typeof AcEvoRawRoute
  '/ac-evo/sessions': typeof AcEvoSessionsRoute
  '/ac-evo/setups': typeof AcEvoSetupsRouteWithChildren
  '/ac-evo/tracks': typeof AcEvoTracksRoute
  '/acc/analyse': typeof AccAnalyseRoute
  '/acc/cars': typeof AccCarsRoute
  '/acc/chats': typeof AccChatsRoute
  '/acc/compare': typeof AccCompareRoute
  '/acc/live': typeof AccLiveRoute
  '/acc/raw': typeof AccRawRoute
  '/acc/sessions': typeof AccSessionsRoute
  '/acc/setups': typeof AccSetupsRouteWithChildren
  '/acc/tracks': typeof AccTracksRoute
  '/dash/combo-1': typeof DashCombo1Route
  '/dash/combo-2': typeof DashCombo2Route
  '/f125/analyse': typeof F125AnalyseRoute
  '/f125/cars': typeof F125CarsRoute
  '/f125/chats': typeof F125ChatsRoute
  '/f125/compare': typeof F125CompareRoute
  '/f125/live': typeof F125LiveRoute
  '/f125/raw': typeof F125RawRoute
  '/f125/sessions': typeof F125SessionsRoute
  '/f125/setups': typeof F125SetupsRouteWithChildren
  '/f125/tracks': typeof F125TracksRoute
  '/f125/tunes': typeof F125TunesRouteWithChildren
  '/fm23/analyse': typeof Fm23AnalyseRoute
  '/fm23/cars': typeof Fm23CarsRoute
  '/fm23/chats': typeof Fm23ChatsRoute
  '/fm23/compare': typeof Fm23CompareRoute
  '/fm23/live': typeof Fm23LiveRouteWithChildren
  '/fm23/raw': typeof Fm23RawRoute
  '/fm23/sessions': typeof Fm23SessionsRoute
  '/fm23/setups': typeof Fm23SetupsRouteWithChildren
  '/fm23/tracks': typeof Fm23TracksRoute
  '/ac-evo/': typeof AcEvoIndexRoute
  '/acc/': typeof AccIndexRoute
  '/dash/': typeof DashIndexRoute
  '/f125/': typeof F125IndexRoute
  '/fm23/': typeof Fm23IndexRoute
  '/ac-evo/setups/import': typeof AcEvoSetupsImportRoute
  '/ac-evo/setups/new': typeof AcEvoSetupsNewRoute
  '/acc/setups/import': typeof AccSetupsImportRoute
  '/acc/setups/new': typeof AccSetupsNewRoute
  '/fm23/cars/$carOrdinal': typeof Fm23CarsCarOrdinalRoute
  '/fm23/live/driver': typeof Fm23LiveDriverRoute
  '/fm23/live/pit': typeof Fm23LivePitRoute
  '/fm23/setups/catalog': typeof Fm23SetupsCatalogRoute
  '/fm23/setups/new': typeof Fm23SetupsNewRoute
  '/ac-evo/setups/': typeof AcEvoSetupsIndexRoute
  '/acc/setups/': typeof AccSetupsIndexRoute
  '/f125/setups/': typeof F125SetupsIndexRoute
  '/f125/tunes/': typeof F125TunesIndexRoute
  '/fm23/setups/': typeof Fm23SetupsIndexRoute
  '/ac-evo/setups/edit/$tuneId': typeof AcEvoSetupsEditTuneIdRoute
  '/acc/setups/edit/$tuneId': typeof AccSetupsEditTuneIdRoute
  '/fm23/setups/edit/$tuneId': typeof Fm23SetupsEditTuneIdRoute
  '/fm23/setups/wheel/$profileId': typeof Fm23SetupsWheelProfileIdRoute
  '/fm23/setups/wheel/': typeof Fm23SetupsWheelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/ac-evo/analyse': typeof AcEvoAnalyseRoute
  '/ac-evo/cars': typeof AcEvoCarsRoute
  '/ac-evo/chats': typeof AcEvoChatsRoute
  '/ac-evo/compare': typeof AcEvoCompareRoute
  '/ac-evo/live': typeof AcEvoLiveRoute
  '/ac-evo/raw': typeof AcEvoRawRoute
  '/ac-evo/sessions': typeof AcEvoSessionsRoute
  '/ac-evo/tracks': typeof AcEvoTracksRoute
  '/acc/analyse': typeof AccAnalyseRoute
  '/acc/cars': typeof AccCarsRoute
  '/acc/chats': typeof AccChatsRoute
  '/acc/compare': typeof AccCompareRoute
  '/acc/live': typeof AccLiveRoute
  '/acc/raw': typeof AccRawRoute
  '/acc/sessions': typeof AccSessionsRoute
  '/acc/tracks': typeof AccTracksRoute
  '/dash/combo-1': typeof DashCombo1Route
  '/dash/combo-2': typeof DashCombo2Route
  '/f125/analyse': typeof F125AnalyseRoute
  '/f125/cars': typeof F125CarsRoute
  '/f125/chats': typeof F125ChatsRoute
  '/f125/compare': typeof F125CompareRoute
  '/f125/live': typeof F125LiveRoute
  '/f125/raw': typeof F125RawRoute
  '/f125/sessions': typeof F125SessionsRoute
  '/f125/tracks': typeof F125TracksRoute
  '/fm23/analyse': typeof Fm23AnalyseRoute
  '/fm23/cars': typeof Fm23CarsRoute
  '/fm23/chats': typeof Fm23ChatsRoute
  '/fm23/compare': typeof Fm23CompareRoute
  '/fm23/live': typeof Fm23LiveRouteWithChildren
  '/fm23/raw': typeof Fm23RawRoute
  '/fm23/sessions': typeof Fm23SessionsRoute
  '/fm23/tracks': typeof Fm23TracksRoute
  '/ac-evo': typeof AcEvoIndexRoute
  '/acc': typeof AccIndexRoute
  '/dash': typeof DashIndexRoute
  '/f125': typeof F125IndexRoute
  '/fm23': typeof Fm23IndexRoute
  '/ac-evo/setups/import': typeof AcEvoSetupsImportRoute
  '/ac-evo/setups/new': typeof AcEvoSetupsNewRoute
  '/acc/setups/import': typeof AccSetupsImportRoute
  '/acc/setups/new': typeof AccSetupsNewRoute
  '/fm23/cars/$carOrdinal': typeof Fm23CarsCarOrdinalRoute
  '/fm23/live/driver': typeof Fm23LiveDriverRoute
  '/fm23/live/pit': typeof Fm23LivePitRoute
  '/fm23/setups/catalog': typeof Fm23SetupsCatalogRoute
  '/fm23/setups/new': typeof Fm23SetupsNewRoute
  '/ac-evo/setups': typeof AcEvoSetupsIndexRoute
  '/acc/setups': typeof AccSetupsIndexRoute
  '/f125/setups': typeof F125SetupsIndexRoute
  '/f125/tunes': typeof F125TunesIndexRoute
  '/fm23/setups': typeof Fm23SetupsIndexRoute
  '/ac-evo/setups/edit/$tuneId': typeof AcEvoSetupsEditTuneIdRoute
  '/acc/setups/edit/$tuneId': typeof AccSetupsEditTuneIdRoute
  '/fm23/setups/edit/$tuneId': typeof Fm23SetupsEditTuneIdRoute
  '/fm23/setups/wheel/$profileId': typeof Fm23SetupsWheelProfileIdRoute
  '/fm23/setups/wheel': typeof Fm23SetupsWheelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ac-evo': typeof AcEvoRouteWithChildren
  '/acc': typeof AccRouteWithChildren
  '/dev': typeof DevRoute
  '/f125': typeof F125RouteWithChildren
  '/fm23': typeof Fm23RouteWithChildren
  '/ac-evo/analyse': typeof AcEvoAnalyseRoute
  '/ac-evo/cars': typeof AcEvoCarsRoute
  '/ac-evo/chats': typeof AcEvoChatsRoute
  '/ac-evo/compare': typeof AcEvoCompareRoute
  '/ac-evo/live': typeof AcEvoLiveRoute
  '/ac-evo/raw': typeof AcEvoRawRoute
  '/ac-evo/sessions': typeof AcEvoSessionsRoute
  '/ac-evo/setups': typeof AcEvoSetupsRouteWithChildren
  '/ac-evo/tracks': typeof AcEvoTracksRoute
  '/acc/analyse': typeof AccAnalyseRoute
  '/acc/cars': typeof AccCarsRoute
  '/acc/chats': typeof AccChatsRoute
  '/acc/compare': typeof AccCompareRoute
  '/acc/live': typeof AccLiveRoute
  '/acc/raw': typeof AccRawRoute
  '/acc/sessions': typeof AccSessionsRoute
  '/acc/setups': typeof AccSetupsRouteWithChildren
  '/acc/tracks': typeof AccTracksRoute
  '/dash/combo-1': typeof DashCombo1Route
  '/dash/combo-2': typeof DashCombo2Route
  '/f125/analyse': typeof F125AnalyseRoute
  '/f125/cars': typeof F125CarsRoute
  '/f125/chats': typeof F125ChatsRoute
  '/f125/compare': typeof F125CompareRoute
  '/f125/live': typeof F125LiveRoute
  '/f125/raw': typeof F125RawRoute
  '/f125/sessions': typeof F125SessionsRoute
  '/f125/setups': typeof F125SetupsRouteWithChildren
  '/f125/tracks': typeof F125TracksRoute
  '/f125/tunes': typeof F125TunesRouteWithChildren
  '/fm23/analyse': typeof Fm23AnalyseRoute
  '/fm23/cars': typeof Fm23CarsRoute
  '/fm23/chats': typeof Fm23ChatsRoute
  '/fm23/compare': typeof Fm23CompareRoute
  '/fm23/live': typeof Fm23LiveRouteWithChildren
  '/fm23/raw': typeof Fm23RawRoute
  '/fm23/sessions': typeof Fm23SessionsRoute
  '/fm23/setups': typeof Fm23SetupsRouteWithChildren
  '/fm23/tracks': typeof Fm23TracksRoute
  '/ac-evo/': typeof AcEvoIndexRoute
  '/acc/': typeof AccIndexRoute
  '/dash/': typeof DashIndexRoute
  '/f125/': typeof F125IndexRoute
  '/fm23/': typeof Fm23IndexRoute
  '/ac-evo/setups/import': typeof AcEvoSetupsImportRoute
  '/ac-evo/setups/new': typeof AcEvoSetupsNewRoute
  '/acc/setups/import': typeof AccSetupsImportRoute
  '/acc/setups/new': typeof AccSetupsNewRoute
  '/fm23/cars_/$carOrdinal': typeof Fm23CarsCarOrdinalRoute
  '/fm23/live/driver': typeof Fm23LiveDriverRoute
  '/fm23/live/pit': typeof Fm23LivePitRoute
  '/fm23/setups/catalog': typeof Fm23SetupsCatalogRoute
  '/fm23/setups/new': typeof Fm23SetupsNewRoute
  '/ac-evo/setups/': typeof AcEvoSetupsIndexRoute
  '/acc/setups/': typeof AccSetupsIndexRoute
  '/f125/setups/': typeof F125SetupsIndexRoute
  '/f125/tunes/': typeof F125TunesIndexRoute
  '/fm23/setups/': typeof Fm23SetupsIndexRoute
  '/ac-evo/setups/edit/$tuneId': typeof AcEvoSetupsEditTuneIdRoute
  '/acc/setups/edit/$tuneId': typeof AccSetupsEditTuneIdRoute
  '/fm23/setups/edit/$tuneId': typeof Fm23SetupsEditTuneIdRoute
  '/fm23/setups/wheel/$profileId': typeof Fm23SetupsWheelProfileIdRoute
  '/fm23/setups/wheel/': typeof Fm23SetupsWheelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ac-evo'
    | '/acc'
    | '/dev'
    | '/f125'
    | '/fm23'
    | '/ac-evo/analyse'
    | '/ac-evo/cars'
    | '/ac-evo/chats'
    | '/ac-evo/compare'
    | '/ac-evo/live'
    | '/ac-evo/raw'
    | '/ac-evo/sessions'
    | '/ac-evo/setups'
    | '/ac-evo/tracks'
    | '/acc/analyse'
    | '/acc/cars'
    | '/acc/chats'
    | '/acc/compare'
    | '/acc/live'
    | '/acc/raw'
    | '/acc/sessions'
    | '/acc/setups'
    | '/acc/tracks'
    | '/dash/combo-1'
    | '/dash/combo-2'
    | '/f125/analyse'
    | '/f125/cars'
    | '/f125/chats'
    | '/f125/compare'
    | '/f125/live'
    | '/f125/raw'
    | '/f125/sessions'
    | '/f125/setups'
    | '/f125/tracks'
    | '/f125/tunes'
    | '/fm23/analyse'
    | '/fm23/cars'
    | '/fm23/chats'
    | '/fm23/compare'
    | '/fm23/live'
    | '/fm23/raw'
    | '/fm23/sessions'
    | '/fm23/setups'
    | '/fm23/tracks'
    | '/ac-evo/'
    | '/acc/'
    | '/dash/'
    | '/f125/'
    | '/fm23/'
    | '/ac-evo/setups/import'
    | '/ac-evo/setups/new'
    | '/acc/setups/import'
    | '/acc/setups/new'
    | '/fm23/cars/$carOrdinal'
    | '/fm23/live/driver'
    | '/fm23/live/pit'
    | '/fm23/setups/catalog'
    | '/fm23/setups/new'
    | '/ac-evo/setups/'
    | '/acc/setups/'
    | '/f125/setups/'
    | '/f125/tunes/'
    | '/fm23/setups/'
    | '/ac-evo/setups/edit/$tuneId'
    | '/acc/setups/edit/$tuneId'
    | '/fm23/setups/edit/$tuneId'
    | '/fm23/setups/wheel/$profileId'
    | '/fm23/setups/wheel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev'
    | '/ac-evo/analyse'
    | '/ac-evo/cars'
    | '/ac-evo/chats'
    | '/ac-evo/compare'
    | '/ac-evo/live'
    | '/ac-evo/raw'
    | '/ac-evo/sessions'
    | '/ac-evo/tracks'
    | '/acc/analyse'
    | '/acc/cars'
    | '/acc/chats'
    | '/acc/compare'
    | '/acc/live'
    | '/acc/raw'
    | '/acc/sessions'
    | '/acc/tracks'
    | '/dash/combo-1'
    | '/dash/combo-2'
    | '/f125/analyse'
    | '/f125/cars'
    | '/f125/chats'
    | '/f125/compare'
    | '/f125/live'
    | '/f125/raw'
    | '/f125/sessions'
    | '/f125/tracks'
    | '/fm23/analyse'
    | '/fm23/cars'
    | '/fm23/chats'
    | '/fm23/compare'
    | '/fm23/live'
    | '/fm23/raw'
    | '/fm23/sessions'
    | '/fm23/tracks'
    | '/ac-evo'
    | '/acc'
    | '/dash'
    | '/f125'
    | '/fm23'
    | '/ac-evo/setups/import'
    | '/ac-evo/setups/new'
    | '/acc/setups/import'
    | '/acc/setups/new'
    | '/fm23/cars/$carOrdinal'
    | '/fm23/live/driver'
    | '/fm23/live/pit'
    | '/fm23/setups/catalog'
    | '/fm23/setups/new'
    | '/ac-evo/setups'
    | '/acc/setups'
    | '/f125/setups'
    | '/f125/tunes'
    | '/fm23/setups'
    | '/ac-evo/setups/edit/$tuneId'
    | '/acc/setups/edit/$tuneId'
    | '/fm23/setups/edit/$tuneId'
    | '/fm23/setups/wheel/$profileId'
    | '/fm23/setups/wheel'
  id:
    | '__root__'
    | '/'
    | '/ac-evo'
    | '/acc'
    | '/dev'
    | '/f125'
    | '/fm23'
    | '/ac-evo/analyse'
    | '/ac-evo/cars'
    | '/ac-evo/chats'
    | '/ac-evo/compare'
    | '/ac-evo/live'
    | '/ac-evo/raw'
    | '/ac-evo/sessions'
    | '/ac-evo/setups'
    | '/ac-evo/tracks'
    | '/acc/analyse'
    | '/acc/cars'
    | '/acc/chats'
    | '/acc/compare'
    | '/acc/live'
    | '/acc/raw'
    | '/acc/sessions'
    | '/acc/setups'
    | '/acc/tracks'
    | '/dash/combo-1'
    | '/dash/combo-2'
    | '/f125/analyse'
    | '/f125/cars'
    | '/f125/chats'
    | '/f125/compare'
    | '/f125/live'
    | '/f125/raw'
    | '/f125/sessions'
    | '/f125/setups'
    | '/f125/tracks'
    | '/f125/tunes'
    | '/fm23/analyse'
    | '/fm23/cars'
    | '/fm23/chats'
    | '/fm23/compare'
    | '/fm23/live'
    | '/fm23/raw'
    | '/fm23/sessions'
    | '/fm23/setups'
    | '/fm23/tracks'
    | '/ac-evo/'
    | '/acc/'
    | '/dash/'
    | '/f125/'
    | '/fm23/'
    | '/ac-evo/setups/import'
    | '/ac-evo/setups/new'
    | '/acc/setups/import'
    | '/acc/setups/new'
    | '/fm23/cars_/$carOrdinal'
    | '/fm23/live/driver'
    | '/fm23/live/pit'
    | '/fm23/setups/catalog'
    | '/fm23/setups/new'
    | '/ac-evo/setups/'
    | '/acc/setups/'
    | '/f125/setups/'
    | '/f125/tunes/'
    | '/fm23/setups/'
    | '/ac-evo/setups/edit/$tuneId'
    | '/acc/setups/edit/$tuneId'
    | '/fm23/setups/edit/$tuneId'
    | '/fm23/setups/wheel/$profileId'
    | '/fm23/setups/wheel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcEvoRoute: typeof AcEvoRouteWithChildren
  AccRoute: typeof AccRouteWithChildren
  DevRoute: typeof DevRoute
  F125Route: typeof F125RouteWithChildren
  Fm23Route: typeof Fm23RouteWithChildren
  DashCombo1Route: typeof DashCombo1Route
  DashCombo2Route: typeof DashCombo2Route
  DashIndexRoute: typeof DashIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fm23': {
      id: '/fm23'
      path: '/fm23'
      fullPath: '/fm23'
      preLoaderRoute: typeof Fm23RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f125': {
      id: '/f125'
      path: '/f125'
      fullPath: '/f125'
      preLoaderRoute: typeof F125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acc': {
      id: '/acc'
      path: '/acc'
      fullPath: '/acc'
      preLoaderRoute: typeof AccRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ac-evo': {
      id: '/ac-evo'
      path: '/ac-evo'
      fullPath: '/ac-evo'
      preLoaderRoute: typeof AcEvoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fm23/': {
      id: '/fm23/'
      path: '/'
      fullPath: '/fm23/'
      preLoaderRoute: typeof Fm23IndexRouteImport
      parentRoute: typeof Fm23Route
    }
    '/f125/': {
      id: '/f125/'
      path: '/'
      fullPath: '/f125/'
      preLoaderRoute: typeof F125IndexRouteImport
      parentRoute: typeof F125Route
    }
    '/dash/': {
      id: '/dash/'
      path: '/dash'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acc/': {
      id: '/acc/'
      path: '/'
      fullPath: '/acc/'
      preLoaderRoute: typeof AccIndexRouteImport
      parentRoute: typeof AccRoute
    }
    '/ac-evo/': {
      id: '/ac-evo/'
      path: '/'
      fullPath: '/ac-evo/'
      preLoaderRoute: typeof AcEvoIndexRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/fm23/tracks': {
      id: '/fm23/tracks'
      path: '/tracks'
      fullPath: '/fm23/tracks'
      preLoaderRoute: typeof Fm23TracksRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/setups': {
      id: '/fm23/setups'
      path: '/setups'
      fullPath: '/fm23/setups'
      preLoaderRoute: typeof Fm23SetupsRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/sessions': {
      id: '/fm23/sessions'
      path: '/sessions'
      fullPath: '/fm23/sessions'
      preLoaderRoute: typeof Fm23SessionsRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/raw': {
      id: '/fm23/raw'
      path: '/raw'
      fullPath: '/fm23/raw'
      preLoaderRoute: typeof Fm23RawRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/live': {
      id: '/fm23/live'
      path: '/live'
      fullPath: '/fm23/live'
      preLoaderRoute: typeof Fm23LiveRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/compare': {
      id: '/fm23/compare'
      path: '/compare'
      fullPath: '/fm23/compare'
      preLoaderRoute: typeof Fm23CompareRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/chats': {
      id: '/fm23/chats'
      path: '/chats'
      fullPath: '/fm23/chats'
      preLoaderRoute: typeof Fm23ChatsRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/cars': {
      id: '/fm23/cars'
      path: '/cars'
      fullPath: '/fm23/cars'
      preLoaderRoute: typeof Fm23CarsRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/analyse': {
      id: '/fm23/analyse'
      path: '/analyse'
      fullPath: '/fm23/analyse'
      preLoaderRoute: typeof Fm23AnalyseRouteImport
      parentRoute: typeof Fm23Route
    }
    '/f125/tunes': {
      id: '/f125/tunes'
      path: '/tunes'
      fullPath: '/f125/tunes'
      preLoaderRoute: typeof F125TunesRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/tracks': {
      id: '/f125/tracks'
      path: '/tracks'
      fullPath: '/f125/tracks'
      preLoaderRoute: typeof F125TracksRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/setups': {
      id: '/f125/setups'
      path: '/setups'
      fullPath: '/f125/setups'
      preLoaderRoute: typeof F125SetupsRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/sessions': {
      id: '/f125/sessions'
      path: '/sessions'
      fullPath: '/f125/sessions'
      preLoaderRoute: typeof F125SessionsRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/raw': {
      id: '/f125/raw'
      path: '/raw'
      fullPath: '/f125/raw'
      preLoaderRoute: typeof F125RawRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/live': {
      id: '/f125/live'
      path: '/live'
      fullPath: '/f125/live'
      preLoaderRoute: typeof F125LiveRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/compare': {
      id: '/f125/compare'
      path: '/compare'
      fullPath: '/f125/compare'
      preLoaderRoute: typeof F125CompareRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/chats': {
      id: '/f125/chats'
      path: '/chats'
      fullPath: '/f125/chats'
      preLoaderRoute: typeof F125ChatsRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/cars': {
      id: '/f125/cars'
      path: '/cars'
      fullPath: '/f125/cars'
      preLoaderRoute: typeof F125CarsRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/analyse': {
      id: '/f125/analyse'
      path: '/analyse'
      fullPath: '/f125/analyse'
      preLoaderRoute: typeof F125AnalyseRouteImport
      parentRoute: typeof F125Route
    }
    '/dash/combo-2': {
      id: '/dash/combo-2'
      path: '/dash/combo-2'
      fullPath: '/dash/combo-2'
      preLoaderRoute: typeof DashCombo2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/combo-1': {
      id: '/dash/combo-1'
      path: '/dash/combo-1'
      fullPath: '/dash/combo-1'
      preLoaderRoute: typeof DashCombo1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acc/tracks': {
      id: '/acc/tracks'
      path: '/tracks'
      fullPath: '/acc/tracks'
      preLoaderRoute: typeof AccTracksRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/setups': {
      id: '/acc/setups'
      path: '/setups'
      fullPath: '/acc/setups'
      preLoaderRoute: typeof AccSetupsRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/sessions': {
      id: '/acc/sessions'
      path: '/sessions'
      fullPath: '/acc/sessions'
      preLoaderRoute: typeof AccSessionsRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/raw': {
      id: '/acc/raw'
      path: '/raw'
      fullPath: '/acc/raw'
      preLoaderRoute: typeof AccRawRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/live': {
      id: '/acc/live'
      path: '/live'
      fullPath: '/acc/live'
      preLoaderRoute: typeof AccLiveRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/compare': {
      id: '/acc/compare'
      path: '/compare'
      fullPath: '/acc/compare'
      preLoaderRoute: typeof AccCompareRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/chats': {
      id: '/acc/chats'
      path: '/chats'
      fullPath: '/acc/chats'
      preLoaderRoute: typeof AccChatsRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/cars': {
      id: '/acc/cars'
      path: '/cars'
      fullPath: '/acc/cars'
      preLoaderRoute: typeof AccCarsRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/analyse': {
      id: '/acc/analyse'
      path: '/analyse'
      fullPath: '/acc/analyse'
      preLoaderRoute: typeof AccAnalyseRouteImport
      parentRoute: typeof AccRoute
    }
    '/ac-evo/tracks': {
      id: '/ac-evo/tracks'
      path: '/tracks'
      fullPath: '/ac-evo/tracks'
      preLoaderRoute: typeof AcEvoTracksRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/setups': {
      id: '/ac-evo/setups'
      path: '/setups'
      fullPath: '/ac-evo/setups'
      preLoaderRoute: typeof AcEvoSetupsRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/sessions': {
      id: '/ac-evo/sessions'
      path: '/sessions'
      fullPath: '/ac-evo/sessions'
      preLoaderRoute: typeof AcEvoSessionsRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/raw': {
      id: '/ac-evo/raw'
      path: '/raw'
      fullPath: '/ac-evo/raw'
      preLoaderRoute: typeof AcEvoRawRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/live': {
      id: '/ac-evo/live'
      path: '/live'
      fullPath: '/ac-evo/live'
      preLoaderRoute: typeof AcEvoLiveRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/compare': {
      id: '/ac-evo/compare'
      path: '/compare'
      fullPath: '/ac-evo/compare'
      preLoaderRoute: typeof AcEvoCompareRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/chats': {
      id: '/ac-evo/chats'
      path: '/chats'
      fullPath: '/ac-evo/chats'
      preLoaderRoute: typeof AcEvoChatsRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/cars': {
      id: '/ac-evo/cars'
      path: '/cars'
      fullPath: '/ac-evo/cars'
      preLoaderRoute: typeof AcEvoCarsRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/analyse': {
      id: '/ac-evo/analyse'
      path: '/analyse'
      fullPath: '/ac-evo/analyse'
      preLoaderRoute: typeof AcEvoAnalyseRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/fm23/setups/': {
      id: '/fm23/setups/'
      path: '/'
      fullPath: '/fm23/setups/'
      preLoaderRoute: typeof Fm23SetupsIndexRouteImport
      parentRoute: typeof Fm23SetupsRoute
    }
    '/f125/tunes/': {
      id: '/f125/tunes/'
      path: '/'
      fullPath: '/f125/tunes/'
      preLoaderRoute: typeof F125TunesIndexRouteImport
      parentRoute: typeof F125TunesRoute
    }
    '/f125/setups/': {
      id: '/f125/setups/'
      path: '/'
      fullPath: '/f125/setups/'
      preLoaderRoute: typeof F125SetupsIndexRouteImport
      parentRoute: typeof F125SetupsRoute
    }
    '/acc/setups/': {
      id: '/acc/setups/'
      path: '/'
      fullPath: '/acc/setups/'
      preLoaderRoute: typeof AccSetupsIndexRouteImport
      parentRoute: typeof AccSetupsRoute
    }
    '/ac-evo/setups/': {
      id: '/ac-evo/setups/'
      path: '/'
      fullPath: '/ac-evo/setups/'
      preLoaderRoute: typeof AcEvoSetupsIndexRouteImport
      parentRoute: typeof AcEvoSetupsRoute
    }
    '/fm23/setups/new': {
      id: '/fm23/setups/new'
      path: '/new'
      fullPath: '/fm23/setups/new'
      preLoaderRoute: typeof Fm23SetupsNewRouteImport
      parentRoute: typeof Fm23SetupsRoute
    }
    '/fm23/setups/catalog': {
      id: '/fm23/setups/catalog'
      path: '/catalog'
      fullPath: '/fm23/setups/catalog'
      preLoaderRoute: typeof Fm23SetupsCatalogRouteImport
      parentRoute: typeof Fm23SetupsRoute
    }
    '/fm23/live/pit': {
      id: '/fm23/live/pit'
      path: '/pit'
      fullPath: '/fm23/live/pit'
      preLoaderRoute: typeof Fm23LivePitRouteImport
      parentRoute: typeof Fm23LiveRoute
    }
    '/fm23/live/driver': {
      id: '/fm23/live/driver'
      path: '/driver'
      fullPath: '/fm23/live/driver'
      preLoaderRoute: typeof Fm23LiveDriverRouteImport
      parentRoute: typeof Fm23LiveRoute
    }
    '/fm23/cars_/$carOrdinal': {
      id: '/fm23/cars_/$carOrdinal'
      path: '/cars/$carOrdinal'
      fullPath: '/fm23/cars/$carOrdinal'
      preLoaderRoute: typeof Fm23CarsCarOrdinalRouteImport
      parentRoute: typeof Fm23Route
    }
    '/acc/setups/new': {
      id: '/acc/setups/new'
      path: '/new'
      fullPath: '/acc/setups/new'
      preLoaderRoute: typeof AccSetupsNewRouteImport
      parentRoute: typeof AccSetupsRoute
    }
    '/acc/setups/import': {
      id: '/acc/setups/import'
      path: '/import'
      fullPath: '/acc/setups/import'
      preLoaderRoute: typeof AccSetupsImportRouteImport
      parentRoute: typeof AccSetupsRoute
    }
    '/ac-evo/setups/new': {
      id: '/ac-evo/setups/new'
      path: '/new'
      fullPath: '/ac-evo/setups/new'
      preLoaderRoute: typeof AcEvoSetupsNewRouteImport
      parentRoute: typeof AcEvoSetupsRoute
    }
    '/ac-evo/setups/import': {
      id: '/ac-evo/setups/import'
      path: '/import'
      fullPath: '/ac-evo/setups/import'
      preLoaderRoute: typeof AcEvoSetupsImportRouteImport
      parentRoute: typeof AcEvoSetupsRoute
    }
    '/fm23/setups/wheel/': {
      id: '/fm23/setups/wheel/'
      path: '/wheel'
      fullPath: '/fm23/setups/wheel/'
      preLoaderRoute: typeof Fm23SetupsWheelIndexRouteImport
      parentRoute: typeof Fm23SetupsRoute
    }
    '/fm23/setups/wheel/$profileId': {
      id: '/fm23/setups/wheel/$profileId'
      path: '/wheel/$profileId'
      fullPath: '/fm23/setups/wheel/$profileId'
      preLoaderRoute: typeof Fm23SetupsWheelProfileIdRouteImport
      parentRoute: typeof Fm23SetupsRoute
    }
    '/fm23/setups/edit/$tuneId': {
      id: '/fm23/setups/edit/$tuneId'
      path: '/edit/$tuneId'
      fullPath: '/fm23/setups/edit/$tuneId'
      preLoaderRoute: typeof Fm23SetupsEditTuneIdRouteImport
      parentRoute: typeof Fm23SetupsRoute
    }
    '/acc/setups/edit/$tuneId': {
      id: '/acc/setups/edit/$tuneId'
      path: '/edit/$tuneId'
      fullPath: '/acc/setups/edit/$tuneId'
      preLoaderRoute: typeof AccSetupsEditTuneIdRouteImport
      parentRoute: typeof AccSetupsRoute
    }
    '/ac-evo/setups/edit/$tuneId': {
      id: '/ac-evo/setups/edit/$tuneId'
      path: '/edit/$tuneId'
      fullPath: '/ac-evo/setups/edit/$tuneId'
      preLoaderRoute: typeof AcEvoSetupsEditTuneIdRouteImport
      parentRoute: typeof AcEvoSetupsRoute
    }
  }
}

interface AcEvoSetupsRouteChildren {
  AcEvoSetupsImportRoute: typeof AcEvoSetupsImportRoute
  AcEvoSetupsNewRoute: typeof AcEvoSetupsNewRoute
  AcEvoSetupsIndexRoute: typeof AcEvoSetupsIndexRoute
  AcEvoSetupsEditTuneIdRoute: typeof AcEvoSetupsEditTuneIdRoute
}

const AcEvoSetupsRouteChildren: AcEvoSetupsRouteChildren = {
  AcEvoSetupsImportRoute: AcEvoSetupsImportRoute,
  AcEvoSetupsNewRoute: AcEvoSetupsNewRoute,
  AcEvoSetupsIndexRoute: AcEvoSetupsIndexRoute,
  AcEvoSetupsEditTuneIdRoute: AcEvoSetupsEditTuneIdRoute,
}

const AcEvoSetupsRouteWithChildren = AcEvoSetupsRoute._addFileChildren(
  AcEvoSetupsRouteChildren,
)

interface AcEvoRouteChildren {
  AcEvoAnalyseRoute: typeof AcEvoAnalyseRoute
  AcEvoCarsRoute: typeof AcEvoCarsRoute
  AcEvoChatsRoute: typeof AcEvoChatsRoute
  AcEvoCompareRoute: typeof AcEvoCompareRoute
  AcEvoLiveRoute: typeof AcEvoLiveRoute
  AcEvoRawRoute: typeof AcEvoRawRoute
  AcEvoSessionsRoute: typeof AcEvoSessionsRoute
  AcEvoSetupsRoute: typeof AcEvoSetupsRouteWithChildren
  AcEvoTracksRoute: typeof AcEvoTracksRoute
  AcEvoIndexRoute: typeof AcEvoIndexRoute
}

const AcEvoRouteChildren: AcEvoRouteChildren = {
  AcEvoAnalyseRoute: AcEvoAnalyseRoute,
  AcEvoCarsRoute: AcEvoCarsRoute,
  AcEvoChatsRoute: AcEvoChatsRoute,
  AcEvoCompareRoute: AcEvoCompareRoute,
  AcEvoLiveRoute: AcEvoLiveRoute,
  AcEvoRawRoute: AcEvoRawRoute,
  AcEvoSessionsRoute: AcEvoSessionsRoute,
  AcEvoSetupsRoute: AcEvoSetupsRouteWithChildren,
  AcEvoTracksRoute: AcEvoTracksRoute,
  AcEvoIndexRoute: AcEvoIndexRoute,
}

const AcEvoRouteWithChildren = AcEvoRoute._addFileChildren(AcEvoRouteChildren)

interface AccSetupsRouteChildren {
  AccSetupsImportRoute: typeof AccSetupsImportRoute
  AccSetupsNewRoute: typeof AccSetupsNewRoute
  AccSetupsIndexRoute: typeof AccSetupsIndexRoute
  AccSetupsEditTuneIdRoute: typeof AccSetupsEditTuneIdRoute
}

const AccSetupsRouteChildren: AccSetupsRouteChildren = {
  AccSetupsImportRoute: AccSetupsImportRoute,
  AccSetupsNewRoute: AccSetupsNewRoute,
  AccSetupsIndexRoute: AccSetupsIndexRoute,
  AccSetupsEditTuneIdRoute: AccSetupsEditTuneIdRoute,
}

const AccSetupsRouteWithChildren = AccSetupsRoute._addFileChildren(
  AccSetupsRouteChildren,
)

interface AccRouteChildren {
  AccAnalyseRoute: typeof AccAnalyseRoute
  AccCarsRoute: typeof AccCarsRoute
  AccChatsRoute: typeof AccChatsRoute
  AccCompareRoute: typeof AccCompareRoute
  AccLiveRoute: typeof AccLiveRoute
  AccRawRoute: typeof AccRawRoute
  AccSessionsRoute: typeof AccSessionsRoute
  AccSetupsRoute: typeof AccSetupsRouteWithChildren
  AccTracksRoute: typeof AccTracksRoute
  AccIndexRoute: typeof AccIndexRoute
}

const AccRouteChildren: AccRouteChildren = {
  AccAnalyseRoute: AccAnalyseRoute,
  AccCarsRoute: AccCarsRoute,
  AccChatsRoute: AccChatsRoute,
  AccCompareRoute: AccCompareRoute,
  AccLiveRoute: AccLiveRoute,
  AccRawRoute: AccRawRoute,
  AccSessionsRoute: AccSessionsRoute,
  AccSetupsRoute: AccSetupsRouteWithChildren,
  AccTracksRoute: AccTracksRoute,
  AccIndexRoute: AccIndexRoute,
}

const AccRouteWithChildren = AccRoute._addFileChildren(AccRouteChildren)

interface F125SetupsRouteChildren {
  F125SetupsIndexRoute: typeof F125SetupsIndexRoute
}

const F125SetupsRouteChildren: F125SetupsRouteChildren = {
  F125SetupsIndexRoute: F125SetupsIndexRoute,
}

const F125SetupsRouteWithChildren = F125SetupsRoute._addFileChildren(
  F125SetupsRouteChildren,
)

interface F125TunesRouteChildren {
  F125TunesIndexRoute: typeof F125TunesIndexRoute
}

const F125TunesRouteChildren: F125TunesRouteChildren = {
  F125TunesIndexRoute: F125TunesIndexRoute,
}

const F125TunesRouteWithChildren = F125TunesRoute._addFileChildren(
  F125TunesRouteChildren,
)

interface F125RouteChildren {
  F125AnalyseRoute: typeof F125AnalyseRoute
  F125CarsRoute: typeof F125CarsRoute
  F125ChatsRoute: typeof F125ChatsRoute
  F125CompareRoute: typeof F125CompareRoute
  F125LiveRoute: typeof F125LiveRoute
  F125RawRoute: typeof F125RawRoute
  F125SessionsRoute: typeof F125SessionsRoute
  F125SetupsRoute: typeof F125SetupsRouteWithChildren
  F125TracksRoute: typeof F125TracksRoute
  F125TunesRoute: typeof F125TunesRouteWithChildren
  F125IndexRoute: typeof F125IndexRoute
}

const F125RouteChildren: F125RouteChildren = {
  F125AnalyseRoute: F125AnalyseRoute,
  F125CarsRoute: F125CarsRoute,
  F125ChatsRoute: F125ChatsRoute,
  F125CompareRoute: F125CompareRoute,
  F125LiveRoute: F125LiveRoute,
  F125RawRoute: F125RawRoute,
  F125SessionsRoute: F125SessionsRoute,
  F125SetupsRoute: F125SetupsRouteWithChildren,
  F125TracksRoute: F125TracksRoute,
  F125TunesRoute: F125TunesRouteWithChildren,
  F125IndexRoute: F125IndexRoute,
}

const F125RouteWithChildren = F125Route._addFileChildren(F125RouteChildren)

interface Fm23LiveRouteChildren {
  Fm23LiveDriverRoute: typeof Fm23LiveDriverRoute
  Fm23LivePitRoute: typeof Fm23LivePitRoute
}

const Fm23LiveRouteChildren: Fm23LiveRouteChildren = {
  Fm23LiveDriverRoute: Fm23LiveDriverRoute,
  Fm23LivePitRoute: Fm23LivePitRoute,
}

const Fm23LiveRouteWithChildren = Fm23LiveRoute._addFileChildren(
  Fm23LiveRouteChildren,
)

interface Fm23SetupsRouteChildren {
  Fm23SetupsCatalogRoute: typeof Fm23SetupsCatalogRoute
  Fm23SetupsNewRoute: typeof Fm23SetupsNewRoute
  Fm23SetupsIndexRoute: typeof Fm23SetupsIndexRoute
  Fm23SetupsEditTuneIdRoute: typeof Fm23SetupsEditTuneIdRoute
  Fm23SetupsWheelProfileIdRoute: typeof Fm23SetupsWheelProfileIdRoute
  Fm23SetupsWheelIndexRoute: typeof Fm23SetupsWheelIndexRoute
}

const Fm23SetupsRouteChildren: Fm23SetupsRouteChildren = {
  Fm23SetupsCatalogRoute: Fm23SetupsCatalogRoute,
  Fm23SetupsNewRoute: Fm23SetupsNewRoute,
  Fm23SetupsIndexRoute: Fm23SetupsIndexRoute,
  Fm23SetupsEditTuneIdRoute: Fm23SetupsEditTuneIdRoute,
  Fm23SetupsWheelProfileIdRoute: Fm23SetupsWheelProfileIdRoute,
  Fm23SetupsWheelIndexRoute: Fm23SetupsWheelIndexRoute,
}

const Fm23SetupsRouteWithChildren = Fm23SetupsRoute._addFileChildren(
  Fm23SetupsRouteChildren,
)

interface Fm23RouteChildren {
  Fm23AnalyseRoute: typeof Fm23AnalyseRoute
  Fm23CarsRoute: typeof Fm23CarsRoute
  Fm23ChatsRoute: typeof Fm23ChatsRoute
  Fm23CompareRoute: typeof Fm23CompareRoute
  Fm23LiveRoute: typeof Fm23LiveRouteWithChildren
  Fm23RawRoute: typeof Fm23RawRoute
  Fm23SessionsRoute: typeof Fm23SessionsRoute
  Fm23SetupsRoute: typeof Fm23SetupsRouteWithChildren
  Fm23TracksRoute: typeof Fm23TracksRoute
  Fm23IndexRoute: typeof Fm23IndexRoute
  Fm23CarsCarOrdinalRoute: typeof Fm23CarsCarOrdinalRoute
}

const Fm23RouteChildren: Fm23RouteChildren = {
  Fm23AnalyseRoute: Fm23AnalyseRoute,
  Fm23CarsRoute: Fm23CarsRoute,
  Fm23ChatsRoute: Fm23ChatsRoute,
  Fm23CompareRoute: Fm23CompareRoute,
  Fm23LiveRoute: Fm23LiveRouteWithChildren,
  Fm23RawRoute: Fm23RawRoute,
  Fm23SessionsRoute: Fm23SessionsRoute,
  Fm23SetupsRoute: Fm23SetupsRouteWithChildren,
  Fm23TracksRoute: Fm23TracksRoute,
  Fm23IndexRoute: Fm23IndexRoute,
  Fm23CarsCarOrdinalRoute: Fm23CarsCarOrdinalRoute,
}

const Fm23RouteWithChildren = Fm23Route._addFileChildren(Fm23RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcEvoRoute: AcEvoRouteWithChildren,
  AccRoute: AccRouteWithChildren,
  DevRoute: DevRoute,
  F125Route: F125RouteWithChildren,
  Fm23Route: Fm23RouteWithChildren,
  DashCombo1Route: DashCombo1Route,
  DashCombo2Route: DashCombo2Route,
  DashIndexRoute: DashIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
