import type React from "react";
import { useMemo, useState } from "react";
import { m } from "@/paraglide/messages";
import { useSetupFiles } from "../../hooks/setup-queries";
import { useBackupLocalSetup, useDeleteBackup, useDisconnectGoogleDrive, useRenameBackup, useRestoreBackup, useSetupBackupStatus, useSetupBackups, type SetupBackup, type SetupBackupApiError, type SetupGameId } from "../../hooks/setup-backup-queries";
import { Button } from "../ui/button";

type SortKey = "car" | "track" | "name" | "updated";
type LocalSortKey = Exclude<SortKey, "updated">;
type PendingConflict =
  | { kind: "backup"; payload: { gameId: SetupGameId; localPath: string; conflict: "error" | "replace" | "copy" } }
  | { kind: "rename"; payload: { id: string; gameId: SetupGameId; name: string; conflict: "error" | "replace" | "copy" } }
  | { kind: "restore"; payload: { id: string; gameId: SetupGameId; conflict: "error" | "replace" | "copy" } };
type Dialog = { kind: "rename"; item: SetupBackup } | { kind: "delete"; id: string } | { kind: "disconnect" } | { kind: "conflict"; pending: PendingConflict };

const errorMessage = (error: unknown): string => {
  const code = (error as SetupBackupApiError | undefined)?.code;
  const messages: Record<string, () => string> = {
    "setup-folder-missing": m.setup_manager_setup_folder_missing,
    "local-setup-not-found": m.setup_manager_local_setup_not_found,
    "backup-not-found": m.setup_manager_backup_not_found,
    "invalid-name": m.setup_manager_invalid_name,
    "invalid-archive": m.setup_manager_invalid_archive,
    "invalid-manifest": m.setup_manager_invalid_archive,
    "unsupported-schema": m.setup_manager_unsupported_schema,
    "unsupported-format": m.setup_manager_unsupported_format,
    "binding-mismatch": m.setup_manager_binding_mismatch,
    "drive-not-configured": m.setup_manager_status_unconfigured,
    "drive-disconnected": m.setup_manager_status_disconnected,
    "drive-unavailable": m.setup_manager_status_unavailable,
    "duplicate-name": m.setup_manager_conflict_title,
  };
  return (code && messages[code]?.()) || m.setup_manager_status_unavailable();
};

export function SetupManagerPage({ gameId }: { gameId: SetupGameId }) {
  const [search, setSearch] = useState("");
  const [notice, setNotice] = useState("");
  const [dialog, setDialog] = useState<Dialog | null>(null);
  const [sort, setSort] = useState<{ local: LocalSortKey; drive: SortKey }>({ local: "name", drive: "updated" });
  const files = useSetupFiles(gameId); const status = useSetupBackupStatus(); const backups = useSetupBackups(gameId);
  const backup = useBackupLocalSetup(); const restore = useRestoreBackup(); const rename = useRenameBackup(); const remove = useDeleteBackup(); const disconnect = useDisconnectGoogleDrive();
  const filtered = useMemo(() => (files.data?.files ?? []).filter((f) => `${f.carModel} ${f.trackName} ${f.fileName}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => { const key = sort.local === "car" ? "carModel" : sort.local === "track" ? "trackName" : "fileName"; return String(a[key]).localeCompare(String(b[key])); }), [files.data, search, sort.local]);
  const driveRows = useMemo(() => [...(backups.data ?? [])].filter((item) => item.valid === false || `${item.carId} ${item.trackId} ${item.setupName}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => { const key = sort.drive === "car" ? "carId" : sort.drive === "track" ? "trackId" : sort.drive === "name" ? "setupName" : "updatedAt"; return String((a as SetupBackup)[key] ?? "").localeCompare(String((b as SetupBackup)[key] ?? "")); }), [backups.data, sort.drive, search]);
  const run = (mutation: { mutate: (p: any, o?: any) => void }, payload: any, kind: PendingConflict["kind"]) => mutation.mutate(payload, { onSuccess: () => { setDialog(null); setNotice(kind === "backup" ? m.setup_manager_backup() : kind === "restore" ? m.setup_manager_restore() : m.setup_manager_rename()); }, onError: (e: unknown) => { if ((e as SetupBackupApiError).code === "duplicate-name") setDialog({ kind: "conflict", pending: { kind, payload } } as Dialog); else { setDialog(null); setNotice(errorMessage(e)); } } });
  const connect = () => { const popup = window.open("/api/setup-backups/google/connect", "raceiq-google-drive", "popup,width=500,height=700"); setNotice(m.setup_manager_authorizing()); if (!popup) return setNotice(m.setup_manager_authorization_timeout()); const started = Date.now(); const timer = window.setInterval(() => { if (popup.closed || Date.now() - started > 120_000) { window.clearInterval(timer); void status.refetch().then((r) => { if (r.data?.status !== "connected") setNotice(m.setup_manager_authorization_timeout()); }); if (!popup.closed) popup.close(); } else void status.refetch().then((r) => { if (r.data?.status === "connected") { window.clearInterval(timer); setNotice(m.setup_manager_status_connected()); } }); }, 1000); };
  const statusText = status.data?.status === "connected" ? m.setup_manager_status_connected() : status.data?.status === "unavailable" ? m.setup_manager_status_unavailable() : status.data?.status === "unconfigured" ? m.setup_manager_status_unconfigured() : m.setup_manager_status_disconnected();
  return <main className="mx-auto max-w-6xl space-y-4 p-4"><header className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-lg font-semibold">{m.setup_manager_title()}</h1><input aria-label={m.setup_manager_search_placeholder()} placeholder={m.setup_manager_search_placeholder()} value={search} onChange={(e) => setSearch(e.target.value)} className="rounded border border-app-border bg-app-surface px-3 py-2 text-sm" /></header>
    <section className="flex items-center justify-between border border-app-border bg-app-surface px-3 py-2 text-sm"><span>{statusText}</span>{status.data?.status === "connected" ? <Button variant="app-ghost" onClick={() => setDialog({ kind: "disconnect" })}>{m.setup_manager_disconnect()}</Button> : <Button variant="app-primary" onClick={connect}>{m.setup_manager_connect()}</Button>}</section>
    {notice && <p role="status" aria-live="polite" className="text-sm text-app-accent">{notice}</p>}
    {(files.error || status.error || backups.error) && <p role="alert" className="text-sm text-status-error">{errorMessage(files.error ?? status.error ?? backups.error)}</p>}
    <div className="grid gap-4 md:grid-cols-2"><Panel title={m.setup_manager_local_title()} sort={sort.local} onSort={(v) => setSort((s) => ({ ...s, local: v as LocalSortKey }))}>{files.isLoading ? <p>{m.common_loading()}</p> : filtered.length === 0 ? <p>{m.setup_manager_no_local()}</p> : filtered.map((file) => <div key={file.absolutePath} className="flex items-center justify-between border-b border-app-border py-2 text-sm"><span>{file.carModel} / {file.trackName} / {file.fileName}</span><Button variant="app-ghost" size="sm" onClick={() => run(backup, { gameId, localPath: file.absolutePath, conflict: "error" }, "backup")}>{m.setup_manager_backup()}</Button></div>)}</Panel>
      <Panel title={m.setup_manager_drive_title()} sort={sort.drive} onSort={(v) => setSort((s) => ({ ...s, drive: v }))} allowUpdated>{backups.isLoading ? <p>{m.common_loading()}</p> : driveRows.length === 0 ? <p>{m.setup_manager_no_backups()}</p> : driveRows.map((item) => item.valid === false ? <div key={item.id} className="flex justify-between border-b border-app-border py-2 text-sm" role="alert"><span>{errorMessage({ code: item.code } as SetupBackupApiError)}</span><Button variant="app-ghost" size="sm" onClick={() => setDialog({ kind: "delete", id: item.id })}>{m.common_delete()}</Button></div> : <div key={item.id} className="flex items-center justify-between border-b border-app-border py-2 text-sm"><span>{item.carId} / {item.trackId} / {item.setupName}<small className="ml-2 opacity-70">{item.updatedAt ? new Date(item.updatedAt).toLocaleString() : ""}</small></span><span className="flex gap-1"><Button variant="app-ghost" size="sm" onClick={() => run(restore, { id: item.id, gameId, conflict: "error" }, "restore")}>{m.setup_manager_restore()}</Button><Button variant="app-ghost" size="sm" onClick={() => setDialog({ kind: "rename", item })}>{m.setup_manager_rename()}</Button><Button variant="app-ghost" size="sm" onClick={() => setDialog({ kind: "delete", id: item.id })}>{m.common_delete()}</Button></span></div>)}</Panel></div>
    {dialog && <DialogView dialog={dialog} close={() => setDialog(null)} onConfirm={(value) => { if (dialog.kind === "delete") remove.mutate({ id: dialog.id, gameId }, { onSuccess: () => { setDialog(null); setNotice(m.common_delete()); }, onError: (e) => { setDialog(null); setNotice(errorMessage(e)); } }); else if (dialog.kind === "disconnect") disconnect.mutate(undefined, { onSuccess: () => { setDialog(null); setNotice(m.setup_manager_disconnect()); }, onError: (e) => { setDialog(null); setNotice(errorMessage(e)); } }); else if (dialog.kind === "rename") run(rename, { id: dialog.item.id, gameId, name: value, conflict: "error" }, "rename"); else { const p = dialog.pending; const conflict = value as "replace" | "copy"; run(p.kind === "backup" ? backup : p.kind === "rename" ? rename : restore, { ...p.payload, conflict }, p.kind); } }} />}</main>;
}
function Panel({ title, children, sort, onSort, allowUpdated = false }: { title: string; children: React.ReactNode; sort?: SortKey; onSort?: (v: SortKey) => void; allowUpdated?: boolean }) { return <section className="border border-app-border bg-app-surface p-3"><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-semibold">{title}</h2>{onSort && <select aria-label={title} value={sort} onChange={(e) => onSort(e.target.value as SortKey)} className="rounded border border-app-border bg-app-surface text-xs"><option value="car">{m.setup_manager_sort_car()}</option><option value="track">{m.setup_manager_sort_track()}</option><option value="name">{m.setup_manager_sort_name()}</option>{allowUpdated && <option value="updated">{m.setup_manager_sort_updated()}</option>}</select>}</div>{children}</section>; }
function DialogView({ dialog, close, onConfirm }: { dialog: Dialog; close: () => void; onConfirm: (value: string) => void }) { const [value, setValue] = useState(dialog.kind === "rename" ? dialog.item.setupName : ""); const title = dialog.kind === "conflict" ? m.setup_manager_conflict_title() : dialog.kind === "rename" ? m.setup_manager_rename() : dialog.kind === "disconnect" ? m.setup_manager_disconnect() : m.common_delete(); return <div className="fixed inset-0 z-50 grid place-items-center bg-app-bg/80 p-4" role="presentation"><section role="dialog" aria-modal="true" aria-labelledby="setup-dialog-title" className="w-full max-w-md space-y-4 border border-app-border bg-app-surface p-4"><h2 id="setup-dialog-title" className="font-semibold">{title}</h2>{dialog.kind === "conflict" && <p>{m.setup_manager_conflict_body()}</p>}{dialog.kind === "rename" && <input autoFocus aria-label={m.setup_manager_rename()} value={value} onChange={(e) => setValue(e.target.value)} className="w-full rounded border border-app-border bg-app-surface px-3 py-2" />}{dialog.kind === "delete" && <p>{m.browser_confirm_delete()}</p>}<div className="flex justify-end gap-2"><Button variant="app-ghost" onClick={close}>{m.common_cancel()}</Button>{dialog.kind === "conflict" ? <><Button variant="app-ghost" onClick={() => onConfirm("copy")}>{dialog.pending.kind === "restore" ? m.setup_manager_restore_copy() : m.setup_manager_save_copy()}</Button><Button variant="app-primary" onClick={() => onConfirm("replace")}>{m.setup_manager_replace()}</Button></> : <Button variant="app-primary" onClick={() => onConfirm(value)}>{dialog.kind === "rename" ? m.setup_manager_rename() : dialog.kind === "disconnect" ? m.setup_manager_disconnect() : m.common_delete()}</Button>}</div></section></div>; }
