import type { GameId } from "../../../shared/games/ids";

export const queryKeys = {
  laps: ["laps"] as const,
  settings: ["settings"] as const,
  storageSessions: ["storage", "sessions"] as const,
  cacheStatus: ["cache", "status"] as const,
  trackName: (key: number | string) => ["track-name", key] as const,
  trackSectors: (key: number | string) => ["track-sectors", key] as const,
  trackSectorBoundaries: (key: number | string) => ["track-sector-boundaries", key] as const,
  trackOutline: (key: number | string) => ["track-outline", key] as const,
  sessions: ["sessions"] as const,
  tracks: ["tracks"] as const,
  carName: (key: number | string) => ["car-name", key] as const,
  userTunes: ["user-tunes"] as const,
  catalogTunes: ["catalog-tunes"] as const,
  driverProfile: (gameId: GameId | null) => ["driver-profile", gameId] as const,
  driverProfileRuns: (gameId: GameId | null) => ["driver-profile-runs", gameId] as const,
  sessionResults: ["session-result"] as const,
  sessionResult: (sessionId: number | null, gameId: GameId | null) => ["session-result", sessionId, gameId] as const,
  raceResultSummaries: ["race-result-summary"] as const,
  raceResultSummary: (gameId: GameId | null, trackOrdinal?: number) => ["race-result-summary", gameId, trackOrdinal] as const,
  raceResultRecents: ["race-result-recent"] as const,
  raceResultRecent: (gameId: GameId | null) => ["race-result-recent", gameId] as const,
};
