import { useMutation, useQuery, useQueryClient, type QueryClient } from "@tanstack/react-query";

export type SetupGameId = "acc" | "ac-evo";
export type SetupBackupApiError = Error & { code?: string };
export type SetupBackup = { valid?: true; id: string; gameId: SetupGameId; carId: string; trackId: string; setupName: string; updatedAt: string; [key: string]: unknown };
export type SetupBackupList = Array<SetupBackup | { valid: false; id: string; code: string; error: string; driveFileName?: string }>;
const api = (path: string, init?: RequestInit) => fetch(path, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } });
async function json<T>(response: Response): Promise<T> { const body = await response.json().catch(() => ({})); if (!response.ok) { const error = Object.assign(new Error(body.error ?? "Request failed"), { code: body.code }); throw error as SetupBackupApiError; } return body as T; }
function mutation(path: string, method: string, qc: QueryClient) { return useMutation({ mutationFn: async () => json(await api(path, { method })), onSuccess: () => { void qc.invalidateQueries({ queryKey: ["setup-backups"] }); } }); }
export function useSetupBackupStatus() { return useQuery({ queryKey: ["setup-backups", "status"], queryFn: () => api("/api/setup-backups/google/status").then((r) => json<{ status: "unconfigured" | "disconnected" | "connected" | "unavailable" }>(r)) }); }
export function useSetupBackups(gameId: SetupGameId) { return useQuery({ queryKey: ["setup-backups", gameId], queryFn: () => api(`/api/setup-backups?gameId=${gameId}`).then((r) => json<{ backups: SetupBackupList }>(r)).then((body) => body.backups), staleTime: 15_000 }); }
export function useBackupLocalSetup() { const qc = useQueryClient(); return useMutation({ mutationFn: (body: { gameId: SetupGameId; localPath: string; conflict: "error" | "replace" | "copy" }) => api("/api/setup-backups", { method: "POST", body: JSON.stringify(body) }).then(json), onSuccess: (_d, v) => { void qc.invalidateQueries({ queryKey: ["setup-backups", v.gameId] }); } }); }
export function useRenameBackup() { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, ...body }: { id: string; gameId: SetupGameId; name: string; conflict: "error" | "replace" | "copy" }) => api(`/api/setup-backups/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(body) }).then(json), onSuccess: (_d, v) => { void qc.invalidateQueries({ queryKey: ["setup-backups", v.gameId] }); } }); }
export function useRestoreBackup() { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, ...body }: { id: string; gameId: SetupGameId; conflict: "error" | "replace" | "copy" }) => api(`/api/setup-backups/${encodeURIComponent(id)}/restore`, { method: "POST", body: JSON.stringify(body) }).then(json), onSuccess: (_d, v) => { void qc.invalidateQueries({ queryKey: ["setup-backups", v.gameId] }); void qc.invalidateQueries({ queryKey: ["setup-files", v.gameId] }); } }); }
export function useDeleteBackup() { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, gameId }: { id: string; gameId: SetupGameId }) => api(`/api/setup-backups/${encodeURIComponent(id)}?gameId=${gameId}`, { method: "DELETE" }).then(json), onSuccess: (_d, v) => { void qc.invalidateQueries({ queryKey: ["setup-backups", v.gameId] }); } }); }
export function useDisconnectGoogleDrive() { const qc = useQueryClient(); return mutation("/api/setup-backups/google/connection", "DELETE", qc); }
export { api as setupBackupApi };
