import { useEffect, useRef } from "react";
import { useSettings } from "../../hooks/settings";
import { LiveEngineerAudioPlayer } from "../../lib/live-engineer-audio";
import { useLiveEngineerStore } from "../../stores/live-engineer";
export function RadioPlaybackController() {
 const { displaySettings } = useSettings(); const playerRef = useRef<LiveEngineerAudioPlayer | null>(null); const line = useLiveEngineerStore((s) => s.voiceCurrent); const enqueue = useLiveEngineerStore((s) => s.enqueueControl); const finish = useLiveEngineerStore((s) => s.finishVoiceLine); const setPlayback = useLiveEngineerStore((s) => s.setPlayback);
 useEffect(() => { playerRef.current?.setVolume(displaySettings.radioVolume); }, [displaySettings.radioVolume]);
 useEffect(() => { if (!line) return; let cancelled = false; const enabled = line.family === "spotter" ? displaySettings.radioSpotterEnabled : displaySettings.radioRaceEngineerEnabled; if (!enabled) { enqueue({ type: "live-engineer-delivery-status", protocolVersion: 2, deliveryId: line.deliveryId, status: "muted", reason: "radio-disabled" }); finish(line.deliveryId); return; } const player = playerRef.current ?? (playerRef.current = new LiveEngineerAudioPlayer()); setPlayback("playing"); enqueue({ type: "live-engineer-delivery-status", protocolVersion: 2, deliveryId: line.deliveryId, status: "started" }); player.play(line.segmentIds, displaySettings.radioVolume).then(() => { if (!cancelled) { enqueue({ type: "live-engineer-delivery-status", protocolVersion: 2, deliveryId: line.deliveryId, status: "completed" }); finish(line.deliveryId); } }).catch((error) => { if (!cancelled) { const reason = error?.code === "audio-blocked" ? "audio-blocked" : error?.code === "asset-missing" ? "asset-missing" : error?.code === "catalog-mismatch" ? "catalog-mismatch" : "decode-failed"; enqueue({ type: "live-engineer-delivery-status", protocolVersion: 2, deliveryId: line.deliveryId, status: "failed", reason }); setPlayback("failed"); finish(line.deliveryId); } }); return () => { cancelled = true; player.stop(); }; }, [line, displaySettings.radioRaceEngineerEnabled, displaySettings.radioSpotterEnabled, displaySettings.radioVolume, enqueue, finish, setPlayback]); return null;
}
