
import { SETUP_CONCEPT_DEFINITIONS } from "../../shared/racing/setups/catalog/concepts";
import type { SemanticDefinition } from "./model";

const SEMANTIC_DEFINITIONS_LIVE: Record<string, SemanticDefinition> = {
  "damage.brake-pad-wear": {
    label: "Brake Pad Wear",
    description: "Brake pad wear, FL/FR/RL/RR.",
    parentId: "damage",
    canonicalUnit: "mm",
    shape: "per-wheel",
    ordering: ["FL", "FR", "RL", "RR"],
  },
  "tires.tire-radius": {
    label: "Tire Radius",
    description: "Tire radius, FL/FR/RL/RR.",
    parentId: "tires",
    canonicalUnit: "m",
    shape: "per-wheel",
    ordering: ["FL", "FR", "RL", "RR"],
  },
  "tires.tire-camber": {
    label: "Tire Camber",
    description: "Tire camber, FL/FR/RL/RR.",
    parentId: "tires",
    canonicalUnit: "rad",
    shape: "per-wheel",
    ordering: ["FL", "FR", "RL", "RR"],
  },
  ...SETUP_CONCEPT_DEFINITIONS,
  "aero.drs-active": {
    label: "DRS active",
    description: "Whether drag-reduction flap is currently open.",
    parentId: "aero",
    canonicalUnit: "boolean",
    shape: "scalar",
  },
  "aero.drs-available": {
    label: "DRS available",
    description: "Whether source currently permits DRS activation.",
    parentId: "aero",
    canonicalUnit: "boolean",
    shape: "scalar",
  },
  "aero.front-aero-height": {
    label: "Front aero height",
    description: "Live front aerodynamic reference height above ground.",
    parentId: "aero",
    canonicalUnit: "m",
    shape: "scalar",
  },
  "aero.rear-aero-height": {
    label: "Rear aero height",
    description: "Live rear aerodynamic reference height above ground.",
    parentId: "aero",
    canonicalUnit: "m",
    shape: "scalar",
  },
  "motion.front-axle-roll-angle": {
    label: "Front axle roll angle",
    description: "Live roll angle measured across front axle.",
    parentId: "motion",
    canonicalUnit: "rad",
    shape: "scalar",
  },
  "motion.rear-axle-roll-angle": {
    label: "Rear axle roll angle",
    description: "Live roll angle measured across rear axle.",
    parentId: "motion",
    canonicalUnit: "rad",
    shape: "scalar",
  },
  "brakes.brake-bias": {
    label: "Front brake bias",
    description: "Current front-axle brake bias.",
    parentId: "brakes",
    canonicalUnit: "%",
    shape: "scalar",
  },
  "electronics.traction-control-level": {
    label: "Traction-control level",
    description: "Current driver-selected traction-control setting.",
    parentId: "electronics",
    canonicalUnit: "level",
    shape: "scalar",
  },
  "electronics.abs-level": {
    label: "ABS level",
    description: "Current driver-selected anti-lock braking setting.",
    parentId: "electronics",
    canonicalUnit: "level",
    shape: "scalar",
  },
  "engine.engine-map": {
    label: "Engine map",
    description: "Current driver-selected engine map.",
    parentId: "engine",
    canonicalUnit: "level",
    shape: "scalar",
  },
  "engine.coolant-temperature": {
    label: "Coolant temperature",
    description: "Engine coolant or water temperature.",
    parentId: "engine",
    canonicalUnit: "°C",
    shape: "scalar",
  },
  "engine.oil-temperature": {
    label: "Oil temperature",
    description: "Current engine oil temperature.",
    parentId: "engine",
    canonicalUnit: "°C",
    shape: "scalar",
  },
  "engine.oil-pressure": {
    label: "Oil pressure",
    description: "Current engine oil pressure.",
    parentId: "engine",
    canonicalUnit: "bar",
    shape: "scalar",
  },
  "engine.cylinder-count": {
    label: "Engine cylinder count",
    description: "Number of engine cylinders.",
    parentId: "engine",
    canonicalUnit: "count",
    shape: "scalar",
  },
  "engine.shift-light.first-rpm": {
    label: "Shift-light first RPM",
    description: "Engine speed where first shift-light indicator illuminates.",
    parentId: "engine.shift-light",
    canonicalUnit: "rpm",
    shape: "scalar",
  },
  "engine.shift-light.shift-rpm": {
    label: "Shift-light target RPM",
    description: "Engine speed for primary upshift indication.",
    parentId: "engine.shift-light",
    canonicalUnit: "rpm",
    shape: "scalar",
  },
  "engine.shift-light.last-rpm": {
    label: "Shift-light last RPM",
    description: "Engine speed where final steady shift-light indicator illuminates.",
    parentId: "engine.shift-light",
    canonicalUnit: "rpm",
    shape: "scalar",
  },
  "engine.shift-light.blink-rpm": {
    label: "Shift-light blink RPM",
    description: "Engine speed where shift lights begin blinking.",
    parentId: "engine.shift-light",
    canonicalUnit: "rpm",
    shape: "scalar",
  },
  "suspension.ride-height": {
    label: "Live ride height",
    description:
      "Measured front/rear or per-corner ride height while vehicle is running.",
    parentId: "suspension",
    canonicalUnit: "m",
    shape: "array",
  },
  "diagnostics.sim-build-version": {
    label: "Simulator build version",
    description: "Source simulator build or telemetry protocol version.",
    parentId: "diagnostics",
    canonicalUnit: "text",
    shape: "scalar",
  },
  "fuel.fuel-percent": {
    label: "Fuel remaining percentage",
    description: "Fuel remaining as percentage of usable capacity.",
    parentId: "fuel",
    canonicalUnit: "%",
    shape: "scalar",
  },
  "fuel.remaining-volume": {
    label: "Fuel remaining volume",
    description: "Current usable fuel volume.",
    parentId: "fuel",
    canonicalUnit: "L",
    shape: "scalar",
  },
  "fuel.density": {
    label: "Fuel density",
    description: "Fuel mass per unit volume.",
    parentId: "fuel",
    canonicalUnit: "kg/L",
    shape: "scalar",
  },
  "fuel.maximum-fill-percentage": {
    label: "Maximum fuel fill percentage",
    description: "Maximum allowed fuel fill as percentage of tank capacity.",
    parentId: "fuel",
    canonicalUnit: "%",
    shape: "scalar",
  },
  "fuel.fuel": {
    label: "RaceIQ packet fuel value",
    description: "Normalized packet field whose legacy unit differs by game; use fuel volume or percentage semantic values for comparison.",
    parentId: "fuel",
    canonicalUnit: "game-native",
    shape: "scalar",
  },
  "fuel.laps-remaining": {
    label: "Fuel laps remaining",
    description: "Source estimate of laps possible with current fuel.",
    parentId: "fuel",
    canonicalUnit: "count",
    shape: "scalar",
  },
  "tires.tire-compound": {
    label: "Tire compound",
    description: "Current player tire compound in RaceIQ's common representation.",
    parentId: "tires",
    canonicalUnit: "enum",
    shape: "scalar",
  },
  "tires.tire-compound-name": {
    label: "Tire compound name",
    description: "Source display name for current player tire compound.",
    parentId: "tires",
    canonicalUnit: "text",
    shape: "scalar",
  },
  "tires.tire-compound-code": {
    label: "Tire compound code",
    description: "Source numeric identifier for current player tire compound.",
    parentId: "tires",
    canonicalUnit: "id",
    shape: "scalar",
  },
  "identity.track-name": {
    label: "Track name",
    description: "Source-provided display name for current track configuration.",
    parentId: "identity.track",
    canonicalUnit: "text",
    shape: "scalar",
  },
  "identity.track.configuration-name": {
    label: "Track configuration name",
    description: "Source display name for current track layout or configuration.",
    parentId: "identity.track",
    canonicalUnit: "text",
    shape: "scalar",
  },
  "identity.track.altitude": {
    label: "Track altitude",
    description: "Track elevation above sea level.",
    parentId: "identity.track",
    canonicalUnit: "m",
    shape: "scalar",
  },
  "identity.track.city": {
    label: "Track city",
    description: "City associated with current track.",
    parentId: "identity.track",
    canonicalUnit: "text",
    shape: "scalar",
  },
  "identity.track.country": {
    label: "Track country",
    description: "Country associated with current track.",
    parentId: "identity.track",
    canonicalUnit: "text",
    shape: "scalar",
  },
  "identity.track.direction": {
    label: "Track direction",
    description: "Track direction category such as neutral, left, or right.",
    parentId: "identity.track",
    canonicalUnit: "text",
    shape: "scalar",
  },
  "identity.track.latitude": {
    label: "Track latitude",
    description: "Geographic latitude of current track.",
    parentId: "identity.track",
    canonicalUnit: "deg",
    shape: "scalar",
  },
  "identity.track.longitude": {
    label: "Track longitude",
    description: "Geographic longitude of current track.",
    parentId: "identity.track",
    canonicalUnit: "deg",
    shape: "scalar",
  },
  "identity.track.north-offset": {
    label: "Track north offset",
    description: "Angular offset from track coordinate north to geographic north.",
    parentId: "identity.track",
    canonicalUnit: "deg",
    shape: "scalar",
  },
  "identity.track.turn-count": {
    label: "Track turn count",
    description: "Source-reported number of turns around current track.",
    parentId: "identity.track",
    canonicalUnit: "count",
    shape: "scalar",
  },
  "identity.track.type": {
    label: "Track type",
    description: "Source category for track or racing venue type.",
    parentId: "identity.track",
    canonicalUnit: "text",
    shape: "scalar",
  },
  "timing.track-length": {
    label: "Track length",
    description: "Official or source-reported lap length.",
    parentId: "identity.track",
    canonicalUnit: "m",
    shape: "scalar",
  },
  "timing.official-track-length": {
    label: "Official track length",
    description: "Sanctioned lap length for current track configuration.",
    parentId: "identity.track",
    canonicalUnit: "m",
    shape: "scalar",
  },
  "timing.current-lap-valid": {
    label: "Current lap valid",
    description: "Whether current lap remains valid according to source.",
    parentId: "timing",
    canonicalUnit: "boolean",
    shape: "scalar",
  },
  "timing.total-laps": {
    label: "Session total laps",
    description: "Configured or scheduled number of laps in current session.",
    parentId: "timing",
    canonicalUnit: "count",
    shape: "scalar",
  },
  "timing.predicted-lap-time": {
    label: "Predicted lap time",
    description: "Source prediction for completed time of current lap.",
    parentId: "timing",
    canonicalUnit: "s",
    shape: "scalar",
  },
  "timing.ideal-lap-time": {
    label: "Ideal lap time",
    description: "Source-provided ideal or optimal lap time.",
    parentId: "timing",
    canonicalUnit: "s",
    shape: "scalar",
  },
  "timing.sector.current-index": {
    label: "Current sector index",
    description: "Zero-based index of sector vehicle currently occupies.",
    parentId: "timing.sector",
    canonicalUnit: "index",
    shape: "scalar",
  },
  "timing.sector.current-time": {
    label: "Current sector running time",
    description: "Elapsed time since vehicle entered current sector.",
    parentId: "timing.sector",
    canonicalUnit: "s",
    shape: "scalar",
  },
  "timing.sector.last-completed-time": {
    label: "Last completed sector time",
    description: "Time taken through most recently completed sector.",
    parentId: "timing.sector",
    canonicalUnit: "s",
    shape: "scalar",
  },
  "timing.sector.layout.indexes": {
    label: "Sector indexes",
    description: "Ordered native sector identifiers.",
    parentId: "timing.sector.layout",
    canonicalUnit: "index",
    shape: "array",
  },
  "timing.sector.layout.start-fractions": {
    label: "Sector start fractions",
    description:
      "Ordered lap fractions where sectors start. Count can vary by simulator and track.",
    parentId: "timing.sector.layout",
    canonicalUnit: "fraction",
    shape: "array",
  },
  "timing.sector.current-lap.s1": {
    label: "Current lap S1",
    description: "Completed sector 1 time on current lap.",
    parentId: "timing.sector.current-lap",
    canonicalUnit: "s",
    shape: "scalar",
  },
  "timing.sector.current-lap.s2": {
    label: "Current lap S2",
    description: "Completed sector 2 time on current lap.",
    parentId: "timing.sector.current-lap",
    canonicalUnit: "s",
    shape: "scalar",
  },
  "timing.sector.current-lap.s3": {
    label: "Current lap S3",
    description: "Completed sector 3 time on current lap.",
    parentId: "timing.sector.current-lap",
    canonicalUnit: "s",
    shape: "scalar",
  },
  "timing.sector.current-lap.times": {
    label: "Current lap sector times",
    description:
      "Ordered completed/running sector-time array assembled by RaceIQ for current lap.",
    parentId: "timing.sector.current-lap",
    canonicalUnit: "s",
    shape: "array",
  },
  "timing.sector.last-lap.s1": {
    label: "Last lap S1",
    description: "Sector 1 time from most recently completed lap.",
    parentId: "timing.sector.last-lap",
    canonicalUnit: "s",
    shape: "scalar",
  },
  "timing.sector.last-lap.s2": {
    label: "Last lap S2",
    description: "Sector 2 time from most recently completed lap.",
    parentId: "timing.sector.last-lap",
    canonicalUnit: "s",
    shape: "scalar",
  },
  "timing.sector.last-lap.s3": {
    label: "Last lap S3",
    description: "Sector 3 time from most recently completed lap.",
    parentId: "timing.sector.last-lap",
    canonicalUnit: "s",
    shape: "scalar",
  },
  "timing.sector.last-lap.times": {
    label: "Last lap sector times",
    description:
      "Ordered sector times for most recently completed lap; supports variable sector counts.",
    parentId: "timing.sector.last-lap",
    canonicalUnit: "s",
    shape: "array",
  },
  "timing.sector.best-times": {
    label: "Best sector times",
    description:
      "Fastest observed time for each sector, possibly drawn from different laps.",
    parentId: "timing.sector",
    canonicalUnit: "s",
    shape: "array",
  },
  "timing.sector.lap-history.s1": {
    label: "Lap-history S1",
    description: "Sector 1 time keyed by completed lap number.",
    parentId: "timing.sector.lap-history",
    canonicalUnit: "s",
    shape: "structured",
  },
  "timing.sector.lap-history.s2": {
    label: "Lap-history S2",
    description: "Sector 2 time keyed by completed lap number.",
    parentId: "timing.sector.lap-history",
    canonicalUnit: "s",
    shape: "structured",
  },
  "timing.sector.lap-history.s3": {
    label: "Lap-history S3",
    description: "Sector 3 time keyed by completed lap number.",
    parentId: "timing.sector.lap-history",
    canonicalUnit: "s",
    shape: "structured",
  },
  "timing.sector.lap-history.lap-time": {
    label: "Lap-history lap time",
    description: "Completed lap time stored beside lap's sector splits.",
    parentId: "timing.sector.lap-history",
    canonicalUnit: "s",
    shape: "structured",
  },
  "timing.sector.competitor-best.s1": {
    label: "Competitor best S1",
    description: "Best sector 1 time for each competitor.",
    parentId: "timing.sector.competitor-best",
    canonicalUnit: "s",
    shape: "structured",
  },
  "timing.sector.competitor-best.s2": {
    label: "Competitor best S2",
    description: "Best sector 2 time for each competitor.",
    parentId: "timing.sector.competitor-best",
    canonicalUnit: "s",
    shape: "structured",
  },
  "timing.sector.competitor-best.s3": {
    label: "Competitor best S3",
    description: "Best sector 3 time for each competitor.",
    parentId: "timing.sector.competitor-best",
    canonicalUnit: "s",
    shape: "structured",
  },
  "timing.sector.competitor-last.s1": {
    label: "Competitor last S1",
    description: "Last completed sector 1 time for each competitor.",
    parentId: "timing.sector.competitor-last",
    canonicalUnit: "s",
    shape: "structured",
  },
  "timing.sector.competitor-last.s2": {
    label: "Competitor last S2",
    description: "Last completed sector 2 time for each competitor.",
    parentId: "timing.sector.competitor-last",
    canonicalUnit: "s",
    shape: "structured",
  },
  "timing.sector.competitor-last.s3": {
    label: "Competitor last S3",
    description: "Last completed sector 3 time for each competitor.",
    parentId: "timing.sector.competitor-last",
    canonicalUnit: "s",
    shape: "structured",
  },
  "race.competitor.position": {
    label: "Competitor position",
    description: "Overall running or classified position for each competitor.",
    parentId: "race.competitor.results",
    canonicalUnit: "count",
    shape: "structured",
  },
  "race.competitor.class-position": {
    label: "Competitor class position",
    description: "Class running or classified position for each competitor.",
    parentId: "race.competitor.results",
    canonicalUnit: "count",
    shape: "structured",
  },
  "race.competitor.driver-id": {
    label: "Competitor driver ID",
    description: "Source-specific driver identifier for each competitor.",
    parentId: "race.competitor.identity",
    canonicalUnit: "id",
    shape: "structured",
  },
  "race.competitor.driver-name": {
    label: "Competitor driver name",
    description: "Display name for each registered competitor.",
    parentId: "race.competitor.identity",
    canonicalUnit: "text",
    shape: "structured",
  },
  "race.competitor.team-id": {
    label: "Competitor team ID",
    description: "Source-specific team identifier for each competitor.",
    parentId: "race.competitor.identity",
    canonicalUnit: "id",
    shape: "structured",
  },
  "race.competitor.team-name": {
    label: "Competitor team name",
    description: "Team display name for each competitor.",
    parentId: "race.competitor.identity",
    canonicalUnit: "text",
    shape: "structured",
  },
  "race.competitor.car-index": {
    label: "Competitor car index",
    description: "Session-local car index used to join competitor arrays.",
    parentId: "race.competitor.identity",
    canonicalUnit: "index",
    shape: "structured",
  },
  "race.competitor.car-id": {
    label: "Competitor car ID",
    description: "Source-specific vehicle model identifier for each competitor.",
    parentId: "race.competitor.identity",
    canonicalUnit: "id",
    shape: "structured",
  },
  "race.competitor.car-name": {
    label: "Competitor car name",
    description: "Vehicle display name for each competitor.",
    parentId: "race.competitor.identity",
    canonicalUnit: "text",
    shape: "structured",
  },
  "race.competitor.car-class-id": {
    label: "Competitor car-class ID",
    description: "Source-specific vehicle class identifier for each competitor.",
    parentId: "race.competitor.identity",
    canonicalUnit: "id",
    shape: "structured",
  },
  "race.competitor.car-class-name": {
    label: "Competitor car-class name",
    description: "Vehicle class display name for each competitor.",
    parentId: "race.competitor.identity",
    canonicalUnit: "text",
    shape: "structured",
  },
  "timing.competitor.current-lap-time": {
    label: "Competitor current lap time",
    description: "Current lap elapsed time for each competitor.",
    parentId: "race.competitor.timing",
    canonicalUnit: "s",
    shape: "structured",
  },
  "timing.competitor.last-lap-time": {
    label: "Competitor last lap time",
    description: "Most recently completed lap time for each competitor.",
    parentId: "race.competitor.timing",
    canonicalUnit: "s",
    shape: "structured",
  },
  "timing.competitor.best-lap-time": {
    label: "Competitor best lap time",
    description: "Fastest completed lap time for each competitor.",
    parentId: "race.competitor.timing",
    canonicalUnit: "s",
    shape: "structured",
  },
  "timing.competitor.gap-to-leader": {
    label: "Competitor gap to leader",
    description: "Time or lap gap from each competitor to overall leader.",
    parentId: "race.competitor.timing",
    canonicalUnit: "s",
    shape: "structured",
  },
};

export { SEMANTIC_DEFINITIONS_LIVE };
