// Contiguous semantic definitions: extended and diagnostic channels.
import { semanticDefinition } from "./semantic-metadata";
import type { SemanticDefinition } from "./model";

const SEMANTIC_DEFINITIONS_EXTENDED: Record<string, SemanticDefinition> = {
  "race.competitor.class-power-adjust": semanticDefinition(
    "Competitor class power adjustment",
    "Balance-of-performance power adjustment for each competitor car class.",
    "race.competitor.identity",
    "%",
    "structured",
  ),
  "race.competitor.class-relative-speed": semanticDefinition(
    "Competitor class relative speed",
    "Relative speed factor for each competitor car class.",
    "race.competitor.identity",
    "ratio",
    "structured",
  ),
  "race.competitor.class-weight-penalty": semanticDefinition(
    "Competitor class weight penalty",
    "Balance-of-performance weight penalty for each competitor car class.",
    "race.competitor.identity",
    "kg",
    "structured",
  ),
  "race.competitor.class-dry-tire-set-limit": semanticDefinition(
    "Competitor class dry-tire set limit",
    "Dry-tire set limit for each competitor car class.",
    "race.competitor.identity",
    "count",
    "structured",
  ),
  "race.competitor.car-design": semanticDefinition(
    "Competitor car design",
    "Source livery or car-design descriptor for each competitor.",
    "race.competitor.identity",
    "text",
    "structured",
  ),
  "race.competitor.car-number-design": semanticDefinition(
    "Competitor car-number design",
    "Source car-number styling descriptor for each competitor.",
    "race.competitor.identity",
    "text",
    "structured",
  ),
  "race.competitor.helmet-design": semanticDefinition(
    "Competitor helmet design",
    "Source helmet-design descriptor for each competitor.",
    "race.competitor.identity",
    "text",
    "structured",
  ),
  "race.competitor.suit-design": semanticDefinition(
    "Competitor suit design",
    "Source driver-suit design descriptor for each competitor.",
    "race.competitor.identity",
    "text",
    "structured",
  ),
  "race.competitor.primary-sponsor": semanticDefinition(
    "Competitor primary sponsor",
    "Primary sponsor identifier for each competitor.",
    "race.competitor.identity",
    "text",
    "structured",
  ),
  "race.competitor.secondary-sponsor": semanticDefinition(
    "Competitor secondary sponsor",
    "Secondary sponsor identifier for each competitor.",
    "race.competitor.identity",
    "text",
    "structured",
  ),
  "session.schedule.names": {
    label: "Session schedule names",
    description: "Names of sessions in current event schedule.",
    parentId: "session",
    canonicalUnit: "text",
    shape: "structured",
  },
  "session.schedule.numbers": {
    label: "Session schedule numbers",
    description: "Source session numbers for current event schedule.",
    parentId: "session",
    canonicalUnit: "count",
    shape: "structured",
  },
  "identity.camera-focus-car-index": semanticDefinition(
    "Camera focus car index",
    "Vehicle index currently targeted by active simulator camera.",
    "identity",
    "index",
  ),
  "diagnostics.radio.transmitting-car-index": semanticDefinition(
    "Radio transmitting car index",
    "Vehicle index associated with person currently transmitting on radio.",
    "diagnostics.radio",
    "index",
  ),
  "race.competitor.fast-repairs-used": semanticDefinition(
    "Competitor fast repairs used",
    "Count of fast repairs consumed by each competitor.",
    "race.competitor.results",
    "count",
    "structured",
  ),
  "race.competitor.push-to-pass-count": semanticDefinition(
    "Competitor push-to-pass count",
    "Push-to-pass uses consumed or remaining for each competitor, according to session rules.",
    "race.competitor.results",
    "count",
    "structured",
  ),
  "race.competitor.push-to-pass-active": semanticDefinition(
    "Competitor push-to-pass active",
    "Whether push-to-pass is active for each competitor.",
    "race.competitor.results",
    "boolean",
    "structured",
  ),
  "race.competitor.pace-flags": semanticDefinition(
    "Competitor pacing flags",
    "Source pacing-state flags for each competitor.",
    "race.competitor.results",
    "bitfield",
    "structured",
  ),
  "race.competitor.pace-line": semanticDefinition(
    "Competitor pace line",
    "Pacing line assignment for each competitor, or source sentinel when not pacing.",
    "race.competitor.results",
    "index",
    "structured",
  ),
  "race.competitor.pace-row": semanticDefinition(
    "Competitor pace row",
    "Pacing row assignment for each competitor, or source sentinel when not pacing.",
    "race.competitor.results",
    "index",
    "structured",
  ),
  "tires.competitor.qualifying-compound": semanticDefinition(
    "Competitor qualifying tire compound",
    "Qualifying tire-compound code for each competitor.",
    "tires",
    "id",
    "structured",
  ),
  "tires.competitor.qualifying-compound-locked": semanticDefinition(
    "Competitor qualifying compound locked",
    "Whether qualifying tire compound is locked for each competitor.",
    "tires",
    "boolean",
    "structured",
  ),
  "race.competitor.session-flags": semanticDefinition(
    "Competitor session flags",
    "Session flag bitfield associated with each competitor.",
    "race.competitor.results",
    "bitfield",
    "structured",
  ),
  "race.competitor.track-location": semanticDefinition(
    "Competitor track location",
    "Track-location classification for each competitor.",
    "race.competitor.results",
    "enum",
    "structured",
  ),
  "race.competitor.track-surface-material": semanticDefinition(
    "Competitor track-surface material",
    "Surface-material classification beneath each competitor.",
    "race.competitor.results",
    "enum",
    "structured",
  ),
  "session.driver-change.drivers-used": semanticDefinition(
    "Team drivers used",
    "Count of team drivers who have completed a stint in current session.",
    "session",
    "count",
  ),
  "race.driver-change-lap-status": semanticDefinition(
    "Driver-change lap status",
    "Status of driver-change lap requirements.",
    "race",
    "enum",
  ),
  "inputs.starter-trigger": semanticDefinition(
    "Starter trigger",
    "In-car starter control trigger state.",
    "inputs",
    "boolean",
  ),
  "timing.delta-to-session-last-lap": semanticDefinition(
    "Delta to session last lap",
    "Current lap-time delta against session last-lap reference.",
    "timing",
    "s",
  ),
  "timing.delta-to-session-last-lap-rate": semanticDefinition(
    "Delta rate to session last lap",
    "Rate of change of lap-time delta against session last-lap reference.",
    "timing",
    "s/s",
  ),
  "timing.delta-to-session-last-lap-valid": semanticDefinition(
    "Delta to session last lap valid",
    "Whether session last-lap delta is currently valid.",
    "timing",
    "boolean",
  ),
  "timing.lap-delta-to-best-lap-rate": semanticDefinition(
    "Delta rate to best lap",
    "Rate of change of lap-time delta against player best lap.",
    "timing",
    "s/s",
  ),
  "timing.lap-delta-to-best-lap-valid": semanticDefinition(
    "Delta to best lap valid",
    "Whether lap-time delta against player best lap is valid.",
    "timing",
    "boolean",
  ),
  "timing.lap-delta-to-optimal-lap-rate": semanticDefinition(
    "Delta rate to optimal lap",
    "Rate of change of lap-time delta against player optimal lap.",
    "timing",
    "s/s",
  ),
  "timing.lap-delta-to-optimal-lap-valid": semanticDefinition(
    "Delta to optimal lap valid",
    "Whether lap-time delta against player optimal lap is valid.",
    "timing",
    "boolean",
  ),
  "timing.lap-delta-to-session-best-lap-rate": semanticDefinition(
    "Delta rate to session best lap",
    "Rate of change of lap-time delta against session best lap.",
    "timing",
    "s/s",
  ),
  "timing.lap-delta-to-session-best-lap-valid": semanticDefinition(
    "Delta to session best lap valid",
    "Whether lap-time delta against session best lap is valid.",
    "timing",
    "boolean",
  ),
  "timing.lap-delta-to-session-optimal-lap-rate": semanticDefinition(
    "Delta rate to session optimal lap",
    "Rate of change of lap-time delta against session optimal lap.",
    "timing",
    "s/s",
  ),
  "timing.lap-delta-to-session-optimal-lap-valid": semanticDefinition(
    "Delta to session optimal lap valid",
    "Whether lap-time delta against session optimal lap is valid.",
    "timing",
    "boolean",
  ),
  "timing.n-lap-average.clean-lap-count": semanticDefinition(
    "N-lap average clean-lap count",
    "Consecutive clean laps completed toward current N-lap average.",
    "timing",
    "count",
  ),
  "timing.n-lap-average.current-time": semanticDefinition(
    "Current N-lap average time",
    "Player current rolling N-lap average time.",
    "timing",
    "s",
  ),
  "timing.n-lap-average.best-ending-lap": semanticDefinition(
    "Best N-lap average ending lap",
    "Last lap number included in player best N-lap average.",
    "timing",
    "count",
  ),
  "timing.n-lap-average.best-time": semanticDefinition(
    "Best N-lap average time",
    "Player best N-lap average time.",
    "timing",
    "s",
  ),
  "timing.best-lap-number": semanticDefinition(
    "Best lap number",
    "Lap number containing player best completed lap time.",
    "timing",
    "count",
  ),
  "timing.last-completed-lap-number": semanticDefinition(
    "Last completed lap number",
    "Most recent lap number completed by player.",
    "timing",
    "count",
  ),
  "session.laps-remaining": semanticDefinition(
    "Session laps remaining",
    "Number of laps remaining before current session ends.",
    "session",
    "count",
  ),
  "diagnostics.car-number-texture-loading": semanticDefinition(
    "Car-number texture loading",
    "Whether simulator will load car-number texture assets.",
    "diagnostics",
    "boolean",
  ),
  "diagnostics.texture-reload-allowed": semanticDefinition(
    "Texture reload allowed",
    "Whether car textures may be reloaded at current time.",
    "diagnostics",
    "boolean",
  ),
  "race.player.push-to-pass-count": semanticDefinition(
    "Player push-to-pass count",
    "Push-to-pass uses consumed or remaining for player car, according to session rules.",
    "race",
    "count",
  ),
  "race.player.push-to-pass-active": semanticDefinition(
    "Player push-to-pass active",
    "Whether push-to-pass is active on player car.",
    "race",
    "boolean",
  ),
  "session.session-flags": semanticDefinition(
    "Session flags",
    "Native race-control flag bitfield for the current iRacing session.",
    "session",
    "bitfield",
  ),
  "session.session-state": semanticDefinition(
    "Session state code",
    "Native numeric current-session state code.",
    "session",
    "count",
  ),
  "race.pit-service.status": semanticDefinition(
    "Pit-service status",
    "Current player-car pit-service status flags.",
    "race.pit-service",
    "bitfield",
  ),
  "race.pit-service.flags": semanticDefinition(
    "Requested pit-service flags",
    "Bitfield of requested pit-service actions.",
    "race.pit-service",
    "bitfield",
  ),
  "race.pit-service.fuel-add-amount": semanticDefinition(
    "Pit-service fuel add amount",
    "Fuel or battery energy requested at next pit service.",
    "race.pit-service",
    "L or kWh",
  ),
  "race.pit-service.tire-pressure": semanticDefinition(
    "Requested pit-service tire pressure",
    "Cold pressure requested for each tire at next pit service.",
    "race.pit-service",
    "kPa",
    "per-wheel",
  ),
  "race.pit-service.tire-compound": semanticDefinition(
    "Requested pit-service tire compound",
    "Tire-compound code requested at next pit service.",
    "race.pit-service",
    "id",
  ),
  "race.pit-service.mandatory-repair-time-remaining": semanticDefinition(
    "Mandatory repair time remaining",
    "Mandatory pit-repair time remaining while repairs are active.",
    "race.pit-service",
    "s",
  ),
  "race.pit-service.optional-repair-time-remaining": semanticDefinition(
    "Optional repair time remaining",
    "Optional pit-repair time remaining while repairs are active.",
    "race.pit-service",
    "s",
  ),
  "diagnostics.camera.group-name": semanticDefinition(
    "Camera group name",
    "Display name of each simulator camera group.",
    "diagnostics.camera",
    "text",
    "structured",
  ),
  "diagnostics.camera.active-camera-number": semanticDefinition(
    "Active camera number",
    "Source number identifying active simulator camera.",
    "diagnostics.camera",
    "index",
  ),
  "diagnostics.camera.active-group-number": semanticDefinition(
    "Active camera group number",
    "Source number identifying active simulator camera group.",
    "diagnostics.camera",
    "index",
  ),
  "diagnostics.camera.state-flags": semanticDefinition(
    "Camera state flags",
    "Bitfield describing active simulator camera system state.",
    "diagnostics.camera",
    "bitfield",
  ),
  "diagnostics.camera.group-number": semanticDefinition(
    "Camera group number",
    "Source number identifying each simulator camera group.",
    "diagnostics.camera",
    "index",
    "structured",
  ),
  "diagnostics.camera.group-scenic": semanticDefinition(
    "Camera group scenic",
    "Whether each simulator camera group is scenic.",
    "diagnostics.camera",
    "boolean",
    "structured",
  ),
  "diagnostics.camera.name": semanticDefinition(
    "Camera name",
    "Display name of each camera definition.",
    "diagnostics.camera",
    "text",
    "structured",
  ),
  "diagnostics.camera.number": semanticDefinition(
    "Camera number",
    "Source number identifying each camera definition.",
    "diagnostics.camera",
    "index",
    "structured",
  ),
  "diagnostics.radio.selected-radio-number": semanticDefinition(
    "Selected radio number",
    "Source radio number currently selected by player.",
    "diagnostics.radio",
    "index",
  ),
  "diagnostics.radio.hop-count": semanticDefinition(
    "Radio hop count",
    "Hop count configured for each simulator radio.",
    "diagnostics.radio",
    "count",
    "structured",
  ),
  "diagnostics.radio.frequency-count": semanticDefinition(
    "Radio frequency count",
    "Number of frequency entries configured for each simulator radio.",
    "diagnostics.radio",
    "count",
    "structured",
  ),
  "diagnostics.radio.number": semanticDefinition(
    "Radio number",
    "Source number identifying each simulator radio.",
    "diagnostics.radio",
    "index",
    "structured",
  ),
  "diagnostics.radio.scanning": semanticDefinition(
    "Radio scanning",
    "Whether scanning is active for each simulator radio.",
    "diagnostics.radio",
    "boolean",
    "structured",
  ),
  "diagnostics.radio.tuned-frequency-number": semanticDefinition(
    "Tuned frequency number",
    "Frequency number currently tuned on each simulator radio.",
    "diagnostics.radio",
    "index",
    "structured",
  ),
  "diagnostics.radio.frequency-can-scan": semanticDefinition(
    "Radio frequency can scan",
    "Whether each frequency entry can participate in scanning.",
    "diagnostics.radio",
    "boolean",
    "structured",
  ),
  "diagnostics.radio.frequency-can-squawk": semanticDefinition(
    "Radio frequency can transmit",
    "Whether player can transmit on each frequency entry.",
    "diagnostics.radio",
    "boolean",
    "structured",
  ),
  "diagnostics.radio.frequency-club-id": semanticDefinition(
    "Radio frequency club ID",
    "Club identifier associated with each frequency entry.",
    "diagnostics.radio",
    "id",
    "structured",
  ),
  "diagnostics.radio.frequency-entry-index": semanticDefinition(
    "Radio frequency entry index",
    "Source index identifying each frequency entry.",
    "diagnostics.radio",
    "index",
    "structured",
  ),
  "diagnostics.radio.frequency-name": semanticDefinition(
    "Radio frequency name",
    "Display name of each frequency entry.",
    "diagnostics.radio",
    "text",
    "structured",
  ),
  "diagnostics.radio.frequency-number": semanticDefinition(
    "Radio frequency number",
    "Source number identifying each frequency entry.",
    "diagnostics.radio",
    "index",
    "structured",
  ),
  "diagnostics.radio.frequency-deletable": semanticDefinition(
    "Radio frequency deletable",
    "Whether each frequency entry may be deleted.",
    "diagnostics.radio",
    "boolean",
    "structured",
  ),
  "diagnostics.radio.frequency-mutable": semanticDefinition(
    "Radio frequency mutable",
    "Whether each frequency entry may be edited.",
    "diagnostics.radio",
    "boolean",
    "structured",
  ),
  "diagnostics.radio.frequency-muted": semanticDefinition(
    "Radio frequency muted",
    "Whether each frequency entry is muted.",
    "diagnostics.radio",
    "boolean",
    "structured",
  ),
  "diagnostics.radio.frequency-priority": semanticDefinition(
    "Radio frequency priority",
    "Priority assigned to each frequency entry.",
    "diagnostics.radio",
    "count",
    "structured",
  ),
  "diagnostics.radio.transmitting-frequency-index": semanticDefinition(
    "Transmitting radio frequency index",
    "Frequency index used by person currently transmitting on radio.",
    "diagnostics.radio",
    "index",
  ),
  "diagnostics.radio.transmitting-radio-index": semanticDefinition(
    "Transmitting radio index",
    "Radio index used by person currently transmitting on radio.",
    "diagnostics.radio",
    "index",
  ),
  "diagnostics.radio.frequency-car-index": {
    label: "Radio frequency car index",
    description: "Vehicle index associated with each radio frequency entry.",
    parentId: "diagnostics.radio",
    canonicalUnit: "index",
    shape: "structured",
  },
};

export { SEMANTIC_DEFINITIONS_EXTENDED };
