// Contiguous semantic definitions: competitor and timing channels.
import { semanticDefinition } from "./semantic-metadata";
import type { SemanticDefinition } from "./model";

const SEMANTIC_DEFINITIONS_COMPETITOR: Record<string, SemanticDefinition> = {
  "timing.competitor.gap-to-ahead": {
    label: "Competitor gap to car ahead",
    description: "Time or lap gap from each competitor to car directly ahead.",
    parentId: "race.competitor.timing",
    canonicalUnit: "s",
    shape: "structured",
  },
  "timing.competitor.current-lap-number": {
    label: "Competitor current lap number",
    description: "Current or last-crossed lap number for each competitor.",
    parentId: "race.competitor.timing",
    canonicalUnit: "count",
    shape: "structured",
  },
  "timing.competitor.best-lap-number": {
    label: "Competitor best lap number",
    description: "Lap number on which each competitor set fastest time.",
    parentId: "race.competitor.timing",
    canonicalUnit: "count",
    shape: "structured",
  },
  "timing.competitor.total-time": {
    label: "Competitor session time",
    description: "Elapsed or classified session time for each competitor.",
    parentId: "race.competitor.timing",
    canonicalUnit: "s",
    shape: "structured",
  },
  "race.competitor.pit-status": {
    label: "Competitor pit status",
    description: "Current pit state for each competitor.",
    parentId: "race.competitor.results",
    canonicalUnit: "enum",
    shape: "structured",
    valueType: "string",
  },
  "race.competitor.pit-stops": {
    label: "Competitor pit-stop count",
    description: "Completed pit-stop count for each competitor.",
    parentId: "race.competitor.results",
    canonicalUnit: "count",
    shape: "structured",
  },
  "race.competitor.penalties": {
    label: "Competitor penalties",
    description: "Accumulated penalty value for each competitor.",
    parentId: "race.competitor.results",
    canonicalUnit: "count",
    shape: "structured",
  },
  "race.competitor.incidents": {
    label: "Competitor incidents",
    description: "Incident count for each competitor.",
    parentId: "race.competitor.results",
    canonicalUnit: "count",
    shape: "structured",
  },
  "race.competitor.laps-complete": {
    label: "Competitor laps complete",
    description: "Completed lap count for each competitor.",
    parentId: "race.competitor.results",
    canonicalUnit: "count",
    shape: "structured",
  },
  "race.competitor.laps-led": {
    label: "Competitor laps led",
    description: "Number of laps led by each competitor.",
    parentId: "race.competitor.results",
    canonicalUnit: "count",
    shape: "structured",
  },
  "tires.competitor.compound": {
    label: "Competitor tire compound",
    description: "Current or classified tire compound for each competitor.",
    parentId: "race.competitor.results",
    canonicalUnit: "text",
    shape: "structured",
  },
  "tires.competitor.age": {
    label: "Competitor tire age",
    description: "Current tire stint age for each competitor.",
    parentId: "race.competitor.results",
    canonicalUnit: "count",
    shape: "structured",
  },
  "inputs.competitor.gear": {
    label: "Competitor gear",
    description: "Current transmission gear for each competitor.",
    parentId: "race.competitor.timing",
    canonicalUnit: "index",
    shape: "structured",
  },
  "engine.competitor-rpm": {
    label: "Competitor engine RPM",
    description: "Current engine speed for each competitor.",
    parentId: "race.competitor.timing",
    canonicalUnit: "rpm",
    shape: "structured",
  },
  "inputs.competitor-steering-angle": {
    label: "Competitor steering angle",
    description: "Current steering-wheel angle for each competitor.",
    parentId: "race.competitor.timing",
    canonicalUnit: "rad",
    shape: "structured",
  },
  "timing.competitor.lap-fraction": {
    label: "Competitor lap fraction",
    description: "Current distance around lap for each competitor.",
    parentId: "race.competitor.timing",
    canonicalUnit: "fraction",
    shape: "structured",
  },
  "timing.lap-fraction": {
    label: "Lap fraction",
    description: "Current distance around lap on normalized 0-1 scale.",
    parentId: "timing",
    canonicalUnit: "fraction",
    shape: "scalar",
  },
  "identity.player-car-index": {
    label: "Player car index",
    description: "Source index identifying current player vehicle.",
    parentId: "identity",
    canonicalUnit: "index",
    shape: "scalar",
  },
  "identity.player-driver-id": {
    label: "Player driver ID",
    description: "Source account identifier for current player driver.",
    parentId: "identity",
    canonicalUnit: "id",
    shape: "scalar",
  },
  "identity.player-car-version": {
    label: "Player car version",
    description: "Source version identifier for current player vehicle definition.",
    parentId: "identity",
    canonicalUnit: "text",
    shape: "scalar",
  },
  "race.pace-car-index": {
    label: "Pace-car index",
    description: "Source vehicle index identifying pace or safety car.",
    parentId: "race",
    canonicalUnit: "index",
    shape: "scalar",
  },
  "race.pit-stall-lap-fraction": {
    label: "Pit-stall lap fraction",
    description: "Lap fraction where player pit stall is located.",
    parentId: "race",
    canonicalUnit: "fraction",
    shape: "scalar",
  },
  "motion.driver-head-position.x": {
    label: "Driver head position X",
    description: "Driver head position on source X axis.",
    parentId: "motion.driver-head-position",
    canonicalUnit: "m",
    shape: "scalar",
  },
  "motion.driver-head-position.y": {
    label: "Driver head position Y",
    description: "Driver head position on source Y axis.",
    parentId: "motion.driver-head-position",
    canonicalUnit: "m",
    shape: "scalar",
  },
  "motion.driver-head-position.z": {
    label: "Driver head position Z",
    description: "Driver head position on source Z axis.",
    parentId: "motion.driver-head-position",
    canonicalUnit: "m",
    shape: "scalar",
  },
  "identity.player-car-class-id": {
    label: "Player car-class ID",
    description: "Source class identifier for current player vehicle.",
    parentId: "identity",
    canonicalUnit: "id",
    shape: "scalar",
    valueType: "string",
  },
  "race.player-class-position": {
    label: "Player class position",
    description: "Current player position within vehicle class.",
    parentId: "race",
    canonicalUnit: "count",
    shape: "scalar",
  },
  "race.pit-speed-limit": {
    label: "Pit speed limit",
    description: "Configured pit-lane speed limit.",
    parentId: "race",
    canonicalUnit: "km/h",
    shape: "scalar",
  },
  "race.incident-flags": {
    label: "Player incident flags",
    description: "Native incident event bit flags reported for current player.",
    parentId: "race",
    canonicalUnit: "flags",
    shape: "scalar",
  },
  "race.player-incident-count": {
    label: "Player incident count",
    description: "Incident points assigned personally to current player.",
    parentId: "race",
    canonicalUnit: "count",
    shape: "scalar",
  },
  "race.driver-incident-count": {
    label: "Current-driver incident count",
    description: "Incident points assigned to current driver in team session.",
    parentId: "race",
    canonicalUnit: "count",
    shape: "scalar",
  },
  "race.team-incident-count": {
    label: "Team incident count",
    description: "Incident points assigned to current player team.",
    parentId: "race",
    canonicalUnit: "count",
    shape: "scalar",
  },
  "session.session-id": {
    label: "Session ID",
    description: "Native event-session identifier.",
    parentId: "session",
    canonicalUnit: "id",
    shape: "scalar",
  },
  "session.subsession-id": {
    label: "Subsession ID",
    description: "Native subsession or server-instance identifier.",
    parentId: "session",
    canonicalUnit: "id",
    shape: "scalar",
  },
  "tires.wheel-linear-speed": {
    label: "Wheel linear speed",
    description: "Per-wheel linear tread speed before radius conversion.",
    parentId: "tires",
    canonicalUnit: "m/s",
    shape: "per-wheel",
  },
  "tires.wheel-force.lateral": {
    label: "Lateral wheel force",
    description: "Per-wheel lateral tire force.",
    parentId: "tires",
    canonicalUnit: "N",
    shape: "per-wheel",
  },
  "tires.wheel-force.longitudinal": {
    label: "Longitudinal wheel force",
    description: "Per-wheel longitudinal tire force.",
    parentId: "tires",
    canonicalUnit: "N",
    shape: "per-wheel",
  },
  "tires.wheel-force.vertical": {
    label: "Vertical wheel force",
    description: "Per-wheel vertical tire load reported by source.",
    parentId: "tires",
    canonicalUnit: "N",
    shape: "per-wheel",
  },
  "tires.tire-slip-angle": {
    label: "Tire slip angle",
    description: "Per-wheel angular difference between wheel heading and travel direction.",
    parentId: "tires",
    canonicalUnit: "rad",
    shape: "per-wheel",
  },
  "tires.normalized-tire-slip-angle": {
    label: "Normalized tire slip-angle signal",
    description:
      "Per-wheel source-normalized lateral slip signal; not a physical angle and not directly convertible to radians.",
    parentId: "tires",
    canonicalUnit: "ratio",
    shape: "per-wheel",
  },
  "suspension.cg-height": {
    label: "Center-of-gravity height",
    description: "Vehicle center-of-gravity height above ground.",
    parentId: "suspension",
    canonicalUnit: "m",
    shape: "scalar",
  },
  "inputs.front-wheel-angle": {
    label: "Front wheel angle",
    description: "Physical front-wheel steering angle.",
    parentId: "inputs",
    canonicalUnit: "rad",
    shape: "scalar",
  },
  "motion.velocity-x": {
    label: "Velocity X",
    description: "Vehicle velocity on RaceIQ X axis.",
    parentId: "motion",
    canonicalUnit: "m/s",
    shape: "scalar",
  },
  "motion.velocity-y": {
    label: "Velocity Y",
    description: "Vehicle velocity on RaceIQ Y axis.",
    parentId: "motion",
    canonicalUnit: "m/s",
    shape: "scalar",
  },
  "motion.velocity-z": {
    label: "Velocity Z",
    description: "Vehicle velocity on RaceIQ Z axis.",
    parentId: "motion",
    canonicalUnit: "m/s",
    shape: "scalar",
  },
  "tires.wheel-rotation-speed": {
    label: "Wheel rotation speed",
    description: "Per-wheel angular velocity.",
    parentId: "tires",
    canonicalUnit: "rad/s",
    shape: "per-wheel",
  },
  "tires.tire-combined-slip": {
    label: "Tire combined slip",
    description: "Per-wheel combined slip magnitude.",
    parentId: "tires",
    canonicalUnit: "ratio",
    shape: "per-wheel",
  },
  "tires.surface-rumble": {
    label: "Surface rumble",
    description: "Per-wheel force-feedback surface-rumble intensity.",
    parentId: "tires",
    canonicalUnit: "unitless",
    shape: "per-wheel",
  },
  "timing.competitor.estimated-time": {
    label: "Competitor estimated lap-position time",
    description: "Estimated session time at each competitor's current track location.",
    parentId: "race.competitor.timing",
    canonicalUnit: "s",
    shape: "structured",
  },
  "weather.wind-speed": {
    label: "Current wind speed",
    description: "Current ambient wind speed.",
    parentId: "weather",
    canonicalUnit: "m/s",
    shape: "scalar",
  },
  "weather.wind-direction": {
    label: "Current wind direction",
    description: "Current ambient wind direction.",
    parentId: "weather",
    canonicalUnit: "deg",
    shape: "scalar",
  },
  "weather.fog-level": {
    label: "Current fog level",
    description: "Current ambient fog level.",
    parentId: "weather",
    canonicalUnit: "%",
    shape: "scalar",
  },
  "weather.air-pressure": {
    label: "Current air pressure",
    description: "Current ambient atmospheric pressure.",
    parentId: "weather",
    canonicalUnit: "kPa",
    shape: "scalar",
  },
  "weather.track-cleanup-mode": {
    label: "Track cleanup mode",
    description: "Configured cleanup behavior for accumulated track state.",
    parentId: "weather",
    canonicalUnit: "text",
    shape: "scalar",
  },
  "weather.dynamic-track-mode": {
    label: "Dynamic track mode",
    description: "Configured dynamic-track behavior for session.",
    parentId: "weather",
    canonicalUnit: "text",
    shape: "scalar",
  },
  "weather.relative-humidity": {
    label: "Current relative humidity",
    description: "Current ambient relative humidity.",
    parentId: "weather",
    canonicalUnit: "%",
    shape: "scalar",
  },
  "weather.skies": {
    label: "Current skies",
    description: "Current sky-condition category.",
    parentId: "weather",
    canonicalUnit: "enum",
    shape: "scalar",
  },
  "weather.weather-type": {
    label: "Current weather type",
    description: "Current source weather-condition category.",
    parentId: "weather",
    canonicalUnit: "enum",
    shape: "scalar",
  },
  "weather.configured.fog-level": {
    label: "Configured fog level",
    description: "Session weather configuration for fog level.",
    parentId: "weather.configured",
    canonicalUnit: "%",
    shape: "scalar",
  },
  "weather.configured.relative-humidity": {
    label: "Configured relative humidity",
    description: "Session weather configuration for relative humidity.",
    parentId: "weather.configured",
    canonicalUnit: "%",
    shape: "scalar",
  },
  "weather.configured.skies": {
    label: "Configured skies",
    description: "Session weather configuration for sky conditions.",
    parentId: "weather.configured",
    canonicalUnit: "text",
    shape: "scalar",
  },
  "weather.configured.temperature": {
    label: "Configured weather temperature",
    description: "Session weather configuration for ambient temperature.",
    parentId: "weather.configured",
    canonicalUnit: "°C",
    shape: "scalar",
  },
  "weather.configured.weather-type": {
    label: "Configured weather type",
    description: "Session weather generation mode or weather type.",
    parentId: "weather.configured",
    canonicalUnit: "text",
    shape: "scalar",
  },
  "weather.configured.wind-direction": {
    label: "Configured wind direction",
    description: "Session weather configuration for wind direction.",
    parentId: "weather.configured",
    canonicalUnit: "deg",
    shape: "scalar",
  },
  "weather.configured.wind-speed": {
    label: "Configured wind speed",
    description: "Session weather configuration for wind speed.",
    parentId: "weather.configured",
    canonicalUnit: "m/s",
    shape: "scalar",
  },
  "race.competitor.driver-incident-count": {
    label: "Competitor current-driver incident count",
    description: "Current-driver incident points for each competitor entry.",
    parentId: "race.competitor.results",
    canonicalUnit: "count",
    shape: "structured",
  },
  "race.competitor.team-incident-count": {
    label: "Competitor team incident count",
    description: "Team incident points for each competitor entry.",
    parentId: "race.competitor.results",
    canonicalUnit: "count",
    shape: "structured",
  },
  "race.competitor.driver-abbreviated-name": semanticDefinition(
    "Competitor abbreviated name",
    "Abbreviated display name for each competitor.",
    "race.competitor.identity",
    "text",
    "structured",
  ),
  "race.competitor.driver-initials": semanticDefinition(
    "Competitor initials",
    "Driver initials for each competitor.",
    "race.competitor.identity",
    "text",
    "structured",
  ),
  "race.competitor.rating": semanticDefinition(
    "Competitor rating",
    "Source skill or matchmaking rating for each competitor.",
    "race.competitor.identity",
    "count",
    "structured",
  ),
  "race.competitor.license-level": semanticDefinition(
    "Competitor license level",
    "Source license level for each competitor.",
    "race.competitor.identity",
    "count",
    "structured",
  ),
  "race.competitor.license-sublevel": semanticDefinition(
    "Competitor license sublevel",
    "Source license progression sublevel for each competitor.",
    "race.competitor.identity",
    "count",
    "structured",
  ),
  "race.competitor.license-name": semanticDefinition(
    "Competitor license name",
    "Source display string for each competitor license.",
    "race.competitor.identity",
    "text",
    "structured",
  ),
  "race.competitor.license-color": semanticDefinition(
    "Competitor license color",
    "Source display color for each competitor license.",
    "race.competitor.identity",
    "color",
    "structured",
  ),
  "race.competitor.club-name": semanticDefinition(
    "Competitor club name",
    "Club or regional affiliation for each competitor.",
    "race.competitor.identity",
    "text",
    "structured",
  ),
  "race.competitor.division-name": semanticDefinition(
    "Competitor division name",
    "Competition division for each competitor.",
    "race.competitor.identity",
    "text",
    "structured",
  ),
  "race.competitor.is-spectator": semanticDefinition(
    "Competitor spectator status",
    "Whether each registered competitor entry is spectating.",
    "race.competitor.identity",
    "boolean",
    "structured",
  ),
  "race.competitor.car-number": semanticDefinition(
    "Competitor car number",
    "Displayed car number for each competitor.",
    "race.competitor.identity",
    "text",
    "structured",
  ),
  "race.competitor.car-number-raw": semanticDefinition(
    "Competitor raw car number",
    "Unformatted source car-number value for each competitor.",
    "race.competitor.identity",
    "text",
    "structured",
  ),
  "race.competitor.car-path": semanticDefinition(
    "Competitor car path",
    "Source vehicle-definition path for each competitor.",
    "race.competitor.identity",
    "text",
    "structured",
  ),
  "race.competitor.is-ai": semanticDefinition(
    "Competitor AI status",
    "Whether each competitor is controlled by simulator AI.",
    "race.competitor.identity",
    "boolean",
    "structured",
  ),
  "race.competitor.is-pace-car": semanticDefinition(
    "Competitor pace-car status",
    "Whether each competitor entry represents pace or safety car.",
    "race.competitor.identity",
    "boolean",
    "structured",
  ),
  "race.competitor.car-class-color": semanticDefinition(
    "Competitor car-class color",
    "Source display color for each competitor car class.",
    "race.competitor.identity",
    "color",
    "structured",
  ),
  "race.competitor.car-class-license-level": semanticDefinition(
    "Competitor class license level",
    "Required or assigned license level for each competitor car class.",
    "race.competitor.identity",
    "count",
    "structured",
  ),
  "race.competitor.class-max-fuel-percentage": semanticDefinition(
    "Competitor class maximum fuel percentage",
    "Maximum allowed fuel percentage for each competitor car class.",
    "race.competitor.identity",
    "%",
    "structured",
  ),
  "timing.competitor.last-lap-valid": semanticDefinition(
    "Competitor last-lap validity",
    "Whether each competitor's most recently completed lap is valid.",
    "race.competitor.timing",
    "boolean",
    "structured",
  ),
};

export { SEMANTIC_DEFINITIONS_COMPETITOR };
