import { z } from "zod";
import { autoTrackSegments } from "../../../shared/racing/tracks/curation/generate";
import type { NamedSegment } from "../../../shared/racing/tracks/named-segments";
import { getLapSummariesByTrack, getLapById } from "../../db/lap-read-queries";
import { getTrackOutline as getDbTrackOutline } from "../../db/track-queries";
import {
  getTrackOutlineByOrdinal,
  getRecordedOutlineByOrdinal,
  recordLapTrace,
} from "../../../shared/racing/tracks/recording/outlines";
import { loadLabelledSegments } from "../../../shared/racing/tracks/storage/meta";
import { loadSharedOutline } from "../../../shared/racing/tracks/geometry/shared";
import { applyAlignment, computeAlignment } from "../../../shared/racing/tracks/geometry/points";
import { tryGetServerGame } from "../../games/registry";
import { tryGetGame } from "../../../shared/games/registry";
import {
  getIRacingOvalDirection,
  getIRacingTrack,
} from "../../../shared/racing/tracks/catalogs/iracing";
import { GameIdSchema, type GameId } from "../../../shared/games/ids";
import { getIRacingSvgTrackMap } from "../../games/iracing/track-map";
import {
  alignIRacingAutoSegmentsToTurnLabels,
  projectIRacingTurnAnchors,
  type IRacingMapLabel,
} from "../../games/iracing/track-map-svg";
import { lapPath } from "../../../shared/racing/tracks/path";

// ─── Param schemas ──────────────────────────────────────────────────────────

export const TrackOrdinalParamSchema = z.object({
  trackOrdinal: z.string().transform((val) => parseInt(val, 10)),
});

// ─── Helpers ────────────────────────────────────────────────────────────────

/** Extract gameId, throwing if missing. Use for endpoints that require game context. */
export function requireGameId(c: { req: { query: (key: string) => string | undefined } }): GameId {
  const raw = c.req.query("gameId");
  const result = GameIdSchema.safeParse(raw);
  if (!result.success) throw new Error(`Invalid gameId: ${raw}`);
  return result.data;
}

/** Sum dx/dz along an outline's points to get its total length in meters.
 *  Same computation used by GET /api/track-sector-boundaries/:ordinal. */
export function computeOutlineLength(
  outline: { x: number; z: number }[] | null | undefined,
): number {
  if (!outline || outline.length < 2) return 0;
  let length = 0;
  for (let i = 1; i < outline.length; i++) {
    const dx = outline[i].x - outline[i - 1].x;
    const dz = outline[i].z - outline[i - 1].z;
    length += Math.sqrt(dx * dx + dz * dz);
  }
  return length;
}

/** Resolve the shared track name for a given ordinal + gameId.
 *  Returns the shared outline file name (e.g. "silverstone") or undefined. */
export function getSharedTrackName(ordinal: number, gameId?: string): string | undefined {
  if (gameId) {
    const serverAdapter = tryGetServerGame(gameId);
    if (serverAdapter?.getSharedTrackName) {
      return serverAdapter.getSharedTrackName(ordinal);
    }
    const adapter = tryGetGame(gameId);
    if (adapter?.getSharedTrackName) return adapter.getSharedTrackName(ordinal);
  }
  return undefined;
}

export interface ResolvedTrackOutline {
  points: { x: number; z: number }[];
  labels: IRacingMapLabel[];
  /** Decorative official iRacing pit-road contours, never lap geometry. */
  pitRoad: { x: number; z: number }[][];
  recorded: boolean;
  source: "shared" | "official-svg" | "generated" | "bundled" | "recorded";
}

/**
 * Resolve one renderable outline in quality order. iRacing layouts are kept
 * exact by native TrackID: curated RaceIQ data first, then that layout's
 * official SVG, then a trace generated by RaceIQ's existing lap recorder.
 */
export async function resolveTrackOutline(
  ordinal: number,
  gameId: string,
): Promise<ResolvedTrackOutline | null> {
  const sharedName = getSharedTrackName(ordinal, gameId);

  if (gameId === "iracing") {
    const official = await getIRacingSvgTrackMap(ordinal);
    if (sharedName) {
      const shared = loadSharedOutline(sharedName);
      const labelledSegments = loadLabelledSegments(sharedName, "iracing");
      if (shared && labelledSegments.length > 0) {
        const alignment = official
          ? computeAlignment(official.points, shared)
          : null;
        return {
          points: shared,
          labels: [],
          pitRoad: official && alignment
            ? official.pitRoad.map((contour) =>
                contour.map((point) => applyAlignment(point, alignment)),
              )
            : [],
          recorded: false,
          source: "shared",
        };
      }
    }

    if (official) {
      return {
        ...official,
        recorded: false,
        source: "official-svg",
      };
    }

    const generated = getRecordedOutlineByOrdinal(ordinal, gameId);
    if (generated) {
      return {
        points: generated,
        labels: [],
        pitRoad: [],
        recorded: true,
        source: "generated",
      };
    }
  } else {
    const outline = getTrackOutlineByOrdinal(ordinal, gameId, sharedName);
    if (outline) {
      return {
        points: outline,
        labels: [],
        pitRoad: [],
        recorded: true,
        source: "bundled",
      };
    }
  }
  const dbOutline = await getDbTrackOutline(ordinal, gameId as GameId);
  if (dbOutline) {
    return {
      points: dbOutline,
      labels: [],
      pitRoad: [],
      recorded: true,
      source: "recorded",
    };
  }

  // Backfill the generated fallback for recordings made before iRacing live
  // map support landed. This still goes through recordLapTrace(), the same
  // existing generator used at live lap completion.
  if (gameId === "iracing") {
    const laps = await getLapSummariesByTrack(ordinal, "iracing");
    for (const lap of laps) {
      if (!lap.isValid) continue;
      const saved = await getLapById(lap.lapId);
      if (!saved?.telemetry || saved.telemetry.length < 50) continue;
      const path = lapPath(saved.telemetry);
      const trace = path.x.map((x, index) => ({
        x,
        z: path.z[index],
      }));
      recordLapTrace(
        ordinal,
        trace,
        trace[0] ?? null,
        saved.telemetry[0]?.Yaw ?? null,
        "iracing",
      );
      const generated = getRecordedOutlineByOrdinal(ordinal, "iracing");
      if (generated) {
        return {
          points: generated,
          labels: [],
          pitRoad: [],
          recorded: true,
          source: "generated",
        };
      }
    }
  }

  return null;
}

// ─── Segment resolution ─────────────────────────────────────────────────────

/**
 * The one place segment fractions come from. Curated shared-meta segments win;
 * otherwise the outline is run through the same auto-detector. Both
 * GET /api/track-sectors/:ordinal (track detail) and
 * GET /api/tracks/:trackOrdinal/corners (review dashboard / track focus) go
 * through here, so the two pages can never disagree about where a corner
 * starts and ends.
 */
export async function resolveTrackSegments(
  ordinal: number,
  gameId: string | undefined,
): Promise<{ segments: NamedSegment[]; totalDist: number; source: "shared" | "auto" | "none" }> {
  const slug = getSharedTrackName(ordinal, gameId);
  const metaSegments = slug && gameId ? loadLabelledSegments(slug, gameId) : [];
  if (metaSegments.length > 0) {
    return { segments: metaSegments, totalDist: 0, source: "shared" };
  }

  const resolved = gameId ? await resolveTrackOutline(ordinal, gameId) : null;
  const outline = resolved?.points ?? null;
  if (!outline || outline.length < 20) {
    return { segments: [], totalDist: 0, source: "none" };
  }
  const iracingTrack = gameId === "iracing" ? getIRacingTrack(ordinal) : undefined;
  const ovalDirection = gameId === "iracing" ? getIRacingOvalDirection(ordinal) : undefined;
  const isFourTurnOval =
    iracingTrack?.category.endsWith("oval") === true &&
    iracingTrack.cornersPerLap === 4;
  const ovalTurnAnchors =
    isFourTurnOval && resolved?.labels.length
      ? projectIRacingTurnAnchors(outline, resolved.labels)
      : [];
  const result = autoTrackSegments(
    outline,
    isFourTurnOval && ovalDirection
      ? { fourTurnOval: { direction: ovalDirection, turnAnchors: ovalTurnAnchors } }
      : {},
  );

  const segments =
    gameId === "iracing" && !isFourTurnOval && resolved?.labels.length
      ? alignIRacingAutoSegmentsToTurnLabels(result.segments, outline, resolved.labels)
      : result.segments;
  return {
    segments,
    totalDist: result.totalDist,
    source: "auto",
  };
}
