import { z } from "zod";
import { autoTrackSegments } from "../../../shared/racing/tracks/curation/generate";
import type { NamedSegment } from "../../../shared/racing/tracks/named-segments";
import { getLapSummariesByTrack, getLapById } from "../../db/lap-read-queries";
import { getTrackOutline as getDbTrackOutline } from "../../db/track-queries";
import { getTrackOutlineByOrdinal, getRecordedOutlineByOrdinal, recordLapTrace } from "../../../shared/racing/tracks/recording/outlines";
import { loadLabelledSegments } from "../../../shared/racing/tracks/storage/meta";
import { loadLegacyOutlineByOrdinal } from "../../../shared/racing/tracks/geometry/legacy";
import { applyAlignment, computeAlignment } from "../../../shared/racing/tracks/geometry/points";
import { getIRacingOvalDirection, getIRacingTrack } from "../../../shared/racing/tracks/catalogs/iracing";
import { GameIdSchema, type GameId } from "../../../shared/games/ids";
import { getIRacingSvgTrackMap } from "../../games/iracing/track-map";
import { alignIRacingAutoSegmentsToTurnLabels, projectIRacingTurnAnchors, type IRacingMapLabel, type IRacingPitLine } from "../../games/iracing/track-map-svg";
import { lapPath } from "../../../shared/racing/tracks/path";
import { loadCanonicalTrackPeer } from "../../tracks/configuration";
import { resolveTrackSharedName } from "../../tracks/identity";

// ─── Param schemas ──────────────────────────────────────────────────────────

export const TrackOrdinalParamSchema = z.object({
  trackOrdinal: z.string().transform((val) => parseInt(val, 10)),
});

// ─── Helpers ────────────────────────────────────────────────────────────────

/** Extract gameId, throwing if missing. Use for endpoints that require game context. */
export function requireGameId(c: { req: { query: (key: string) => string | undefined } }): GameId {
  const raw = c.req.query("gameId");
  const result = GameIdSchema.safeParse(raw);
  if (!result.success) throw new Error(`Invalid gameId: ${raw}`);
  return result.data;
}

/** Sum dx/dz along an outline's points to get its total length in meters.
 *  Same computation used by GET /api/track-sector-boundaries/:ordinal. */
export function computeOutlineLength(outline: { x: number; z: number }[] | null | undefined): number {
  if (!outline || outline.length < 2) return 0;
  let length = 0;
  for (let i = 1; i < outline.length; i++) {
    const dx = outline[i].x - outline[i - 1].x;
    const dz = outline[i].z - outline[i - 1].z;
    length += Math.sqrt(dx * dx + dz * dz);
  }
  return length;
}

/** Resolve the shared track name for a given ordinal + gameId.
 *  Returns the shared outline file name (e.g. "silverstone") or undefined. */
export function getSharedTrackName(ordinal: number, gameId?: string): string | undefined {
  return resolveTrackSharedName(ordinal, gameId);
}

export interface ResolvedTrackOutline {
  points: { x: number; z: number }[];
  labels: IRacingMapLabel[];
  /** Solid official iRacing pit-road and pit-exit centerlines. */
  pitLines: IRacingPitLine[];
  recorded: boolean;
  source: "shared" | "official-svg" | "generated" | "bundled" | "recorded";
}

/**
 * Resolve one renderable outline in quality order. iRacing layouts are kept
 * exact by native TrackID: curated RaceIQ data first, then that layout's
 * official SVG, then a trace generated by RaceIQ's existing lap recorder.
 */
export async function resolveTrackOutline(ordinal: number, gameId: string): Promise<ResolvedTrackOutline | null> {
  const sharedName = getSharedTrackName(ordinal, gameId);

  if (gameId === "iracing") {
    const official = await getIRacingSvgTrackMap(ordinal);
    if (sharedName) {
      const shared = loadLegacyOutlineByOrdinal(ordinal, "iracing");
      const labelledSegments = loadLabelledSegments(sharedName, "iracing");
      if (shared && labelledSegments.length > 0) {
        const alignment = official ? computeAlignment(official.points, shared) : null;
        return {
          points: shared,
          labels: [],
          pitLines:
            official && alignment
              ? official.pitLines.map((line) => ({
                  ...line,
                  points: line.points.map((point) => applyAlignment(point, alignment)),
                }))
              : [],
          recorded: false,
          source: "shared",
        };
      }
    }

    if (official) {
      return {
        ...official,
        recorded: false,
        source: "official-svg",
      };
    }

    const generated = getRecordedOutlineByOrdinal(ordinal, gameId);
    if (generated) {
      return {
        points: generated,
        labels: [],
        pitLines: [],
        recorded: true,
        source: "generated",
      };
    }
  } else {
    const outline = getTrackOutlineByOrdinal(ordinal, gameId);
    if (outline) {
      return {
        points: outline,
        labels: [],
        pitLines: [],
        recorded: true,
        source: "bundled",
      };
    }
  }
  const dbOutline = await getDbTrackOutline(ordinal, gameId as GameId);
  if (dbOutline) {
    return {
      points: dbOutline,
      labels: [],
      pitLines: [],
      recorded: true,
      source: "recorded",
    };
  }

  // Backfill the generated fallback for recordings made before iRacing live
  // map support landed. This still goes through recordLapTrace(), the same
  // existing generator used at live lap completion.
  if (gameId === "iracing") {
    const laps = await getLapSummariesByTrack(ordinal, "iracing");
    for (const lap of laps) {
      if (!lap.isValid) continue;
      const saved = await getLapById(lap.lapId);
      if (!saved?.telemetry || saved.telemetry.length < 50) continue;
      const path = lapPath(saved.telemetry);
      const trace = path.x.map((x, index) => ({
        x,
        z: path.z[index],
      }));
      recordLapTrace(ordinal, trace, trace[0] ?? null, saved.telemetry[0]?.Yaw ?? null, "iracing");
      const generated = getRecordedOutlineByOrdinal(ordinal, "iracing");
      if (generated) {
        return {
          points: generated,
          labels: [],
          pitLines: [],
          recorded: true,
          source: "generated",
        };
      }
    }
  }

  return null;
}

// ─── Segment resolution ─────────────────────────────────────────────────────

/**
 * Load persisted segment fractions from generated track-registry SQLite.
 * Curated geometry wins; compatible canonical peers are the only fallback.
 * Automatic detection is an explicit authoring action, never a runtime read.
 */
export async function resolveTrackSegments(ordinal: number, gameId: string | undefined): Promise<{ segments: NamedSegment[]; totalDist: number; source: "shared" | "canonical" | "none" }> {
  const slug = getSharedTrackName(ordinal, gameId);
  const registrySegments = slug && gameId ? loadLabelledSegments(slug, gameId) : [];
  if (registrySegments.length > 0) {
    return { segments: registrySegments, totalDist: 0, source: "shared" };
  }

  const parsedGameId = GameIdSchema.safeParse(gameId);
  if (parsedGameId.success && parsedGameId.data !== "iracing") {
    const iracingPeer = loadCanonicalTrackPeer(parsedGameId.data, ordinal, "iracing");
    if (iracingPeer) {
      const inherited = await resolveTrackSegments(iracingPeer.trackOrdinal, "iracing");
      if (inherited.source !== "none") return { ...inherited, source: "canonical" };
    }
  }

  return { segments: [], totalDist: 0, source: "none" };
}

/** Generate an editable preview from outline assets without persisting it. */
export async function generateTrackSegments(ordinal: number, gameId: string): Promise<{ segments: NamedSegment[]; totalDist: number; source: "auto" | "none" }> {
  const resolved = await resolveTrackOutline(ordinal, gameId);
  const outline = resolved?.points ?? null;
  if (!outline || outline.length < 20) {
    return { segments: [], totalDist: 0, source: "none" };
  }
  const iracingTrack = gameId === "iracing" ? getIRacingTrack(ordinal) : undefined;
  const ovalDirection = gameId === "iracing" ? getIRacingOvalDirection(ordinal) : undefined;
  const isFourTurnOval = iracingTrack?.category.endsWith("oval") === true && iracingTrack.cornersPerLap === 4;
  const ovalTurnAnchors = isFourTurnOval && resolved?.labels.length ? projectIRacingTurnAnchors(outline, resolved.labels) : [];
  const result = autoTrackSegments(outline, isFourTurnOval && ovalDirection ? { fourTurnOval: { direction: ovalDirection, turnAnchors: ovalTurnAnchors } } : {});
  const segments = gameId === "iracing" && !isFourTurnOval && resolved?.labels.length ? alignIRacingAutoSegmentsToTurnLabels(result.segments, outline, resolved.labels) : result.segments;
  return {
    segments,
    totalDist: result.totalDist,
    source: segments.length > 0 ? "auto" : "none",
  };
}
