import type { IRacingSourceFrameV2, IRacingSourceFrameV3 } from "../../../server/games/iracing/source-frame";

export function sampleFrame(): IRacingSourceFrameV2 {
  return {
    schemaVersion: 2,
    session: {
      sessionId: 123,
      subSessionId: 456,
      sessionNum: 2,
      driverCarIdx: 7,
      trackId: 99,
      trackName: "Road America",
      trackLengthM: 6515,
      sectorStarts: [0, 0.34, 0.67],
      carId: 42,
      carName: "GT3 Test Car",
      carClassId: 8,
      carClassName: "GT3",
      engineIdleRpm: 900,
      engineRedlineRpm: 8500,
      engineCylinderCount: 8,
    },
    values: {
      SessionTime: 125.5,
      SessionTick: 7530,
      SessionNum: 2,
      IsOnTrack: true,
      OnPitRoad: false,
      PlayerTrackSurface: 3,
      PlayerIncidents: 1,
      PlayerCarPosition: 4,
      Speed: 72.5,
      RPM: 7000,
      Throttle: 0.75,
      Brake: 0.2,
      Clutch: 0,
      Gear: 5,
      SteeringWheelAngle: 0.2,
      SteeringWheelAngleMax: 2,
      FuelLevel: 41.25,
      Lap: 3,
      LapDist: 1200,
      LapDistPct: 0.184,
      LapBestLapTime: 121.2,
      LapLastLapTime: 122.4,
      LapCurrentLapTime: 25.5,
      LatAccel: 4.2,
      LongAccel: 1.1,
      VertAccel: 9.8,
      LFshockDefl: 0.04,
      RFshockDefl: 0.041,
      LRshockDefl: 0.05,
      RRshockDefl: 0.051,
      LFtempCL: 82,
      LFtempCM: 84,
      LFtempCR: 86,
      LFwearL: 0.95,
      LFwearM: 0.94,
      LFwearR: 0.96,
      TrackTemp: 32,
      AirTemp: 23,
      Precipitation: 0,
      TrackWetness: 0,
      CarPath: " gt3 test car ",
      CarIdxOnPitRoad: [true, false, true],
      EngineWarnings: 0xf0000001,
      CarIdxLapDistPct: [0.125, 0.5, 0.875],
      LapDeltaToBestLap: -0.012345678901234,
    },
  };
}

export function sampleFrameV3(
  sessionInfo = "WeekendInfo:\n  TrackDisplayName: Road America\n",
  sessionInfoUpdate = 7,
): IRacingSourceFrameV3 {
  const frame = sampleFrame();
  return {
    schemaVersion: 3,
    session: frame.session,
    values: frame.values,
    sessionInfo,
    sessionInfoUpdate,
  };
}
