import * as cheerio from "cheerio";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import { fetchText, sleep } from "../../lib/http";
import { runPool } from "../../lib/pool";

const BASE = "https://accsetups.com";
const MAX_PER_CAR_TRACK = 10;
const SOURCE_SLUG = "accsetups-com";
const HEADERS = { "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) RaceIQ-SetupScraper/1.0" };
interface ScrapedSetup { name: string; carModel: string; carClass: string; trackName: string; downloadUrl: string; videoUrl: string; pageUrl: string; author: string; lapTime: string; date: string; hasRace: boolean; hasQuali: boolean; hasSafe: boolean; hasWet: boolean; }
const relativeToDate = (text: string): string => { const match = text.trim().match(/^(\d+)\s+(day|week|month|year)s?\s+ago$/i); if (!match) return ""; const date = new Date(); const amount = parseInt(match[1], 10); const unit = match[2].toLowerCase(); if (unit === "day") date.setDate(date.getDate() - amount); else if (unit === "week") date.setDate(date.getDate() - amount * 7); else if (unit === "month") date.setMonth(date.getMonth() - amount); else date.setFullYear(date.getFullYear() - amount); return date.toISOString().slice(0, 7); };
async function fetchPage(url: string): Promise<string> { return fetchText(url, { headers: HEADERS }); }
async function getCarUrls(): Promise<{ slug: string; name: string }[]> { const $ = cheerio.load(await fetchPage(BASE)); const cars: { slug: string; name: string }[] = []; const seen = new Set<string>(); $("a[href*=\"/games/assetto-corsa-competizione/cars/\"]").each((_, element) => { const href = $(element).attr("href"); const match = href?.match(/\/cars\/([\w-]+)\/?$/); if (!match || seen.has(match[1])) return; seen.add(match[1]); const title = $(element).attr("title") || ""; cars.push({ slug: match[1], name: title.replace(/\s*\(\d{4}\)\s*$/, "").trim() || match[1] }); }); return cars; }
async function scrapeCarSetups(carSlug: string, carName: string): Promise<ScrapedSetup[]> { const $ = cheerio.load(await fetchPage(`${BASE}/games/assetto-corsa-competizione/cars/${carSlug}/`)); const setups: ScrapedSetup[] = []; let currentDate = ""; $(".setup-list__row--item, .dividing-headline").each((_, element) => { const row = $(element); if (row.hasClass("dividing-headline")) { currentDate = relativeToDate(row.text().trim()); return; } const trackName = row.find(".setup-list__track a").text().trim(); if (!trackName) return; const absolute = (selector: string) => { const href = row.find(selector).attr("href") || ""; return href.startsWith("http") ? href : href ? `${BASE}${href}` : ""; }; setups.push({ name: `${carName} ${trackName}`, carModel: carSlug, carClass: row.find(".setup-list__class").text().trim(), trackName, downloadUrl: absolute("a.setup-list__download"), videoUrl: absolute("a.setup-list__hotlap-icon"), pageUrl: absolute("a.setup-list__link"), author: row.find(".setup-list__author a").text().trim(), lapTime: row.find(".setup-list__time").text().replace(/[^\d:.]/g, "").trim(), date: currentDate, hasRace: row.find(".setup-list__variants__race svg").length > 0, hasQuali: row.find(".setup-list__variants__quali svg").length > 0, hasSafe: row.find(".setup-list__variants__safe svg").length > 0, hasWet: row.find(".setup-list__variants__wet svg").length > 0 }); }); return setups; }
const slugify = (value: string): string => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+$/, "").replace(/^-+/, "");
const downloadHosts = ["drive.google.com", "docs.google.com", "onedrive.live.com", "1drv.ms", "dropbox.com", "mega.nz", "mega.co.nz"];
function youtubeId(url: string): string | null { try { const parsed = new URL(url); if (parsed.hostname.includes("youtube.com")) return parsed.searchParams.get("v"); if (parsed.hostname === "youtu.be") return parsed.pathname.slice(1); } catch { /* invalid URL */ } return null; }
function downloadLink(description: string): string { for (const link of description.match(/https?:\/\/[^\s]+/g) ?? []) { try { if (downloadHosts.some(host => new URL(link).hostname.includes(host))) return link; } catch { /* invalid URL */ } } return ""; }
async function fetchYouTubeMeta(id: string): Promise<{ uploadDate: string; downloadUrl: string }> { const html = await fetchPage(`https://www.youtube.com/watch?v=${id}`); const date = html.match(/"uploadDate":"([^"]+)"/)?.[1]?.slice(0, 10) ?? ""; const marker = '"shortDescription":"'; const index = html.indexOf(marker); let description = ""; for (let i = index < 0 ? html.length : index + marker.length; i < html.length && index >= 0; i++) { const c = html[i], next = html[i + 1]; if (c === "\\" && next === '"') { description += '"'; i++; } else if (c === "\\" && next === "n") { description += "\n"; i++; } else if (c === "\\" && next === "\\") { description += "\\"; i++; } else if (c === '"') break; else description += c; } return { uploadDate: date, downloadUrl: downloadLink(description) }; }
async function enrich(setups: ScrapedSetup[]): Promise<void> { const ids = new Set<string>(); for (const setup of setups) { const id = youtubeId(setup.downloadUrl) || youtubeId(setup.videoUrl); if (id) ids.add(id); } if (!ids.size) return; console.log(`\nFetching YouTube metadata for ${ids.size} unique videos...`); const cache = new Map<string, { uploadDate: string; downloadUrl: string }>(); let done = 0; await runPool([...ids], 5, async id => { try { cache.set(id, await fetchYouTubeMeta(id)); } catch { cache.set(id, { uploadDate: "", downloadUrl: "" }); } done++; if (done % 20 === 0) process.stdout.write(`  ${done}/${ids.size}...\n`); await sleep(150); }); let dates = 0, links = 0; for (const setup of setups) { const id = youtubeId(setup.downloadUrl) || youtubeId(setup.videoUrl); const meta = id ? cache.get(id) : undefined; if (!meta) continue; if (meta.uploadDate && !setup.date) { setup.date = meta.uploadDate; dates++; } if (meta.downloadUrl) { setup.downloadUrl = meta.downloadUrl; links++; } } console.log(`  Dates added: ${dates}, download links found: ${links}`); }
export async function main(): Promise<void> { console.log("Fetching car list from accsetups.com..."); const cars = await getCarUrls(); console.log(`Found ${cars.length} cars\n`); const all: ScrapedSetup[] = []; for (let i = 0; i < cars.length; i++) { const car = cars[i]; process.stdout.write(`[${i + 1}/${cars.length}] ${car.name} ... `); try { const setups = await scrapeCarSetups(car.slug, car.name); console.log(`${setups.length} setups`); all.push(...setups); } catch (error) { console.log(`FAILED: ${(error as Error).message}`); } await sleep(400); } console.log(`\nTotal raw setups: ${all.length}`); await enrich(all); const filtered = all.filter(setup => !["base setup", "base"].includes(setup.trackName.toLowerCase())); const grouped = new Map<string, ScrapedSetup[]>(); for (const setup of filtered) grouped.set(`${setup.carModel}::${setup.trackName}`, [...(grouped.get(`${setup.carModel}::${setup.trackName}`) ?? []), setup]); const outBase = resolve(import.meta.dir, "../../../shared/data/tunes/acc", SOURCE_SLUG); mkdirSync(outBase, { recursive: true }); writeFileSync(resolve(outBase, "_source.json"), JSON.stringify({ name: "ACC Setups", slug: SOURCE_SLUG, domain: "accsetups.com", url: `${BASE}/`, lastScraped: new Date().toISOString() }, null, 2)); let files = 0, total = 0; for (const setups of grouped.values()) { setups.sort((a, b) => !a.lapTime && !b.lapTime ? 0 : !a.lapTime ? 1 : !b.lapTime ? -1 : a.lapTime.localeCompare(b.lapTime)); const limited = setups.slice(0, MAX_PER_CAR_TRACK); const dir = resolve(outBase, slugify(limited[0].trackName)); mkdirSync(dir, { recursive: true }); writeFileSync(resolve(dir, `${limited[0].carModel}.json`), JSON.stringify(limited, null, 2)); files++; total += limited.length; } const metaPath = resolve(outBase, "_source.json"); const meta = JSON.parse(readFileSync(metaPath, "utf-8")); meta.lastScraped = new Date().toISOString(); writeFileSync(metaPath, JSON.stringify(meta, null, 2)); console.log(`\nWritten ${files} files (${total} setups) to ${outBase}`); console.log(`${new Set(filtered.map(setup => setup.carModel)).size} cars, ${new Set(filtered.map(setup => slugify(setup.trackName))).size} tracks`); }
