// Generated by scripts/generate-telemetry-catalog.ts. Do not edit.
import catalog from "./telemetry-catalog.generated.json";

export const TELEMETRY_CATALOG_VERSION = "0.13.0";
export const TELEMETRY_CATALOG_SCHEMA_VERSION = "v6";
export const TELEMETRY_CATALOG_HASH = "9fac7ca09c4bc36d7bbfe3166c3dcb44edafaba049db7bfee11bbe4c67b5145f";
export const TELEMETRY_CATALOG_GENERATED = catalog;
