import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { parseChangelog } from "../shared/changelog";

const root = process.cwd();
const source = readFileSync(join(root, "CHANGELOG.md"), "utf8");
const entries = parseChangelog(source);
const output = `// Generated by scripts/generate-changelog.ts. Do not edit.\nimport type { ChangelogEntry } from "../../shared/changelog";\n\nexport const embeddedChangelog: ChangelogEntry[] = ${JSON.stringify(entries, null, 2)};\n`;
const outputPath = join(root, "server/generated/changelog.ts");
mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, output);
