// Generated from packages/game-fm-2023-metadata/src/tracks.csv. Do not edit.
export const TRACK_NAME_BY_ORDINAL: Readonly<Record<number, string>> = {
  "0": "WeatherTech Raceway Laguna Seca",
  "1": "WeatherTech Raceway Laguna Seca",
  "3": "Road America",
  "5": "Road America",
  "16": "Road Atlanta",
  "17": "Road Atlanta",
  "21": "Silverstone Racing Circuit",
  "22": "Silverstone Racing Circuit",
  "23": "Silverstone Racing Circuit",
  "31": "Nürburgring",
  "32": "Nürburgring",
  "33": "Nürburgring",
  "34": "Nürburgring",
  "35": "Mugello Circuit",
  "36": "Mugello Circuit",
  "37": "Suzuka Circuit",
  "38": "Suzuka Circuit",
  "40": "Sebring International",
  "42": "Sebring International",
  "67": "Maple Valley",
  "68": "Maple Valley",
  "70": "Maple Valley",
  "78": "Fujimi Kaido",
  "83": "Fujimi Kaido",
  "100": "Le Mans - Circuit International de la Sarthe",
  "101": "Le Mans - Circuit International de la Sarthe",
  "110": "Circuit de Barcelona-Catalunya",
  "111": "Circuit de Barcelona-Catalunya",
  "113": "Circuit de Barcelona-Catalunya",
  "231": "Indianapolis Motor Speedway",
  "232": "Indianapolis Motor Speedway",
  "250": "Hockenheimring",
  "251": "Hockenheimring",
  "252": "Hockenheimring",
  "510": "Yas Marina Circuit",
  "511": "Yas Marina Circuit",
  "512": "Yas Marina Circuit",
  "513": "Yas Marina Circuit",
  "530": "Circuit de Spa-Francorchamps",
  "540": "Mount Panorama",
  "840": "Daytona Intl Speedway",
  "841": "Daytona Intl Speedway",
  "860": "Brand Hatch",
  "861": "Brand Hatch",
  "870": "Watkins Glen International Speedway",
  "873": "Watkins Glen International Speedway",
  "880": "Lime Rock Park",
  "882": "Lime Rock Park",
  "883": "Lime Rock Park",
  "990": "Virginia International Raceway",
  "991": "Virginia International Raceway",
  "992": "Virginia International Raceway",
  "995": "Virginia International Raceway",
  "996": "Virginia International Raceway",
  "1110": "Homestead-Miami Speedway",
  "1111": "Homestead-Miami Speedway",
  "1450": "Mid-Ohio Sports Car Course",
  "1452": "Mid-Ohio Sports Car Course",
  "1590": "Kyalami Grand Prix Circuit",
  "1620": "Sunset Peninsula Raceway",
  "1621": "Sunset Peninsula Raceway",
  "1622": "Sunset Peninsula Raceway",
  "1623": "Sunset Peninsula Raceway",
  "1624": "Sunset Peninsula Raceway",
  "1630": "Grand Oak Raceway",
  "1631": "Grand Oak Raceway",
  "1632": "Grand Oak Raceway",
  "1640": "Hakone",
  "1641": "Hakone",
  "1643": "Hakone",
  "1660": "Eaglerock Speedway",
  "1661": "Eaglerock Speedway",
  "1663": "Eaglerock Speedway"
};
