import type { IRacingSessionInfoCatalogField } from "./contracts";
import { humanize, unitFor } from "./formatting";

const SECTIONS: ReadonlyArray<{
  prefix: string;
  context: string;
  fields: readonly string[];
}> = [
  {
    prefix: "WeekendInfo",
    context: "weekend and track metadata",
    fields: [
      "Category",
      "DCRuleSet",
      "EventType",
      "HeatRacing",
      "LeagueID",
      "MaxDrivers",
      "MinDrivers",
      "NumCarClasses",
      "NumCarTypes",
      "Official",
      "QualifierMustStartRace",
      "RaceWeek",
      "SeasonID",
      "SeriesID",
      "SessionID",
      "SimMode",
      "SubSessionID",
      "TeamRacing",
      "TrackAirPressure",
      "TrackAirTemp",
      "TrackAltitude",
      "TrackCity",
      "TrackCleanup",
      "TrackConfigName",
      "TrackCountry",
      "TrackDirection",
      "TrackDisplayName",
      "TrackDisplayShortName",
      "TrackDynamicTrack",
      "TrackFogLevel",
      "TrackID",
      "TrackLatitude",
      "TrackLength",
      "TrackLengthOfficial",
      "TrackLongitude",
      "TrackName",
      "TrackNorthOffset",
      "TrackNumTurns",
      "TrackPitSpeedLimit",
      "TrackPrecipitation",
      "TrackRelativeHumidity",
      "TrackSkies",
      "TrackSurfaceTemp",
      "TrackType",
      "TrackVersion",
      "TrackWeatherType",
      "TrackWindDir",
      "TrackWindVel",
      "BuildType",
      "BuildTarget",
      "BuildVersion",
    ],
  },
  {
    prefix: "WeekendInfo.WeekendOptions",
    context: "configured weekend options",
    fields: [
      "CommercialMode",
      "CourseCautions",
      "Date",
      "EarthRotationSpeedupFactor",
      "FastRepairsLimit",
      "FogLevel",
      "GreenWhiteCheckeredLimit",
      "HardcoreLevel",
      "HasOpenRegistration",
      "IncidentLimit",
      "IsFixedSetup",
      "NightMode",
      "NumJokerLaps",
      "NumStarters",
      "QualifyScoring",
      "RelativeHumidity",
      "Restarts",
      "ShortParadeLap",
      "Skies",
      "StandingStart",
      "StartingGrid",
      "StrictLapsChecking",
      "TimeOfDay",
      "Unofficial",
      "WeatherTemp",
      "WeatherType",
      "WindDirection",
      "WindSpeed",
    ],
  },
  {
    prefix: "WeekendInfo.TelemetryOptions",
    context: "telemetry recording options",
    fields: ["TelemetryDiskFile"],
  },
  {
    prefix: "SessionInfo.Sessions[]",
    context: "session definition and aggregate results",
    fields: [
      "ResultsAverageLapTime",
      "ResultsLapsComplete",
      "ResultsNumCautionFlags",
      "ResultsNumCautionLaps",
      "ResultsNumLeadChanges",
      "ResultsOfficial",
      "SessionEnforceTireCompoundChange",
      "SessionLaps",
      "SessionName",
      "SessionNum",
      "SessionNumLapsToAvg",
      "SessionRunGroupsUsed",
      "SessionSkipped",
      "SessionSubType",
      "SessionTime",
      "SessionTrackRubberState",
      "SessionType",
    ],
  },
  {
    prefix: "SessionInfo.Sessions[].ResultsFastestLap[]",
    context: "session fastest-lap result",
    fields: ["CarIdx", "FastestLap", "FastestTime"],
  },
  {
    prefix: "SessionInfo.Sessions[].ResultsPositions[]",
    context: "competitor session result",
    fields: [
      "CarIdx",
      "ClassPosition",
      "FastestLap",
      "FastestTime",
      "Incidents",
      "JokerLapsComplete",
      "Lap",
      "LapsComplete",
      "LapsDriven",
      "LapsLed",
      "LastTime",
      "Position",
      "ReasonOutId",
      "ReasonOutStr",
      "Time",
    ],
  },
  {
    prefix: "QualifyResultsInfo.Results[]",
    context: "qualifying result",
    fields: ["CarIdx", "ClassPosition", "FastestLap", "FastestTime", "Position"],
  },
  {
    prefix: "CameraInfo.Groups[]",
    context: "camera group",
    fields: ["GroupName", "GroupNum", "IsScenic"],
  },
  {
    prefix: "CameraInfo.Groups[].Cameras[]",
    context: "camera definition",
    fields: ["CameraName", "CameraNum"],
  },
  {
    prefix: "RadioInfo",
    context: "in-sim radio state",
    fields: ["SelectedRadioNum"],
  },
  {
    prefix: "RadioInfo.Radios[]",
    context: "in-sim radio",
    fields: [
      "HopCount",
      "NumFrequencies",
      "RadioNum",
      "ScanningIsOn",
      "TunedToFrequencyNum",
    ],
  },
  {
    prefix: "RadioInfo.Radios[].Frequencies[]",
    context: "radio frequency",
    fields: [
      "CanScan",
      "CanSquawk",
      "CarIdx",
      "ClubID",
      "EntryIdx",
      "FrequencyName",
      "FrequencyNum",
      "IsDeletable",
      "IsMutable",
      "Muted",
      "Priority",
    ],
  },
  {
    prefix: "DriverInfo",
    context: "player and player-car metadata",
    fields: [
      "DriverCarIdx",
      "DriverUserID",
      "PaceCarIdx",
      "DriverHeadPosX",
      "DriverHeadPosY",
      "DriverHeadPosZ",
      "DriverCarIdleRPM",
      "DriverCarRedLine",
      "DriverCarEngCylinderCount",
      "DriverCarGearNeutral",
      "DriverCarGearNumForward",
      "DriverCarGearReverse",
      "DriverCarIsElectric",
      "DriverCarFuelKgPerLtr",
      "DriverCarFuelMaxLtr",
      "DriverCarMaxFuelPct",
      "DriverCarSLFirstRPM",
      "DriverCarSLShiftRPM",
      "DriverCarSLLastRPM",
      "DriverCarSLBlinkRPM",
      "DriverCarVersion",
      "DriverPitTrkPct",
      "DriverCarEstLapTime",
      "DriverSetupName",
      "DriverSetupIsModified",
      "DriverSetupLoadTypeName",
      "DriverSetupPassedTech",
      "DriverIncidentCount",
    ],
  },
  {
    prefix: "DriverInfo.Drivers[]",
    context: "registered competitor",
    fields: [
      "AbbrevName",
      "CarClassColor",
      "CarClassDryTireSetLimit",
      "CarClassEstLapTime",
      "CarClassID",
      "CarClassLicenseLevel",
      "CarClassMaxFuelPct",
      "CarClassPowerAdjust",
      "CarClassRelSpeed",
      "CarClassShortName",
      "CarClassWeightPenalty",
      "CarDesignStr",
      "CarID",
      "CarIdx",
      "CarIsAI",
      "CarIsPaceCar",
      "CarIsElectric",
      "CarNumber",
      "CarNumberDesignStr",
      "CarNumberRaw",
      "CarPath",
      "CarScreenName",
      "CarScreenNameShort",
      "CarSponsor_1",
      "CarSponsor_2",
      "ClubName",
      "ClubID",
      "CurDriverIncidentCount",
      "DivisionName",
      "DivisionID",
      "HelmetDesignStr",
      "Initials",
      "IRating",
      "IsSpectator",
      "LicColor",
      "LicLevel",
      "LicString",
      "LicSubLevel",
      "SuitDesignStr",
      "TeamID",
      "TeamIncidentCount",
      "TeamName",
      "UserID",
      "UserName",
    ],
  },
  {
    prefix: "SplitTimeInfo.Sectors[]",
    context: "native track-sector layout",
    fields: ["SectorNum", "SectorStartPct"],
  },
];

const DESCRIPTION_OVERRIDES: Record<string, string> = {
  "WeekendInfo.TrackLength":
    "Official track length with unit embedded in iRacing YAML value.",
  "WeekendInfo.TrackLengthOfficial":
    "Official sanctioned track length with unit embedded in iRacing YAML value.",
  "WeekendInfo.TrackVersion":
    "iRacing content-build version for the active track configuration.",
  "WeekendInfo.TrackPitSpeedLimit":
    "Configured pit-lane speed limit with unit embedded in YAML value.",
  "SessionInfo.Sessions[].SessionEnforceTireCompoundChange":
    "Whether this session enforces a tire-compound change.",
  "SessionInfo.Sessions[].ResultsPositions[].Incidents":
    "Incident points assessed to this competitor in the session.",
  "SessionInfo.Sessions[].ResultsPositions[].LapsLed":
    "Completed laps led by this competitor in the session.",
  "SessionInfo.Sessions[].ResultsPositions[].FastestTime":
    "Competitor's fastest completed lap time in this session.",
  "SessionInfo.Sessions[].ResultsPositions[].LastTime":
    "Competitor's most recently completed lap time.",
  "SessionInfo.Sessions[].ResultsPositions[].Time":
    "Competitor's elapsed or result time for this session.",
  "SessionInfo.Sessions[].ResultsFastestLap[].FastestTime":
    "Fastest completed lap time represented by this session result entry.",
  "QualifyResultsInfo.Results[].FastestTime":
    "Competitor's fastest qualifying lap time.",
  "DriverInfo.DriverCarGearNeutral":
    "Number of neutral positions in the player car gearbox.",
  "DriverInfo.DriverCarGearNumForward":
    "Number of forward gears in the player car gearbox.",
  "DriverInfo.DriverCarGearReverse":
    "Number of reverse gears in the player car gearbox.",
  "DriverInfo.DriverCarIsElectric":
    "Whether the player car uses an electric drivetrain.",
  "DriverInfo.Drivers[].CarClassEstLapTime":
    "iRacing's estimated lap time for this competitor's car class.",
  "DriverInfo.Drivers[].CarIsElectric":
    "Whether this competitor's car uses an electric drivetrain.",
  "DriverInfo.Drivers[].ClubID":
    "iRacing club identifier assigned to this competitor.",
  "DriverInfo.Drivers[].DivisionID":
    "iRacing division identifier assigned to this competitor.",
  "DriverInfo.DriverCarEstLapTime":
    "iRacing's estimated lap time for player car and current track.",
  "DriverInfo.DriverPitTrkPct":
    "Lap fraction where player car's pit stall is located.",
  "SplitTimeInfo.Sectors[].SectorNum":
    "Zero-based order of this native iRacing sector.",
  "SplitTimeInfo.Sectors[].SectorStartPct":
    "Lap fraction where this sector starts and previous sector ends.",
};

export const IRACING_SESSION_INFO_SECTION_FIELDS: readonly IRacingSessionInfoCatalogField[] = SECTIONS.flatMap(
  ({ prefix, context, fields }) =>
    fields.map((field) => {
      const path = `${prefix}.${field}`;
      return {
        path,
        label: humanize(field),
        unit: unitFor(path),
        description:
          DESCRIPTION_OVERRIDES[path] ??
          `${humanize(field)} from iRacing ${context}.`,
        retention: "exact" as const,
      };
    }),
);
