import { writeFileSync } from "fs";
import type { NamedSegment } from "../../shared/track-named-segments";

interface Pt { x: number; z: number }

/** Distinct, high-contrast colors cycled across corner segments. */
const CORNER_COLORS = [
  "#ef4444", "#f97316", "#eab308", "#22c55e", "#06b6d4",
  "#3b82f6", "#8b5cf6", "#ec4899", "#14b8a6", "#f43f5e",
];
const STRAIGHT_COLOR = "#9ca3af";

/**
 * Render a centerline with its named segments as an SVG — same spirit as the
 * lap SVGs in lap-svg.ts, but colored per segment with corner-name labels and
 * sector boundary markers. Regenerated by tests so segment changes show up as
 * reviewable diffs in test/e2e/output.
 */
export function generateSegmentSvg(
  outline: Pt[],
  segments: NamedSegment[],
  sectors: { s1End: number; s2End: number } | null,
  title: string,
  outFile: string,
): void {
  if (outline.length < 2) return;

  // Cumulative distance → fraction per outline point
  const cum: number[] = [0];
  for (let i = 1; i < outline.length; i++) {
    const dx = outline[i].x - outline[i - 1].x;
    const dz = outline[i].z - outline[i - 1].z;
    cum.push(cum[i - 1] + Math.sqrt(dx * dx + dz * dz));
  }
  const total = cum[cum.length - 1] || 1;
  const fracOf = (i: number) => cum[i] / total;
  const idxAtFrac = (f: number) => {
    const target = f * total;
    let lo = 0;
    let hi = cum.length - 1;
    while (lo < hi) {
      const mid = (lo + hi) >> 1;
      if (cum[mid] < target) lo = mid + 1;
      else hi = mid;
    }
    return lo;
  };

  let minX = outline[0].x, maxX = outline[0].x, minZ = outline[0].z, maxZ = outline[0].z;
  for (const p of outline) {
    minX = Math.min(minX, p.x); maxX = Math.max(maxX, p.x);
    minZ = Math.min(minZ, p.z); maxZ = Math.max(maxZ, p.z);
  }
  const pad = Math.max(maxX - minX, maxZ - minZ) * 0.12 || 100;
  const viewMinX = minX - pad, viewMaxX = maxX + pad;
  const viewMinZ = minZ - pad, viewMaxZ = maxZ + pad;
  const svgWidth = 1000, svgHeight = 800;
  const scale = Math.min(svgWidth / (viewMaxX - viewMinX), svgHeight / (viewMaxZ - viewMinZ));
  const toSvg = (p: Pt) => ({
    x: (p.x - viewMinX) * scale,
    y: (viewMaxZ - p.z) * scale, // invert Z to match track orientation
  });

  // Track centroid for outward label offsets
  const centroid = toSvg({
    x: outline.reduce((a, p) => a + p.x, 0) / outline.length,
    z: outline.reduce((a, p) => a + p.z, 0) / outline.length,
  });

  const polylines: string[] = [];
  const labels: string[] = [];
  let cornerIdx = 0;
  for (const seg of segments) {
    const from = idxAtFrac(seg.startFrac);
    const to = Math.max(from + 1, idxAtFrac(seg.endFrac));
    const pts = outline.slice(from, to + 1).map((p) => {
      const s = toSvg(p);
      return `${s.x.toFixed(1)},${s.y.toFixed(1)}`;
    });
    if (pts.length < 2) continue;
    const isCorner = seg.type === "corner";
    const color = isCorner ? CORNER_COLORS[cornerIdx++ % CORNER_COLORS.length] : STRAIGHT_COLOR;
    polylines.push(`  <polyline fill="none" stroke="${color}" stroke-width="${isCorner ? 5 : 2.5}" points="${pts.join(" ")}" />`);

    if (seg.name) {
      const mid = toSvg(outline[idxAtFrac((seg.startFrac + seg.endFrac) / 2)]);
      // Push label away from the centroid so it sits outside the track line
      const dx = mid.x - centroid.x, dy = mid.y - centroid.y;
      const len = Math.sqrt(dx * dx + dy * dy) || 1;
      const lx = mid.x + (dx / len) * 26;
      const ly = mid.y + (dy / len) * 26;
      const anchor = lx < mid.x ? "end" : "start";
      labels.push(
        `  <line x1="${mid.x.toFixed(1)}" y1="${mid.y.toFixed(1)}" x2="${lx.toFixed(1)}" y2="${ly.toFixed(1)}" stroke="#d1d5db" stroke-width="1" />`,
        `  <text x="${lx.toFixed(1)}" y="${ly.toFixed(1)}" text-anchor="${anchor}" class="name" fill="${isCorner ? "#111827" : "#6b7280"}">${escapeXml(seg.name)}</text>`,
      );
    }
  }

  // Sector boundary markers
  const sectorMarks: string[] = [];
  if (sectors) {
    for (const [label, frac] of [["S1", sectors.s1End], ["S2", sectors.s2End]] as const) {
      const i = idxAtFrac(frac);
      const p = toSvg(outline[i]);
      sectorMarks.push(
        `  <circle cx="${p.x.toFixed(1)}" cy="${p.y.toFixed(1)}" r="7" fill="none" stroke="#7c3aed" stroke-width="2.5" />`,
        `  <text x="${(p.x + 11).toFixed(1)}" y="${(p.y - 8).toFixed(1)}" class="sector">${label} ${frac.toFixed(3)}</text>`,
      );
    }
  }

  // Start/finish marker
  const start = toSvg(outline[0]);

  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${svgWidth}" height="${svgHeight}" viewBox="0 0 ${svgWidth} ${svgHeight}">
  <defs>
    <style>
      .name { font-family: monospace; font-size: 12px; }
      .sector { font-family: monospace; font-size: 12px; fill: #7c3aed; font-weight: bold; }
      .title { font-family: monospace; font-size: 14px; fill: #111827; font-weight: bold; }
      .sub { font-family: monospace; font-size: 11px; fill: #6b7280; }
    </style>
  </defs>
  <rect width="${svgWidth}" height="${svgHeight}" fill="#ffffff" />
${polylines.join("\n")}
${labels.join("\n")}
${sectorMarks.join("\n")}
  <rect x="${(start.x - 5).toFixed(1)}" y="${(start.y - 5).toFixed(1)}" width="10" height="10" fill="#111827" />
  <text x="${(start.x + 12).toFixed(1)}" y="${(start.y + 4).toFixed(1)}" class="sub">S/F</text>
  <text class="title" x="12" y="22">${escapeXml(title)}</text>
  <text class="sub" x="12" y="40">${segments.filter((s) => s.type === "corner").length} corners, ${segments.length} segments, ${(total / 1000).toFixed(3)} km</text>
</svg>`;

  writeFileSync(outFile, svg);
}

function escapeXml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
