import { create } from "zustand";
import type { LiveEngineerCalloutMessageV3, LiveEngineerDeliveryStatusV3, LiveEngineerVoiceLineMessageV3, LiveEngineerVoiceRequestV3 } from "../../../shared/racing/live/engineer-contracts";
export type LiveEngineerCallout = LiveEngineerCalloutMessageV3;
type Outbound = LiveEngineerVoiceRequestV3 | LiveEngineerDeliveryStatusV3;
interface LiveEngineerState { current: LiveEngineerCalloutMessageV3 | null; voiceCurrent: LiveEngineerVoiceLineMessageV3 | null; queue: LiveEngineerCalloutMessageV3[]; history: LiveEngineerCalloutMessageV3[]; playback: "idle" | "playing" | "failed"; outbound: Outbound[]; receiveCallout: (callout: LiveEngineerCalloutMessageV3) => void; receiveVoiceLine: (line: LiveEngineerVoiceLineMessageV3, currentSessionTimeMs?: number) => void; finishVoiceLine: (deliveryId: string) => void; enqueueControl: (message: Outbound) => void; takeOutbound: () => Outbound | undefined; dismiss: () => void; setPlayback: (playback: LiveEngineerState["playback"]) => void; }
export const useLiveEngineerStore = create<LiveEngineerState>((set, get) => ({ current: null, voiceCurrent: null, queue: [], history: [], playback: "idle", outbound: [],
 receiveCallout: (callout) => set((state) => { if (state.history.some((x) => x.decisionId === callout.decisionId)) return state; return { ...state, current: state.current ?? callout, queue: state.current ? [...state.queue, callout].slice(-3) : state.queue, history: [callout, ...state.history].slice(0, 5) }; }),
 receiveVoiceLine: (line, now = Date.now()) => set((state) => { if (state.voiceCurrent?.deliveryId === line.deliveryId) return state; if (line.expiresSessionTimeMs <= now) return { ...state, outbound: [...state.outbound, { type: "live-engineer-delivery-status", protocolVersion: 3, deliveryId: line.deliveryId, status: "failed", reason: "expired" }] }; const spotter = line.family === "spotter"; const current = state.voiceCurrent; if (current && spotter && current.family !== "spotter") return { ...state, voiceCurrent: line, outbound: [...state.outbound, { type: "live-engineer-delivery-status", protocolVersion: 3, deliveryId: current.deliveryId, status: "preempted", reason: "superseded" }] }; if (current) return { ...state, outbound: [...state.outbound, { type: "live-engineer-delivery-status", protocolVersion: 3, deliveryId: line.deliveryId, status: "failed", reason: "superseded" }] }; return { ...state, voiceCurrent: line }; }),
 finishVoiceLine: (deliveryId) => set((state) => state.voiceCurrent?.deliveryId !== deliveryId ? state : { ...state, voiceCurrent: null, playback: "idle" }),
 enqueueControl: (message) => set((state) => ({ outbound: [...state.outbound, message] })), takeOutbound: () => { const next = get().outbound[0]; if (next) set((s) => ({ outbound: s.outbound.slice(1) })); return next; }, dismiss: () => set((state) => ({ ...state, current: state.queue[0] ?? null, queue: state.queue.slice(1) })), setPlayback: (playback) => set({ playback }) }));
