import type { GameId } from "../../../../shared/games/ids";
import type { useUnits } from "../../hooks/useUnits";
import { severityRangeColor } from "../../lib/colors";
import { frictionUtilColor, slipRatioColor, tireState, tireTempLabel } from "../../lib/vehicle-dynamics";
import { m } from "../../paraglide/messages";
import { WheelTable } from "./WheelTable";
import type { SemanticAnalysisFrame } from "./track-map/types";
interface Props { frame: SemanticAnalysisFrame; gameId?: GameId; units: ReturnType<typeof useUnits>; }
const W=["FL","FR","RL","RR"] as const; const arr=(f:SemanticAnalysisFrame,id:string)=>(W.map((_,i)=>{const v=f.values[id];return Array.isArray(v)&&typeof v[i]==="number"&&Number.isFinite(v[i])?v[i]:null})); const n=(f:SemanticAnalysisFrame,id:string)=>typeof f.values[id]==="number"&&Number.isFinite(f.values[id] as number)?f.values[id] as number:null; const u=<span className="text-app-text-dim">—</span>;
export function AnalyseDynamicsPanel({frame,units}:Props){const slip=arr(frame,"tires.tire-slip-ratio"), angle=arr(frame,"tires.tire-slip-angle"), temp=arr(frame,"tire.temperature.average"), grip=arr(frame,"tires.tire-combined-slip"), speed=n(frame,"motion.speed"); const C=(v:string,c:string)=><span style={{color:c}}>{v}</span>; const states=slip.map((v,i)=>v==null?null:tireState("nominal",v,angle[i]??0)); const sf=Math.max(.3,Math.min(1,(speed??0)*2.23694/80)); return <div className="text-app-compact font-mono space-y-1.5 mb-3"><div className="flex justify-between"><span className="text-app-text-muted">{m.analyse_g_force()}</span><span className="tabular-nums text-app-text">Lat {n(frame,"motion.acceleration-x") == null ? "—" : `${(-(n(frame,"motion.acceleration-x")!)/9.81).toFixed(2)}g`} Lon {n(frame,"motion.acceleration-z") == null ? "—" : `${(-(n(frame,"motion.acceleration-z")!)/9.81).toFixed(2)}g`}</span></div><WheelTable rows={[{label:m.analyse_dynamics_grip_ask(),fl:grip[0]==null?u:C(`${(grip[0]*100).toFixed(0)}%`,frictionUtilColor(grip[0])),fr:grip[1]==null?u:C(`${(grip[1]*100).toFixed(0)}%`,frictionUtilColor(grip[1])),rl:grip[2]==null?u:C(`${(grip[2]*100).toFixed(0)}%`,frictionUtilColor(grip[2])),rr:grip[3]==null?u:C(`${(grip[3]*100).toFixed(0)}%`,frictionUtilColor(grip[3]))},{label:m.analyse_dynamics_traction(),fl:states[0]==null?u:states[0].label,fr:states[1]==null?u:states[1].label,rl:states[2]==null?u:states[2].label,rr:states[3]==null?u:states[3].label},{label:m.analyse_dynamics_temp(),fl:temp[0]==null?u:tireTempLabel(units.toTempC(temp[0]),units.thresholds).label,fr:temp[1]==null?u:tireTempLabel(units.toTempC(temp[1]),units.thresholds).label,rl:temp[2]==null?u:tireTempLabel(units.toTempC(temp[2]),units.thresholds).label,rr:temp[3]==null?u:tireTempLabel(units.toTempC(temp[3]),units.thresholds).label}]} /><WheelTable title={m.label_slip()} borderTop rows={[{label:m.analyse_dynamics_ratio(),fl:slip[0]==null?u:C(`${(slip[0]*100).toFixed(0)}%`,slipRatioColor(slip[0])),fr:slip[1]==null?u:C(`${(slip[1]*100).toFixed(0)}%`,slipRatioColor(slip[1])),rl:slip[2]==null?u:C(`${(slip[2]*100).toFixed(0)}%`,slipRatioColor(slip[2])),rr:slip[3]==null?u:C(`${(slip[3]*100).toFixed(0)}%`,slipRatioColor(slip[3]))},{label:m.analyse_dynamics_angle(),fl:angle[0]==null?u:C(`${(angle[0]*180/Math.PI).toFixed(1)}°`,severityRangeColor(Math.abs(angle[0]*180/Math.PI),[4/sf,8/sf,14/sf])),fr:angle[1]==null?u:C(`${(angle[1]*180/Math.PI).toFixed(1)}°`,severityRangeColor(Math.abs(angle[1]*180/Math.PI),[4/sf,8/sf,14/sf])),rl:angle[2]==null?u:C(`${(angle[2]*180/Math.PI).toFixed(1)}°`,severityRangeColor(Math.abs(angle[2]*180/Math.PI),[4/sf,8/sf,14/sf])),rr:angle[3]==null?u:C(`${(angle[3]*180/Math.PI).toFixed(1)}°`,severityRangeColor(Math.abs(angle[3]*180/Math.PI),[4/sf,8/sf,14/sf]))}]} /></div>}
