import { readFileSync } from "node:fs";
import type { CarSpecRow, OurCar, WikiCar } from "./types";

const DIVISION_NAMES: Record<string, string> = { "488": "488 Challenge Spec", efr: "Early Factory Racecars", egtc: "Exotic GT Classics", elmp: "Early LMP", esc: "Early Sport Compact", f60: "Formula 60s", f70: "Formula 70s", fau: "Forza AUS", faufgt: "Forza AUS", fd: "Formula Drift", fg2fgt: "Forza GT2", fg3: "Forza GT3", fg3fgt: "Forza GT3", fg4fgt: "Forza GT4", fms: "Formula Mazda Spec", fp1: "Forza P1", fp2: "Forza P2", fph: "Forza Proto-H", fsp: "Forza Specials", ftafgt: "Forza T/A", ftc: "Forza Touring Cars", g40: "Ginetta G40 Junior Spec", gpr: "Grand Prix Rivals", gtp: "GTP/C", gtx: "GTX Sportscars", hhi: "Hot Hatch Icons", megt: "Modern Exotic GT", mfr: "Modern Factory Racecars", mh: "Modern Hypercars", mhh: "Modern Hot Hatch", mrs: "Mission R Spec", mscm: "Modern Sport Compact", mscu: "Modern Sport Coupe", msgt: "Modern Sport GT", mst: "Modern Sport Touring", nas: "NASCAR", pgr: "Prototype Group Racing", sci: "Sport Coupe Icons", sdc: "Street Drag Racers", sgti: "Sport GT Icons", sl: "Sport Luxury", st: "Super Trofeo", stc: "Sport Touring Classics", tbogp: "The Birth of Grand Prix", tt: "Track Toys", vegt: "Vintage Exotic GT", vlmp: "Vintage Le Mans Prototypes", vlms: "Vintage Le Mans Sportscars", vm: "Vintage Muscle", vsc: "Vintage Sport Compact", vta: "Vintage Trans Am" };

function normalize(value: string): string { return value.toLowerCase().replace(/mercedes-benz/g, "mercedes").replace(/mercedes-amg/g, "mercedes").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/#\s*\d+\s+/g, "").replace(/[^a-z0-9]/g, ""); }
function wordOverlap(a: string, b: string): number { const tokens = (value: string) => new Set(value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, " ").trim().split(/\s+/).map(word => word.replace(/^#+/, "")).filter(word => word.length >= 3)); const ta = tokens(a), tb = tokens(b); const [small, large] = ta.size <= tb.size ? [ta, tb] : [tb, ta]; if (!small.size) return 0; let hits = 0; for (const token of small) if (large.has(token)) hits++; return hits / small.size; }
function score(our: OurCar, wiki: WikiCar): number { if (our.year !== wiki.year) return 0; const ourRaw = `${our.make} ${our.model}`; const ourFull = normalize(ourRaw); for (const wikiRaw of [`${wiki.wikiMake ?? ""} ${wiki.wikiModel ?? ""}`, wiki.pageName]) { const wikiString = normalize(wikiRaw); if (!wikiString) continue; if (ourFull === wikiString) return 4; if (ourFull.includes(wikiString) || wikiString.includes(ourFull)) return 3; const [small, large] = ourFull.length < wikiString.length ? [ourFull, wikiString] : [wikiString, ourFull]; if (small.length >= 6 && large.includes(small)) return 2; if (wordOverlap(ourRaw, wikiRaw) >= 0.8) return 1; } return 0; }

export function readCatalog(path: string): OurCar[] { return readFileSync(path, "utf-8").split("\n").map(line => line.trim()).filter(Boolean).flatMap(line => { const [ord, year, make, ...model] = line.split(","); const ordinal = parseInt(ord, 10), parsedYear = parseInt(year, 10); return !Number.isNaN(ordinal) && !Number.isNaN(parsedYear) && make ? [{ ordinal, year: parsedYear, make, model: model.join(",") }] : []; }); }

export function matchCatalog(ourCars: OurCar[], wikiCars: WikiCar[], imageUrlMap: Map<string, string>): { rows: CarSpecRow[]; unmatched: string[] } {
  const byYear = new Map<number, WikiCar[]>();
  for (const car of wikiCars) if (car.year) byYear.set(car.year, [...(byYear.get(car.year) ?? []), car]);
  const rows: CarSpecRow[] = []; const unmatched: string[] = [];
  for (const our of ourCars) {
    let best: WikiCar | null = null; let bestScore = 0;
    for (const wiki of byYear.get(our.year) ?? []) { const candidateScore = score(our, wiki); if (candidateScore > bestScore) { bestScore = candidateScore; best = wiki; } }
    if (!best || bestScore <= 0) { unmatched.push(`${our.year} ${our.make} ${our.model} (ordinal ${our.ordinal})`); continue; }
    rows.push({ ordinal: our.ordinal, hp: best.hp ?? 0, torque: best.torque ?? 0, weightLbs: best.weightLbs ?? 0, weightKg: Math.round((best.weightLbs ?? 0) * 0.453592), displacement: best.displacement ?? 0, engine: best.engine ?? "", drivetrain: best.drivetrain ?? "", gears: best.gears ?? 0, aspiration: best.aspiration ?? "", frontWeightPct: best.frontWeightPct ?? 0, pi: best.pi ?? 0, speedRating: best.speedRating ?? 0, brakingRating: best.brakingRating ?? 0, handlingRating: best.handlingRating ?? 0, accelRating: best.accelRating ?? 0, price: best.price ?? 0, division: DIVISION_NAMES[best.division ?? ""] ?? best.division ?? "", topSpeedMph: best.topSpeedMph ?? 0, quarterMile: best.quarterMile ?? 0, zeroToSixty: best.zeroToSixty ?? 0, zeroToHundred: best.zeroToHundred ?? 0, braking60: best.braking60 ?? 0, braking100: best.braking100 ?? 0, lateralG60: best.lateralG60 ?? 0, lateralG120: best.lateralG120 ?? 0, cdnImageUrl: best.imageFile ? imageUrlMap.get(best.imageFile.replace(/ /g, "_")) ?? best.directImageUrl ?? "" : best.directImageUrl ?? "", imageUrl: "", wikiUrl: best.pageName ? `https://forza.fandom.com/wiki/${best.pageName.replace(/ /g, "_")}` : "", synopsis: (best.synopsis ?? "").replace(/"/g, "'") });
  }
  return { rows, unmatched };
}
