use serde_json::{Map, Number, Value};

const ACC_MAGIC: u32 = 0x5043_4341;
const EVO_MAGIC: u32 = 0x5045_4341;

pub struct Parser {
    game_id: String,
    evo_distance: EvoDistance,
    evo_slot: PlayerSlot,
    last_car: String,
    last_track: String,
    car_ordinal: i64,
    track_ordinal: i64,
    last_static: Vec<u8>,
}

struct PlayerSlot { slot: Option<usize>, observations: u8, scores: [f64; 60], previous: [f32; 180] }
impl Default for PlayerSlot { fn default()->Self{Self{slot:None,observations:0,scores:[0.0;60],previous:[0.0;180]}} }
fn coord(b:&[u8],base:usize,slot:usize)->f64{rf(b,base+slot*12) as f64}
struct EvoDistance { packet: Option<i32>, speed: f64, previous_km: f64, anchor: f64, integral: f64, calibration_integral: f64, calibration_true: f64, seconds_per_step: f64, output: f64 }
impl Default for EvoDistance { fn default()->Self{Self{packet:None,speed:0.0,previous_km:-1.0,anchor:0.0,integral:0.0,calibration_integral:0.0,calibration_true:0.0,seconds_per_step:0.0,output:0.0}}}

impl Parser {
    pub fn new(game_id: &str) -> Result<Self, String> {
        if !matches!(game_id, "acc" | "ac-evo") { return Err(format!("unsupported Kunos game id: {game_id}")); }
        Ok(Self { game_id: game_id.into(), evo_distance: EvoDistance::default(), evo_slot: PlayerSlot::default(), last_car: String::new(), last_track: String::new(), car_ordinal: -1, track_ordinal: -1, last_static: Vec::new() })
    }
    pub fn reset(&mut self) {
        self.evo_distance = EvoDistance::default(); self.evo_slot = PlayerSlot::default();
        self.last_car.clear(); self.last_track.clear(); self.car_ordinal = -1; self.track_ordinal = -1; self.last_static.clear();
    }
    pub fn feed(&mut self, frame: &[u8], time_ms: u64) -> Result<Option<Value>, String> {
        let Some(magic) = u32le(frame, 0) else { return Ok(None) };
        let expected = if self.game_id == "acc" { ACC_MAGIC } else { EVO_MAGIC };
        if magic != expected { return Ok(None); }
        if frame.len() < 24 { return Ok(None); }
        let car = i32le(frame, 4).unwrap() as i64;
        let track = i32le(frame, 8).unwrap() as i64;
        let Some((phys, after_phys)) = part(frame, 12) else { return Ok(None) };
        let Some((graphics, after_graphics)) = part(frame, after_phys) else { return Ok(None) };
        let Some((stat, _)) = part(frame, after_graphics) else { return Ok(None) };
        if self.game_id == "acc" { self.acc(phys, graphics, stat, car, track, time_ms) } else {
            let static_data = if stat.len() >= crate::games::generated::layouts::EVO_STATIC_EVO_SIZE {
                self.last_static.clear(); self.last_static.extend_from_slice(stat); stat.to_vec()
            } else if stat.is_empty() && !self.last_static.is_empty() {
                self.last_static.clone()
            } else { return Ok(None) };
            self.evo(phys, graphics, &static_data, car, track, time_ms)
        }
    }
    fn acc(&mut self, p: &[u8], g: &[u8], s: &[u8], mut car: i64, mut track: i64, t: u64) -> Result<Option<Value>, String> {
        use crate::games::generated::layouts as l;
        if p.len()<l::ACC_PHYSICS_SIZE || g.len()<l::ACC_GRAPHICS_MIN_SIZE || s.len()<l::ACC_STATIC_SIZE { return Ok(None); }
        let model = wide(s,l::ACC_STATIC_CAR_MODEL,66); let track_name = wide(s,l::ACC_STATIC_TRACK,66);
        if let Some(v)=crate::games::catalog::resolve_acc_car(&model) { car=v.get("id").and_then(Value::as_i64).unwrap_or(car); }
        if let Some(v)=crate::games::catalog::resolve_acc_track(&track_name) { track=v.get("id").and_then(Value::as_i64).unwrap_or(track); }
        let mut m=Map::new();
        base(&mut m,"acc",t,car,track,read_i(g,l::ACC_GRAPHICS_COMPLETED_LAPS)+1, read_i(g,l::ACC_GRAPHICS_STATUS)==2);
        let current=valid_ms(read_i(g,l::ACC_GRAPHICS_I_CURRENT_TIME)); let last=valid_ms(read_i(g,l::ACC_GRAPHICS_I_LAST_TIME)); let best=valid_ms(read_i(g,l::ACC_GRAPHICS_I_BEST_TIME));
        set(&mut m,"CurrentLap",current);set(&mut m,"CurrentRaceTime",current);set(&mut m,"LastLap",last);set(&mut m,"BestLap",best);
        set(&mut m,"Fuel",rf(p,l::ACC_PHYSICS_FUEL));set(&mut m,"DistanceTraveled",rf(g,l::ACC_GRAPHICS_DISTANCE_TRAVELED));set(&mut m,"RacePosition",read_i(g,l::ACC_GRAPHICS_POSITION));
        let player=player_acc(g);let coordinates=l::ACC_GRAPHICS_CAR_COORDINATES_BASE+player*12;
        set(&mut m,"PositionX",rf(g,coordinates));set(&mut m,"PositionY",rf(g,coordinates+4));set(&mut m,"PositionZ",rf(g,coordinates+8));
        set(&mut m,"Yaw",rf(p,l::ACC_PHYSICS_HEADING));set(&mut m,"Speed",(rf(p,l::ACC_PHYSICS_SPEED_KMH) as f64)/3.6);set(&mut m,"CurrentEngineRpm",read_i(p,l::ACC_PHYSICS_RPMS));
        set(&mut m,"Accel",js_round((rf(p,l::ACC_PHYSICS_GAS) as f64)*255.0));set(&mut m,"Brake",js_round((rf(p,l::ACC_PHYSICS_BRAKE) as f64)*255.0));set(&mut m,"Gear",if read_i(p,l::ACC_PHYSICS_GEAR)<=1 {0.0}else{(read_i(p,l::ACC_PHYSICS_GEAR)-1) as f64});set(&mut m,"Steer",js_round((rf(p,l::ACC_PHYSICS_STEER_ANGLE) as f64)*127.0));
        for (name,offset) in [("TireSurfaceTempInnerFL",l::ACC_PHYSICS_TYRE_TEMP_INNER_FL),("TireSurfaceTempInnerFR",l::ACC_PHYSICS_TYRE_TEMP_INNER_FR),("TireSurfaceTempInnerRL",l::ACC_PHYSICS_TYRE_TEMP_INNER_RL),("TireSurfaceTempInnerRR",l::ACC_PHYSICS_TYRE_TEMP_INNER_RR),("TireSurfaceTempMiddleFL",l::ACC_PHYSICS_TYRE_TEMP_MIDDLE_FL),("TireSurfaceTempMiddleFR",l::ACC_PHYSICS_TYRE_TEMP_MIDDLE_FR),("TireSurfaceTempMiddleRL",l::ACC_PHYSICS_TYRE_TEMP_MIDDLE_RL),("TireSurfaceTempMiddleRR",l::ACC_PHYSICS_TYRE_TEMP_MIDDLE_RR),("TireSurfaceTempOuterFL",l::ACC_PHYSICS_TYRE_TEMP_OUTER_FL),("TireSurfaceTempOuterFR",l::ACC_PHYSICS_TYRE_TEMP_OUTER_FR),("TireSurfaceTempOuterRL",l::ACC_PHYSICS_TYRE_TEMP_OUTER_RL),("TireSurfaceTempOuterRR",l::ACC_PHYSICS_TYRE_TEMP_OUTER_RR)]{set(&mut m,name,rf(p,offset));}
        for (k,o) in [("EngineMaxRpm",l::ACC_PHYSICS_CURRENT_MAX_RPM),("AccelerationX",l::ACC_PHYSICS_ACC_GX),("AccelerationY",l::ACC_PHYSICS_ACC_GY),("AccelerationZ",l::ACC_PHYSICS_ACC_GZ),("VelocityX",l::ACC_PHYSICS_VELOCITY_X),("VelocityY",l::ACC_PHYSICS_VELOCITY_Y),("VelocityZ",l::ACC_PHYSICS_VELOCITY_Z),("AngularVelocityX",l::ACC_PHYSICS_LOCAL_ANGULAR_VEL_X),("AngularVelocityY",l::ACC_PHYSICS_LOCAL_ANGULAR_VEL_Y),("AngularVelocityZ",l::ACC_PHYSICS_LOCAL_ANGULAR_VEL_Z),("Pitch",l::ACC_PHYSICS_PITCH),("Roll",l::ACC_PHYSICS_ROLL),("NormSuspensionTravelFL",l::ACC_PHYSICS_SUSP_TRAVEL_FL),("NormSuspensionTravelFR",l::ACC_PHYSICS_SUSP_TRAVEL_FR),("NormSuspensionTravelRL",l::ACC_PHYSICS_SUSP_TRAVEL_RL),("NormSuspensionTravelRR",l::ACC_PHYSICS_SUSP_TRAVEL_RR),("TireSlipRatioFL",l::ACC_PHYSICS_SLIP_RATIO_FL),("TireSlipRatioFR",l::ACC_PHYSICS_SLIP_RATIO_FR),("TireSlipRatioRL",l::ACC_PHYSICS_SLIP_RATIO_RL),("TireSlipRatioRR",l::ACC_PHYSICS_SLIP_RATIO_RR),("WheelRotationSpeedFL",l::ACC_PHYSICS_WHEEL_ROT_FL),("WheelRotationSpeedFR",l::ACC_PHYSICS_WHEEL_ROT_FR),("WheelRotationSpeedRL",l::ACC_PHYSICS_WHEEL_ROT_RL),("WheelRotationSpeedRR",l::ACC_PHYSICS_WHEEL_ROT_RR),("TireSlipAngleFL",l::ACC_PHYSICS_SLIP_ANGLE_FL),("TireSlipAngleFR",l::ACC_PHYSICS_SLIP_ANGLE_FR),("TireSlipAngleRL",l::ACC_PHYSICS_SLIP_ANGLE_RL),("TireSlipAngleRR",l::ACC_PHYSICS_SLIP_ANGLE_RR),("TireCombinedSlipFL",l::ACC_PHYSICS_WHEEL_SLIP_FL),("TireCombinedSlipFR",l::ACC_PHYSICS_WHEEL_SLIP_FR),("TireCombinedSlipRL",l::ACC_PHYSICS_WHEEL_SLIP_RL),("TireCombinedSlipRR",l::ACC_PHYSICS_WHEEL_SLIP_RR),("SuspensionTravelMFL",l::ACC_PHYSICS_SUSP_TRAVEL_FL),("SuspensionTravelMFR",l::ACC_PHYSICS_SUSP_TRAVEL_FR),("SuspensionTravelMRL",l::ACC_PHYSICS_SUSP_TRAVEL_RL),("SuspensionTravelMRR",l::ACC_PHYSICS_SUSP_TRAVEL_RR),("TireTempFL",l::ACC_PHYSICS_TYRE_TEMP_FL),("TireTempFR",l::ACC_PHYSICS_TYRE_TEMP_FR),("TireTempRL",l::ACC_PHYSICS_TYRE_TEMP_RL),("TireTempRR",l::ACC_PHYSICS_TYRE_TEMP_RR),("TireCarcassTempFL",l::ACC_PHYSICS_TYRE_CORE_FL),("TireCarcassTempFR",l::ACC_PHYSICS_TYRE_CORE_FR),("TireCarcassTempRL",l::ACC_PHYSICS_TYRE_CORE_RL),("TireCarcassTempRR",l::ACC_PHYSICS_TYRE_CORE_RR),("TirePressureFrontLeft",l::ACC_PHYSICS_TYRE_PRESSURE_FL),("TirePressureFrontRight",l::ACC_PHYSICS_TYRE_PRESSURE_FR),("TirePressureRearLeft",l::ACC_PHYSICS_TYRE_PRESSURE_RL),("TirePressureRearRight",l::ACC_PHYSICS_TYRE_PRESSURE_RR),("BrakeTempFrontLeft",l::ACC_PHYSICS_BRAKE_TEMP_FL),("BrakeTempFrontRight",l::ACC_PHYSICS_BRAKE_TEMP_FR),("BrakeTempRearLeft",l::ACC_PHYSICS_BRAKE_TEMP_RL),("BrakeTempRearRight",l::ACC_PHYSICS_BRAKE_TEMP_RR),("TireWearFL",l::ACC_PHYSICS_TYRE_WEAR_FL),("TireWearFR",l::ACC_PHYSICS_TYRE_WEAR_FR),("TireWearRL",l::ACC_PHYSICS_TYRE_WEAR_RL),("TireWearRR",l::ACC_PHYSICS_TYRE_WEAR_RR)] { set(&mut m,k,rf(p,o) as f64); }
        set(&mut m,"EngineMaxRpm",if read_i(p,l::ACC_PHYSICS_CURRENT_MAX_RPM)!=0{read_i(p,l::ACC_PHYSICS_CURRENT_MAX_RPM)as f64}else{read_i(s,l::ACC_STATIC_MAX_RPM)as f64});
        set(&mut m,"EngineIdleRpm",0.0);set(&mut m,"WheelOnRumbleStripFL",0.0);set(&mut m,"WheelOnRumbleStripFR",0.0);set(&mut m,"WheelOnRumbleStripRL",0.0);set(&mut m,"WheelOnRumbleStripRR",0.0);set(&mut m,"WheelInPuddleDepthFL",0.0);set(&mut m,"WheelInPuddleDepthFR",0.0);set(&mut m,"WheelInPuddleDepthRL",0.0);set(&mut m,"WheelInPuddleDepthRR",0.0);set(&mut m,"SurfaceRumbleFL_2",0.0);set(&mut m,"SurfaceRumbleFR_2",0.0);set(&mut m,"SurfaceRumbleRL_2",0.0);set(&mut m,"SurfaceRumbleRR_2",0.0);set(&mut m,"TireSlipCombinedFL_2",0.0);
        set(&mut m,"NormSuspensionTravelFL",if rf(s,l::ACC_STATIC_SUSP_MAX_FL)>0.0{rf(p,l::ACC_PHYSICS_SUSP_TRAVEL_FL) as f64/rf(s,l::ACC_STATIC_SUSP_MAX_FL) as f64}else{0.0});set(&mut m,"NormSuspensionTravelFR",if rf(s,l::ACC_STATIC_SUSP_MAX_FR)>0.0{rf(p,l::ACC_PHYSICS_SUSP_TRAVEL_FR) as f64/rf(s,l::ACC_STATIC_SUSP_MAX_FR) as f64}else{0.0});set(&mut m,"NormSuspensionTravelRL",if rf(s,l::ACC_STATIC_SUSP_MAX_RL)>0.0{rf(p,l::ACC_PHYSICS_SUSP_TRAVEL_RL) as f64/rf(s,l::ACC_STATIC_SUSP_MAX_RL) as f64}else{0.0});set(&mut m,"NormSuspensionTravelRR",if rf(s,l::ACC_STATIC_SUSP_MAX_RR)>0.0{rf(p,l::ACC_PHYSICS_SUSP_TRAVEL_RR) as f64/rf(s,l::ACC_STATIC_SUSP_MAX_RR) as f64}else{0.0});
        set(&mut m,"AccelerationX",(rf(p,l::ACC_PHYSICS_ACC_GX) as f64)*9.81);set(&mut m,"AccelerationY",(rf(p,l::ACC_PHYSICS_ACC_GY) as f64)*9.81);set(&mut m,"AccelerationZ",(rf(p,l::ACC_PHYSICS_ACC_GZ) as f64)*9.81);set(&mut m,"Yaw",rf(p,l::ACC_PHYSICS_HEADING) as f64);set(&mut m,"Pitch",rf(p,l::ACC_PHYSICS_PITCH) as f64);set(&mut m,"Roll",rf(p,l::ACC_PHYSICS_ROLL) as f64);
        let max_fuel=rf(s,l::ACC_STATIC_MAX_FUEL);if max_fuel.is_finite()&&max_fuel>0.0{set(&mut m,"FuelCapacity",max_fuel as f64);}set(&mut m,"Boost",0.0);set(&mut m,"Clutch",0.0);set(&mut m,"HandBrake",0.0);set(&mut m,"NormDrivingLine",0.0);set(&mut m,"NormAIBrakeDiff",0.0);set(&mut m,"TireWearFL",-1.0);set(&mut m,"TireWearFR",-1.0);set(&mut m,"TireWearRL",-1.0);set(&mut m,"TireWearRR",-1.0);set(&mut m,"Power",0.0);set(&mut m,"Torque",0.0);set(&mut m,"CarClass",0.0);set(&mut m,"CarPerformanceIndex",0.0);set(&mut m,"DrivetrainType",1.0);set(&mut m,"NumCylinders",0.0);
        set(&mut m,"TrackTemp",0.0);set(&mut m,"AirTemp",0.0);set(&mut m,"RainPercent",0.0);set(&mut m,"WeatherType",if read_i(g,l::ACC_GRAPHICS_RAIN_TYRES)!=0{3.0}else{0.0});
        set(&mut m,"SurfaceRumbleFL",0.0);set(&mut m,"SurfaceRumbleFR",0.0);set(&mut m,"SurfaceRumbleRL",0.0);set(&mut m,"SurfaceRumbleRR",0.0);
        let mut ext=Map::new(); ext.insert("pitStatus".into(),Value::String((if read_i(g,l::ACC_GRAPHICS_IS_IN_PIT)!=0 {"in_pit"} else if read_i(g,l::ACC_GRAPHICS_IS_IN_PIT_LANE)!=0 {"pit_lane"} else {"out"}).into()));
        ext.insert("flagStatus".into(),Value::String(match read_i(g,l::ACC_GRAPHICS_FLAG){0=>"none",1=>"blue",2=>"yellow",3=>"black",4=>"white",5=>"checkered",6=>"penalty",_=>"none"}.into()));
        ext.insert("currentSectorIndex".into(),num(read_i(g,l::ACC_GRAPHICS_CURRENT_SECTOR_INDEX) as f64)); ext.insert("lastSectorTime".into(),num(read_i(g,l::ACC_GRAPHICS_LAST_SECTOR_TIME) as f64));
        ext.insert("isValidLap".into(),if g.len()>=l::ACC_GRAPHICS_IS_VALID_LAP+4 { match read_i(g,l::ACC_GRAPHICS_IS_VALID_LAP) { 1=>Value::Bool(true),0=>Value::Bool(false),_=>Value::Null }} else {Value::Null});
        ext.insert("sessionType".into(),Value::String(match read_i(g,l::ACC_GRAPHICS_SESSION){0=>"practice",1=>"qualifying",2=>"race",3=>"hotlap",4=>"time-attack",5=>"drift",6=>"drag",7=>"hot-stint",8=>"hotlap-superpole",_=>"unknown"}.into()));
        let penalty=read_i(g,l::ACC_GRAPHICS_PENALTY);ext.insert("penalty".into(),Value::Number(penalty.into()));ext.insert("penaltyTime".into(),num(rf(g,l::ACC_GRAPHICS_PENALTY_TIME)as f64));
        ext.insert("penaltyType".into(),Value::String(match penalty{0=>"none",1=>"drive-through-cutting",2=>"stop-and-go-10-cutting",3=>"stop-and-go-20-cutting",4=>"stop-and-go-30-cutting",5=>"disqualified-cutting",6=>"remove-best-lap-time-cutting",7=>"drive-through-pit-speeding",8=>"stop-and-go-10-pit-speeding",9=>"stop-and-go-20-pit-speeding",10=>"stop-and-go-30-pit-speeding",11=>"disqualified-pit-speeding",12=>"remove-best-lap-time-pit-speeding",13=>"disqualified-ignored-mandatory-pit",14=>"post-race-time",15=>"disqualified-trolling",16=>"disqualified-pit-entry",17=>"disqualified-pit-exit",18=>"disqualified-wrong-way-old",19=>"drive-through-ignored-driver-stint",20=>"disqualified-ignored-driver-stint",21=>"disqualified-exceeded-driver-stint-limit",22=>"disqualified-wrong-way",_=>"unknown"}.into()));
        ext.insert("fuelPerLap".into(),num(rf(g,l::ACC_GRAPHICS_FUEL_XLAP)as f64));ext.insert("windSpeed".into(),num(rf(g,l::ACC_GRAPHICS_WIND_SPEED)as f64));ext.insert("windDirection".into(),num(rf(g,l::ACC_GRAPHICS_WIND_DIRECTION)as f64));
        let compound=wide(g,l::ACC_GRAPHICS_CURRENT_TYRE_COMPOUND,66);ext.insert("tireCompound".into(),Value::String(if compound.is_empty(){if read_i(g,l::ACC_GRAPHICS_RAIN_TYRES)!=0{"wet_compound".into()}else{"dry_compound".into()}}else{compound}));
        for (k,o) in [("tireCoreTemp",[l::ACC_PHYSICS_TYRE_CORE_FL,l::ACC_PHYSICS_TYRE_CORE_FR,l::ACC_PHYSICS_TYRE_CORE_RL,l::ACC_PHYSICS_TYRE_CORE_RR]),("tireInnerTemp",[l::ACC_PHYSICS_TYRE_TEMP_INNER_FL,l::ACC_PHYSICS_TYRE_TEMP_INNER_FR,l::ACC_PHYSICS_TYRE_TEMP_INNER_RL,l::ACC_PHYSICS_TYRE_TEMP_INNER_RR]),("tireMiddleTemp",[l::ACC_PHYSICS_TYRE_TEMP_MIDDLE_FL,l::ACC_PHYSICS_TYRE_TEMP_MIDDLE_FR,l::ACC_PHYSICS_TYRE_TEMP_MIDDLE_RL,l::ACC_PHYSICS_TYRE_TEMP_MIDDLE_RR]),("tireOuterTemp",[l::ACC_PHYSICS_TYRE_TEMP_OUTER_FL,l::ACC_PHYSICS_TYRE_TEMP_OUTER_FR,l::ACC_PHYSICS_TYRE_TEMP_OUTER_RL,l::ACC_PHYSICS_TYRE_TEMP_OUTER_RR]),("tireCamber",[l::ACC_PHYSICS_CAMBER_FL,l::ACC_PHYSICS_CAMBER_FR,l::ACC_PHYSICS_CAMBER_RL,l::ACC_PHYSICS_CAMBER_RR]),("wheelLoad",[l::ACC_PHYSICS_WHEEL_LOAD_FL,l::ACC_PHYSICS_WHEEL_LOAD_FR,l::ACC_PHYSICS_WHEEL_LOAD_RL,l::ACC_PHYSICS_WHEEL_LOAD_RR]),("brakePadWear",[l::ACC_PHYSICS_PAD_LIFE_FL,l::ACC_PHYSICS_PAD_LIFE_FR,l::ACC_PHYSICS_PAD_LIFE_RL,l::ACC_PHYSICS_PAD_LIFE_RR])] {
            ext.insert(k.into(),Value::Array(o.iter().map(|offset|num(rf(p,*offset) as f64)).collect()));
        }
        ext.insert("rideHeight".into(),Value::Array(vec![num(rf(p,l::ACC_PHYSICS_RIDE_HEIGHT_F)as f64),num(rf(p,l::ACC_PHYSICS_RIDE_HEIGHT_R)as f64)]));
        ext.insert("cgHeight".into(),num(rf(p,l::ACC_PHYSICS_CG_HEIGHT)as f64));ext.insert("tireRadius".into(),Value::Array([l::ACC_STATIC_TYRE_RADIUS_FL,l::ACC_STATIC_TYRE_RADIUS_FR,l::ACC_STATIC_TYRE_RADIUS_RL,l::ACC_STATIC_TYRE_RADIUS_RR].iter().map(|o|num(rf(s,*o)as f64)).collect()));
        ext.insert("tireContactHeading".into(),Value::Array((0..4).map(|i|Value::Array((0..3).map(|j|num(rf(p,l::ACC_PHYSICS_CONTACT_HEADING_BASE+i*12+j*4)as f64)).collect())).collect()));
        ext.insert("brakePadCompound".into(),Value::Number(0.into()));ext.insert("tc".into(),Value::Number(read_i(g,l::ACC_GRAPHICS_TC_GRAPHICS).into()));ext.insert("tcCut".into(),Value::Number(read_i(g,l::ACC_GRAPHICS_TC_CUT).into()));ext.insert("abs".into(),Value::Number(read_i(g,l::ACC_GRAPHICS_ABS_GRAPHICS).into()));ext.insert("engineMap".into(),Value::Number(read_i(g,l::ACC_GRAPHICS_ENGINE_MAP).into()));ext.insert("brakeBias".into(),num(rf(p,l::ACC_PHYSICS_BRAKE_BIAS)as f64));
        ext.insert("tcIntervention".into(),Value::Number(((rf(p,l::ACC_PHYSICS_TC)>0.01)as i32).into()));ext.insert("absIntervention".into(),Value::Number(((rf(p,l::ACC_PHYSICS_ABS)>0.01)as i32).into()));ext.insert("tcRaw".into(),num(rf(p,l::ACC_PHYSICS_TC)as f64));ext.insert("absRaw".into(),num(rf(p,l::ACC_PHYSICS_ABS)as f64));ext.insert("slipVibrations".into(),num(rf(p,l::ACC_PHYSICS_SLIP_VIBRATIONS)as f64));ext.insert("absVibrations".into(),num(rf(p,l::ACC_PHYSICS_ABS_VIBRATIONS)as f64));
        ext.insert("rainIntensity".into(),Value::Number(0.into()));ext.insert("trackGripStatus".into(),Value::String("unknown".into()));ext.insert("drsAvailable".into(),Value::Bool(false));ext.insert("drsEnabled".into(),Value::Bool(false));
        ext.insert("carDamage".into(),serde_json::json!({"front":rf(p,l::ACC_PHYSICS_DAM_FRONT),"rear":rf(p,l::ACC_PHYSICS_DAM_REAR),"left":rf(p,l::ACC_PHYSICS_DAM_LEFT),"right":rf(p,l::ACC_PHYSICS_DAM_RIGHT),"centre":rf(p,l::ACC_PHYSICS_DAM_CENTRE)}));
        ext.insert("airTempC".into(),if p.len()>=l::ACC_PHYSICS_AIR_TEMP+4{num(rf(p,l::ACC_PHYSICS_AIR_TEMP)as f64)}else{Value::Null});ext.insert("roadTempC".into(),if p.len()>=l::ACC_PHYSICS_ROAD_TEMP+4{num(rf(p,l::ACC_PHYSICS_ROAD_TEMP)as f64)}else{Value::Null});
        m.insert("acc".into(),Value::Object(ext));
        self.car_ordinal=car;self.track_ordinal=track;
        Ok(Some(Value::Object(m)))
    }
    fn evo(&mut self,p:&[u8],g:&[u8],s:&[u8],_car:i64,_track:i64,t:u64)->Result<Option<Value>,String>{
        use crate::games::generated::layouts as l;
        if p.len()<l::EVO_PHYSICS_SIZE||g.len()<l::EVO_GRAPHICS_EVO_SIZE||s.len()<l::EVO_STATIC_EVO_SIZE{return Ok(None)};
        let status=read_i(g,l::EVO_GRAPHICS_EVO_STATUS); if status==0||status==1{return Ok(None)};
        let model=cstr(g,l::EVO_GRAPHICS_EVO_CAR_MODEL,33);let track_name=cstr(s,l::EVO_STATIC_EVO_TRACK,33);let config=cstr(s,l::EVO_STATIC_EVO_TRACK_CONFIGURATION,33);
        if !model.is_empty()&&model!=self.last_car {self.last_car=model.clone();self.car_ordinal=crate::games::catalog::resolve_evo_car(&model).and_then(|v|v.get("id").and_then(Value::as_i64)).unwrap_or(-1);}
        let key=format!("{track_name}|{config}");if !track_name.is_empty()&&key!=self.last_track {self.last_track=key;self.track_ordinal=crate::games::catalog::resolve_evo_track(&track_name,&config).and_then(|v|v.get("id").and_then(Value::as_i64)).unwrap_or(-1);}
        let slot=player_slot(&mut self.evo_slot,p,g,read_u8(g,l::EVO_GRAPHICS_EVO_ACTIVE_CARS) as usize);
        let packet=read_i(p,l::EVO_PHYSICS_PACKET_ID);let speed=((rf(p,l::EVO_PHYSICS_SPEED_KMH) as f64)/3.6);let km=rf(g,l::EVO_GRAPHICS_EVO_CURRENT_KM) as f64;let laps=read_i(g,l::EVO_GRAPHICS_EVO_TOTAL_LAP_COUNT);
        let dist=integrate(&mut self.evo_distance,packet,speed,km,laps);
        let mut m=Map::new();base(&mut m,"ac-evo",t,self.car_ordinal,self.track_ordinal,laps+1,status==2);
        for (key,val) in [("Fuel",rf(p,l::EVO_PHYSICS_FUEL) as f64),("DistanceTraveled",dist),("Speed",speed),("CurrentEngineRpm",read_i(p,l::EVO_PHYSICS_RPMS) as f64),("PositionX",rf(g,l::EVO_GRAPHICS_EVO_CAR_COORDINATES_BASE+slot*12) as f64),("PositionY",rf(g,l::EVO_GRAPHICS_EVO_CAR_COORDINATES_BASE+slot*12+4) as f64),("PositionZ",rf(g,l::EVO_GRAPHICS_EVO_CAR_COORDINATES_BASE+slot*12+8) as f64),("Yaw",rf(p,l::EVO_PHYSICS_HEADING) as f64)] {set(&mut m,key,val)}
        let current=valid_ms(read_i(g,l::EVO_GRAPHICS_EVO_CURRENT_LAP_TIME_MS));let last=valid_ms(read_i(g,l::EVO_GRAPHICS_EVO_LAST_LAPTIME_MS));let best=valid_ms(read_i(g,l::EVO_GRAPHICS_EVO_BEST_LAPTIME_MS));set(&mut m,"CurrentLap",current);set(&mut m,"CurrentRaceTime",current);set(&mut m,"LastLap",last);set(&mut m,"BestLap",best);
        for (k,o) in [("AccelerationX",l::EVO_PHYSICS_ACC_GX),("AccelerationY",l::EVO_PHYSICS_ACC_GY),("AccelerationZ",l::EVO_PHYSICS_ACC_GZ),("VelocityX",l::EVO_PHYSICS_VELOCITY_X),("VelocityY",l::EVO_PHYSICS_VELOCITY_Y),("VelocityZ",l::EVO_PHYSICS_VELOCITY_Z),("AngularVelocityX",l::EVO_PHYSICS_LOCAL_ANGULAR_VEL_X),("AngularVelocityY",l::EVO_PHYSICS_LOCAL_ANGULAR_VEL_Y),("AngularVelocityZ",l::EVO_PHYSICS_LOCAL_ANGULAR_VEL_Z),("Pitch",l::EVO_PHYSICS_PITCH),("Roll",l::EVO_PHYSICS_ROLL),("TireSlipRatioFL",l::EVO_PHYSICS_SLIP_RATIO_FL),("TireSlipRatioFR",l::EVO_PHYSICS_SLIP_RATIO_FR),("TireSlipRatioRL",l::EVO_PHYSICS_SLIP_RATIO_RL),("TireSlipRatioRR",l::EVO_PHYSICS_SLIP_RATIO_RR),("WheelRotationSpeedFL",l::EVO_PHYSICS_WHEEL_ROT_FL),("WheelRotationSpeedFR",l::EVO_PHYSICS_WHEEL_ROT_FR),("WheelRotationSpeedRL",l::EVO_PHYSICS_WHEEL_ROT_RL),("WheelRotationSpeedRR",l::EVO_PHYSICS_WHEEL_ROT_RR),("TireSlipAngleFL",l::EVO_PHYSICS_SLIP_ANGLE_FL),("TireSlipAngleFR",l::EVO_PHYSICS_SLIP_ANGLE_FR),("TireSlipAngleRL",l::EVO_PHYSICS_SLIP_ANGLE_RL),("TireSlipAngleRR",l::EVO_PHYSICS_SLIP_ANGLE_RR),("TireCombinedSlipFL",l::EVO_PHYSICS_WHEEL_SLIP_FL),("TireCombinedSlipFR",l::EVO_PHYSICS_WHEEL_SLIP_FR),("TireCombinedSlipRL",l::EVO_PHYSICS_WHEEL_SLIP_RL),("TireCombinedSlipRR",l::EVO_PHYSICS_WHEEL_SLIP_RR),("SuspensionTravelMFL",l::EVO_PHYSICS_SUSP_TRAVEL_FL),("SuspensionTravelMFR",l::EVO_PHYSICS_SUSP_TRAVEL_FR),("SuspensionTravelMRL",l::EVO_PHYSICS_SUSP_TRAVEL_RL),("SuspensionTravelMRR",l::EVO_PHYSICS_SUSP_TRAVEL_RR),("TireCarcassTempFL",l::EVO_PHYSICS_TYRE_CORE_FL),("TireCarcassTempFR",l::EVO_PHYSICS_TYRE_CORE_FR),("TireCarcassTempRL",l::EVO_PHYSICS_TYRE_CORE_RL),("TireCarcassTempRR",l::EVO_PHYSICS_TYRE_CORE_RR),("TirePressureFrontLeft",l::EVO_PHYSICS_TYRE_PRESSURE_FL),("TirePressureFrontRight",l::EVO_PHYSICS_TYRE_PRESSURE_FR),("TirePressureRearLeft",l::EVO_PHYSICS_TYRE_PRESSURE_RL),("TirePressureRearRight",l::EVO_PHYSICS_TYRE_PRESSURE_RR),("BrakeTempFrontLeft",l::EVO_PHYSICS_BRAKE_TEMP_FL),("BrakeTempFrontRight",l::EVO_PHYSICS_BRAKE_TEMP_FR),("BrakeTempRearLeft",l::EVO_PHYSICS_BRAKE_TEMP_RL),("BrakeTempRearRight",l::EVO_PHYSICS_BRAKE_TEMP_RR),("TireWearFL",l::EVO_PHYSICS_TYRE_WEAR_FL),("TireWearFR",l::EVO_PHYSICS_TYRE_WEAR_FR),("TireWearRL",l::EVO_PHYSICS_TYRE_WEAR_RL),("TireWearRR",l::EVO_PHYSICS_TYRE_WEAR_RR)] {set(&mut m,k,rf(p,o) as f64);}
        let tire_bases=[l::EVO_GRAPHICS_EVO_TYRE_LF_BASE,l::EVO_GRAPHICS_EVO_TYRE_RF_BASE,l::EVO_GRAPHICS_EVO_TYRE_LR_BASE,l::EVO_GRAPHICS_EVO_TYRE_RR_BASE];
        for (k,o) in [("TireTempFL",tire_bases[0]+l::EVO_TYRE_STATE_TEMPERATURE_CENTER),("TireTempFR",tire_bases[1]+l::EVO_TYRE_STATE_TEMPERATURE_CENTER),("TireTempRL",tire_bases[2]+l::EVO_TYRE_STATE_TEMPERATURE_CENTER),("TireTempRR",tire_bases[3]+l::EVO_TYRE_STATE_TEMPERATURE_CENTER)] {set(&mut m,k,rf(g,o) as f64);}
        for (key, offset) in [("TireSurfaceTempInnerFL",tire_bases[0]+l::EVO_TYRE_STATE_TEMPERATURE_RIGHT),("TireSurfaceTempInnerFR",tire_bases[1]+l::EVO_TYRE_STATE_TEMPERATURE_LEFT),("TireSurfaceTempInnerRL",tire_bases[2]+l::EVO_TYRE_STATE_TEMPERATURE_RIGHT),("TireSurfaceTempInnerRR",tire_bases[3]+l::EVO_TYRE_STATE_TEMPERATURE_LEFT),("TireSurfaceTempMiddleFL",tire_bases[0]+l::EVO_TYRE_STATE_TEMPERATURE_CENTER),("TireSurfaceTempMiddleFR",tire_bases[1]+l::EVO_TYRE_STATE_TEMPERATURE_CENTER),("TireSurfaceTempMiddleRL",tire_bases[2]+l::EVO_TYRE_STATE_TEMPERATURE_CENTER),("TireSurfaceTempMiddleRR",tire_bases[3]+l::EVO_TYRE_STATE_TEMPERATURE_CENTER),("TireSurfaceTempOuterFL",tire_bases[0]+l::EVO_TYRE_STATE_TEMPERATURE_LEFT),("TireSurfaceTempOuterFR",tire_bases[1]+l::EVO_TYRE_STATE_TEMPERATURE_RIGHT),("TireSurfaceTempOuterRL",tire_bases[2]+l::EVO_TYRE_STATE_TEMPERATURE_LEFT),("TireSurfaceTempOuterRR",tire_bases[3]+l::EVO_TYRE_STATE_TEMPERATURE_RIGHT)] { let value=rf(g,offset); if value>0.0 { set(&mut m,key,value as f64); } }
        set(&mut m,"EngineMaxRpm",read_i(p,l::EVO_PHYSICS_CURRENT_MAX_RPM) as f64);
        set(&mut m,"EngineIdleRpm",0.0);set(&mut m,"AccelerationX",(rf(p,l::EVO_PHYSICS_ACC_GX) as f64)*9.81);set(&mut m,"AccelerationY",(rf(p,l::EVO_PHYSICS_ACC_GY) as f64)*9.81);set(&mut m,"AccelerationZ",(rf(p,l::EVO_PHYSICS_ACC_GZ) as f64)*9.81);
        set(&mut m,"NormSuspensionTravelFL",(0.5+rf(p,l::EVO_PHYSICS_SUSP_TRAVEL_FL) as f64/0.1).clamp(0.0,1.0));set(&mut m,"NormSuspensionTravelFR",(0.5+rf(p,l::EVO_PHYSICS_SUSP_TRAVEL_FR) as f64/0.1).clamp(0.0,1.0));set(&mut m,"NormSuspensionTravelRL",(0.5+rf(p,l::EVO_PHYSICS_SUSP_TRAVEL_RL) as f64/0.1).clamp(0.0,1.0));set(&mut m,"NormSuspensionTravelRR",(0.5+rf(p,l::EVO_PHYSICS_SUSP_TRAVEL_RR) as f64/0.1).clamp(0.0,1.0));
        set(&mut m,"Accel",js_round((rf(p,l::EVO_PHYSICS_GAS) as f64)*255.0));set(&mut m,"Brake",js_round((rf(p,l::EVO_PHYSICS_BRAKE) as f64)*255.0));set(&mut m,"Gear",if read_i(p,l::EVO_PHYSICS_GEAR)<=1{0.0}else{(read_i(p,l::EVO_PHYSICS_GEAR)-1)as f64});set(&mut m,"Steer",js_round((rf(p,l::EVO_PHYSICS_STEER_ANGLE) as f64)*127.0));set(&mut m,"Clutch",0.0);set(&mut m,"HandBrake",0.0);set(&mut m,"Boost",0.0);set(&mut m,"NormDrivingLine",0.0);set(&mut m,"NormAIBrakeDiff",0.0);
        for k in ["WheelOnRumbleStripFL","WheelOnRumbleStripFR","WheelOnRumbleStripRL","WheelOnRumbleStripRR","WheelInPuddleDepthFL","WheelInPuddleDepthFR","WheelInPuddleDepthRL","WheelInPuddleDepthRR","SurfaceRumbleFL_2","SurfaceRumbleFR_2","SurfaceRumbleRL_2","SurfaceRumbleRR_2","TireSlipCombinedFL_2","SurfaceRumbleFL","SurfaceRumbleFR","SurfaceRumbleRL","SurfaceRumbleRR"]{set(&mut m,k,0.0)}
        let max_fuel=rf(g,l::EVO_GRAPHICS_EVO_MAX_FUEL);if max_fuel.is_finite()&&max_fuel>0.0{set(&mut m,"FuelCapacity",max_fuel as f64);}set(&mut m,"Power",0.0);set(&mut m,"Torque",0.0);set(&mut m,"CarClass",0.0);set(&mut m,"CarPerformanceIndex",0.0);set(&mut m,"DrivetrainType",1.0);set(&mut m,"NumCylinders",0.0);set(&mut m,"WeatherType",0.0);set(&mut m,"TrackTemp",rf(s,l::EVO_STATIC_EVO_STARTING_GROUND_TEMPERATURE_C) as f64);set(&mut m,"AirTemp",rf(s,l::EVO_STATIC_EVO_STARTING_AMBIENT_TEMPERATURE_C) as f64);set(&mut m,"RainPercent",0.0);
        if self.car_ordinal<0&&!self.last_car.is_empty(){m.insert("carModelName".into(),Value::String(self.last_car.clone()));}
        let mut ext=Map::new();let pit_box=read_u8(g,l::EVO_GRAPHICS_EVO_IS_IN_PIT_BOX)!=0;let pit_lane=read_u8(g,l::EVO_GRAPHICS_EVO_IS_IN_PIT_LANE)!=0;let location=read_i(g,l::EVO_GRAPHICS_EVO_CAR_LOCATION);
        ext.insert("pitStatus".into(),Value::String((if pit_box||location==0 {"in_pit"} else if pit_lane||location==1 {"pit_lane"} else {"out"}).into()));
        ext.insert("isValidLap".into(),if read_u8(g,l::EVO_GRAPHICS_EVO_IS_VALID_LAP)!=0 {Value::Bool(true)}else if pit_lane||pit_box {Value::Null}else{Value::Bool(false)});
        ext.insert("tireCompound".into(),Value::String({let v=cstr(g,l::EVO_GRAPHICS_EVO_TYRE_LF_BASE+l::EVO_GRAPHICS_EVO_TYRE_COMPOUND_OFFSET,33);if v.is_empty(){"dry_compound".to_owned()}else{v}}));
        ext.insert("tireCoreTemp".into(),Value::Array([l::EVO_PHYSICS_TYRE_CORE_FL,l::EVO_PHYSICS_TYRE_CORE_FR,l::EVO_PHYSICS_TYRE_CORE_RL,l::EVO_PHYSICS_TYRE_CORE_RR].iter().map(|o|num(rf(p,*o)as f64)).collect()));
        ext.insert("tireCamber".into(),Value::Array([l::EVO_PHYSICS_CAMBER_FL,l::EVO_PHYSICS_CAMBER_FR,l::EVO_PHYSICS_CAMBER_RL,l::EVO_PHYSICS_CAMBER_RR].iter().map(|o|num(rf(p,*o)as f64)).collect()));
        ext.insert("wheelLoad".into(),Value::Array([l::EVO_PHYSICS_WHEEL_LOAD_FL,l::EVO_PHYSICS_WHEEL_LOAD_FR,l::EVO_PHYSICS_WHEEL_LOAD_RL,l::EVO_PHYSICS_WHEEL_LOAD_RR].iter().map(|o|num(rf(p,*o)as f64)).collect()));
        ext.insert("brakePadWear".into(),Value::Array([l::EVO_PHYSICS_PAD_LIFE_FL,l::EVO_PHYSICS_PAD_LIFE_FR,l::EVO_PHYSICS_PAD_LIFE_RL,l::EVO_PHYSICS_PAD_LIFE_RR].iter().map(|o|num(rf(p,*o)as f64)).collect()));
        for (name,offs) in [("tireInnerTemp",[tire_bases[0]+l::EVO_TYRE_STATE_TEMPERATURE_RIGHT,tire_bases[1]+l::EVO_TYRE_STATE_TEMPERATURE_LEFT,tire_bases[2]+l::EVO_TYRE_STATE_TEMPERATURE_RIGHT,tire_bases[3]+l::EVO_TYRE_STATE_TEMPERATURE_LEFT]),("tireMiddleTemp",[tire_bases[0]+l::EVO_TYRE_STATE_TEMPERATURE_CENTER,tire_bases[1]+l::EVO_TYRE_STATE_TEMPERATURE_CENTER,tire_bases[2]+l::EVO_TYRE_STATE_TEMPERATURE_CENTER,tire_bases[3]+l::EVO_TYRE_STATE_TEMPERATURE_CENTER]),("tireOuterTemp",[tire_bases[0]+l::EVO_TYRE_STATE_TEMPERATURE_LEFT,tire_bases[1]+l::EVO_TYRE_STATE_TEMPERATURE_RIGHT,tire_bases[2]+l::EVO_TYRE_STATE_TEMPERATURE_LEFT,tire_bases[3]+l::EVO_TYRE_STATE_TEMPERATURE_RIGHT])] {ext.insert(name.into(),Value::Array(offs.iter().map(|o|num(rf(g,*o)as f64)).collect()));}
        ext.insert("cgHeight".into(),num(rf(p,l::EVO_PHYSICS_CG_HEIGHT)as f64));ext.insert("tireRadius".into(),Value::Array(vec![0.into(),0.into(),0.into(),0.into()]));
        ext.insert("tireContactHeading".into(),Value::Array((0..4).map(|i|Value::Array((0..3).map(|j|num(rf(p,l::EVO_PHYSICS_CONTACT_HEADING_BASE+i*12+j*4)as f64)).collect())).collect()));
        let elec=l::EVO_GRAPHICS_EVO_ELECTRONICS_BASE;
        ext.insert("brakePadCompound".into(),Value::Number(0.into()));ext.insert("tc".into(),Value::Number((read_u8(g,elec+l::EVO_ELECTRONICS_TC_LEVEL)as i8 as i64).into()));ext.insert("tcCut".into(),Value::Number((read_u8(g,elec+l::EVO_ELECTRONICS_TC_CUT_LEVEL)as i8 as i64).into()));ext.insert("abs".into(),Value::Number((read_u8(g,elec+l::EVO_ELECTRONICS_ABS_LEVEL)as i8 as i64).into()));ext.insert("engineMap".into(),Value::Number((read_u8(g,elec+l::EVO_ELECTRONICS_ENGINE_MAP_LEVEL)as i8 as i64).into()));ext.insert("brakeBias".into(),num(rf(p,l::EVO_PHYSICS_BRAKE_BIAS)as f64));
        ext.insert("tcIntervention".into(),Value::Number(((read_u8(g,l::EVO_GRAPHICS_EVO_TC_ACTIVE)!=0) as i32).into()));ext.insert("absIntervention".into(),Value::Number(((read_u8(g,l::EVO_GRAPHICS_EVO_ABS_ACTIVE)!=0) as i32).into()));ext.insert("tcRaw".into(),num(rf(p,l::EVO_PHYSICS_TC)as f64));ext.insert("absRaw".into(),num(rf(p,l::EVO_PHYSICS_ABS)as f64));ext.insert("slipVibrations".into(),num(rf(p,l::EVO_PHYSICS_SLIP_VIBRATIONS)as f64));ext.insert("absVibrations".into(),num(rf(p,l::EVO_PHYSICS_ABS_VIBRATIONS)as f64));
        ext.insert("rainIntensity".into(),Value::Number(0.into()));ext.insert("trackGripStatus".into(),Value::String("unknown".into()));ext.insert("windSpeed".into(),Value::Number(0.into()));ext.insert("windDirection".into(),Value::Number(0.into()));ext.insert("drsAvailable".into(),Value::Bool(false));ext.insert("drsEnabled".into(),Value::Bool(false));
        ext.insert("fuelPerLap".into(),num(rf(g,l::EVO_GRAPHICS_EVO_FUEL_PER_LAP)as f64));ext.insert("currentSectorIndex".into(),Value::Number((-1).into()));ext.insert("lastSectorTime".into(),Value::Number(0.into()));
        ext.insert("airTempC".into(),if p.len()>=l::EVO_PHYSICS_AIR_TEMP+4{num(rf(p,l::EVO_PHYSICS_AIR_TEMP)as f64)}else{Value::Null});ext.insert("roadTempC".into(),if p.len()>=l::EVO_PHYSICS_ROAD_TEMP+4{num(rf(p,l::EVO_PHYSICS_ROAD_TEMP)as f64)}else{Value::Null});
        let mut evo=Map::new();evo.insert("physicsPacketId".into(),Value::Number(read_i(p,l::EVO_PHYSICS_PACKET_ID).into()));evo.insert("graphicsPacketId".into(),Value::Number(read_i(g,l::EVO_GRAPHICS_EVO_PACKET_ID).into()));evo.insert("acEvoVersion".into(),Value::String(cstr(s,l::EVO_STATIC_EVO_AC_EVO_VERSION,15)));
        evo.insert("sessionName".into(),Value::String(cstr(s,l::EVO_STATIC_EVO_SESSION_NAME,33)));evo.insert("isStaticWeather".into(),Value::Bool(read_u8(s,l::EVO_STATIC_EVO_IS_STATIC_WEATHER)!=0));evo.insert("isTimedRace".into(),Value::Bool(read_u8(s,l::EVO_STATIC_EVO_IS_TIMED_RACE)!=0));evo.insert("isOnline".into(),Value::Bool(read_u8(s,l::EVO_STATIC_EVO_IS_ONLINE)!=0));evo.insert("numberOfSessions".into(),Value::Number(read_i(s,l::EVO_STATIC_EVO_NUMBER_OF_SESSIONS).into()));
        let session=read_i(s,l::EVO_STATIC_EVO_SESSION);evo.insert("sessionType".into(),Value::String(match session{0=>"time_attack",1=>"race",2=>"hot_stint",3=>"cruise",-1=>"unknown",_=>"unknown"}.into()));
        let grip=read_i(s,l::EVO_STATIC_EVO_STARTING_GRIP);evo.insert("startingGrip".into(),Value::String(match grip{0=>"green",1=>"fast",2=>"optimum",_=>"unknown"}.into()));
        let session_base=l::EVO_GRAPHICS_EVO_SESSION_STATE_BASE;
        let timing_base=l::EVO_GRAPHICS_EVO_TIMING_STATE_BASE;
        evo.insert("deltaCurrent".into(),Value::String(cstr(g,timing_base+l::EVO_TIMING_STATE_DELTA_CURRENT,15)));evo.insert("deltaLast".into(),Value::String(cstr(g,timing_base+l::EVO_TIMING_STATE_DELTA_LAST,15)));evo.insert("idealLapTime".into(),Value::String(cstr(g,timing_base+l::EVO_TIMING_STATE_IDEAL_LAPTIME,15)));evo.insert("timingIsInvalid".into(),Value::Bool(read_u8(g,timing_base+l::EVO_TIMING_STATE_IS_INVALID)!=0));
        let flag=read_i(g,l::EVO_GRAPHICS_EVO_FLAG);
        let elec=l::EVO_GRAPHICS_EVO_ELECTRONICS_BASE;
        evo.insert("escLevel".into(),Value::Number((read_u8(g,elec+l::EVO_ELECTRONICS_ESC_LEVEL)as i8 as i64).into()));evo.insert("isDrsOpen".into(),Value::Bool(read_u8(g,elec+l::EVO_ELECTRONICS_IS_DRS_OPEN)!=0));
        evo.insert("engineMapLevel".into(),Value::Number((read_u8(g,elec+l::EVO_ELECTRONICS_ENGINE_MAP_LEVEL) as i8 as i64).into()));
        evo.insert("tyreMiddleTempC".into(),Value::Array(tire_bases.iter().map(|o|num(rf(g,*o+l::EVO_TYRE_STATE_TEMPERATURE_CENTER)as f64)).collect()));
        evo.insert("clutchPercent".into(),num(rf(g,l::EVO_GRAPHICS_EVO_CLUTCH_PERCENT)as f64));evo.insert("handbrakePercent".into(),num(rf(g,l::EVO_GRAPHICS_EVO_HANDBRAKE_PERCENT)as f64));evo.insert("waterTempC".into(),num(rf(p,l::EVO_PHYSICS_WATER_TEMP)as f64));evo.insert("oilTempC".into(),num(rf(g,l::EVO_GRAPHICS_EVO_OIL_TEMPERATURE_C)as f64));evo.insert("oilPressureBar".into(),num(rf(g,l::EVO_GRAPHICS_EVO_OIL_PRESSURE_BAR)as f64));evo.insert("exhaustTempC".into(),num(rf(g,l::EVO_GRAPHICS_EVO_EXHAUST_TEMPERATURE_C)as f64));evo.insert("turboBoost".into(),num(rf(g,l::EVO_GRAPHICS_EVO_TURBO_BOOST)as f64));evo.insert("currentTorque".into(),num(rf(g,l::EVO_GRAPHICS_EVO_CURRENT_TORQUE)as f64));evo.insert("currentBhp".into(),Value::Number(read_i(g,l::EVO_GRAPHICS_EVO_CURRENT_BHP).into()));evo.insert("isWrongWay".into(),Value::Bool(read_u8(g,l::EVO_GRAPHICS_EVO_IS_WRONG_WAY)!=0));
        evo.insert("instantaneousKmPerLiter".into(),num(rf(g,l::EVO_GRAPHICS_EVO_INSTANTANEOUS_KM_PER_FUEL_LITER)as f64));
        m.insert("RacePosition".into(),Value::Number((u32le(g,l::EVO_GRAPHICS_EVO_CURRENT_POS).unwrap_or(0)as u64).into()));
        ext.insert("flagStatus".into(),Value::String(match flag{0=>"none",1=>"white",2=>"green",3=>"red",4=>"blue",5=>"yellow",6=>"black",7=>"black_white",8=>"checkered",9=>"orange_circle",10=>"red_yellow_stripes",_=>"none"}.into()));
        ext.insert("normalizedCarPosition".into(),num(rf(g,l::EVO_GRAPHICS_EVO_NPOS)as f64));ext.insert("trackLengthM".into(),num(rf(s,l::EVO_STATIC_EVO_TRACK_LENGTH_M)as f64));
        ext.insert("carDamage".into(),serde_json::json!({"front":rf(p,l::EVO_PHYSICS_DAM_FRONT),"rear":rf(p,l::EVO_PHYSICS_DAM_REAR),"left":rf(p,l::EVO_PHYSICS_DAM_LEFT),"right":rf(p,l::EVO_PHYSICS_DAM_RIGHT),"centre":rf(p,l::EVO_PHYSICS_DAM_CENTRE)}));
        evo.insert("airTempC".into(),num(rf(p,l::EVO_PHYSICS_AIR_TEMP)as f64));evo.insert("roadTempC".into(),num(rf(p,l::EVO_PHYSICS_ROAD_TEMP)as f64));evo.insert("deltaTimeMs".into(),Value::Number(read_i(g,l::EVO_GRAPHICS_EVO_DELTA_TIME_MS).into()));evo.insert("predictedLapTimeMs".into(),Value::Number(read_i(g,l::EVO_GRAPHICS_EVO_PREDICTED_LAP_TIME_MS).into()));
        evo.insert("sessionTimeLeftMs".into(),Value::Number(read_i(g,session_base+l::EVO_SESSION_STATE_TIME_LEFT_MS).into()));evo.insert("sessionTotalLaps".into(),Value::Number(read_i(g,session_base+l::EVO_SESSION_STATE_TOTAL_LAP).into()));evo.insert("sessionCurrentLap".into(),Value::Number(read_i(g,session_base+l::EVO_SESSION_STATE_CURRENT_LAP).into()));evo.insert("lapLengthKm".into(),num(rf(g,session_base+l::EVO_SESSION_STATE_LAP_LENGTH_KM)as f64));
        evo.insert("fuelLiters".into(),num(rf(g,l::EVO_GRAPHICS_EVO_FUEL_LITER_CURRENT_QUANTITY)as f64));evo.insert("fuelPercent".into(),num(rf(g,l::EVO_GRAPHICS_EVO_FUEL_LITER_CURRENT_QUANTITY_PERCENT)as f64));evo.insert("fuelLitersPerLap".into(),num(rf(g,l::EVO_GRAPHICS_EVO_FUEL_LITER_PER_LAP)as f64));evo.insert("fuelLitersUsed".into(),num(rf(g,l::EVO_GRAPHICS_EVO_FUEL_LITER_USED)as f64));evo.insert("lapsPossibleWithFuel".into(),num(rf(g,l::EVO_GRAPHICS_EVO_LAPS_POSSIBLE_WITH_FUEL)as f64));evo.insert("kmPerFuelLiter".into(),num(rf(g,l::EVO_GRAPHICS_EVO_KM_PER_FUEL_LITER)as f64));
        evo.insert("brakeDiscLife".into(),Value::Array([l::EVO_PHYSICS_DISC_LIFE_FL,l::EVO_PHYSICS_DISC_LIFE_FR,l::EVO_PHYSICS_DISC_LIFE_RL,l::EVO_PHYSICS_DISC_LIFE_RR].iter().map(|o|num(rf(p,*o)as f64)).collect()));evo.insert("localVelocity".into(),Value::Array(vec![num(rf(p,l::EVO_PHYSICS_LOCAL_VELOCITY_X)as f64),num(rf(p,l::EVO_PHYSICS_LOCAL_VELOCITY_Y)as f64),num(rf(p,l::EVO_PHYSICS_LOCAL_VELOCITY_Z)as f64)]));
        evo.insert("gapAheadMs".into(),num(rf(g,l::EVO_GRAPHICS_EVO_GAP_AHEAD)as f64));evo.insert("gapBehindMs".into(),num(rf(g,l::EVO_GRAPHICS_EVO_GAP_BEHIND)as f64));evo.insert("sessionKm".into(),num(km));evo.insert("totalDrivingTimeS".into(),Value::Number((u32le(g,l::EVO_GRAPHICS_EVO_TOTAL_DRIVING_TIME_S).unwrap_or(0)as u64).into()));
        evo.insert("timeOfDayHours".into(),Value::Number(read_i(g,l::EVO_GRAPHICS_EVO_TIME_OF_DAY_HOURS).into()));evo.insert("timeOfDayMinutes".into(),Value::Number(read_i(g,l::EVO_GRAPHICS_EVO_TIME_OF_DAY_MINUTES).into()));evo.insert("timeOfDaySeconds".into(),Value::Number(read_i(g,l::EVO_GRAPHICS_EVO_TIME_OF_DAY_SECONDS).into()));
        ext.insert("acEvo".into(),Value::Object(evo));m.insert("acc".into(),Value::Object(ext));Ok(Some(Value::Object(m)))
    }
}
fn part(b:&[u8],o:usize)->Option<(&[u8],usize)>{let n=u32le(b,o)? as usize;let start=o.checked_add(4)?;let end=start.checked_add(n)?;Some((b.get(start..end)?,end))}
fn u32le(b:&[u8],o:usize)->Option<u32>{Some(u32::from_le_bytes(b.get(o..o.checked_add(4)?)?.try_into().ok()?))}
fn i32le(b:&[u8],o:usize)->Option<i32>{Some(i32::from_le_bytes(b.get(o..o.checked_add(4)?)?.try_into().ok()?))}
fn read_i(b:&[u8],o:usize)->i32{i32le(b,o).unwrap_or(0)}
fn read_u8(b:&[u8],o:usize)->u8{b.get(o).copied().unwrap_or(0)}
fn rf(b:&[u8],o:usize)->f32{u32le(b,o).map(f32::from_bits).unwrap_or(0.0)}
fn num(v:f64)->Value{Number::from_f64(v).map(Value::Number).unwrap_or(Value::Null)}
fn js_round(v:f64)->f64{(v+0.5).floor()}
fn set<T: Into<f64>>(m:&mut Map<String,Value>,k:&str,v:T){m.insert(k.into(),num(v.into()));}
fn base(m:&mut Map<String,Value>,id:&str,t:u64,car:i64,track:i64,lap:i32,on:bool){m.insert("gameId".into(),Value::String(id.into()));m.insert("TimestampMS".into(),Value::Number(t.into()));m.insert("IsRaceOn".into(),Value::Number((on as i64).into()));m.insert("CarOrdinal".into(),Value::Number(car.into()));m.insert("TrackOrdinal".into(),Value::Number(track.into()));m.insert("LapNumber".into(),Value::Number((lap as i64).into()));m.insert("CarClass".into(),Value::Number(0.into()));m.insert("CarPerformanceIndex".into(),Value::Number(0.into()));}
fn valid_ms(v:i32)->f64{if v>0&&v!=i32::MAX {v as f64/1000.0}else{0.0}}
fn wide(b:&[u8],o:usize,n:usize)->String{let mut u=Vec::new();for c in b.get(o..o.saturating_add(n)).unwrap_or(&[]).chunks_exact(2){let x=u16::from_le_bytes([c[0],c[1]]);if x==0{break}u.push(x)}String::from_utf16_lossy(&u).trim().to_owned()}
fn cstr(b:&[u8],o:usize,n:usize)->String{let s=b.get(o..o.saturating_add(n)).unwrap_or(&[]);let e=s.iter().position(|x|*x==0).unwrap_or(s.len());String::from_utf8_lossy(&s[..e]).trim().to_owned()}
fn acc_layout(group:&str,key:&str)->usize{crate::games::catalog::layout_number("acc",group,key).expect("generated ACC layout field")}
fn evo_layout(group:&str,key:&str)->usize{crate::games::catalog::layout_number("evo",group,key).expect("generated AC Evo layout field")}
fn evo_constant(key:&str)->usize{crate::games::catalog::layout_constant("evo",key).expect("generated AC Evo layout constant")}
fn player_acc(g:&[u8])->usize{let player=read_i(g,acc_layout("GRAPHICS","playerCarID"));if player>0{for n in 0..60{if read_i(g,acc_layout("GRAPHICS","carIDbase")+n*4)==player{return n}}}0}
fn player_slot(s:&mut PlayerSlot,p:&[u8],g:&[u8],active:usize)->usize {
    if let Some(slot)=s.slot{return slot}
    let speed=rf(p,evo_layout("PHYSICS","speedKmh")) as f64; if speed<20.0{return 0}
    let vx=rf(p,evo_layout("PHYSICS","velocityX")) as f64;let vz=rf(p,evo_layout("PHYSICS","velocityZ")) as f64;let mag=(vx*vx+vz*vz).sqrt();if mag<0.1{return 0}
    let count=if active==0{1}else{active.min(60)};
    for i in 0..count {let o=evo_constant("CAR_COORDS_BASE")+i*12;let x=rf(g,o) as f64;let z=rf(g,o+8) as f64;let dx=x-s.previous[i*3] as f64;let dz=z-s.previous[i*3+2] as f64;let dm=(dx*dx+dz*dz).sqrt();if dm>0.01{s.scores[i]=(s.scores[i] as f64+(vx*dx+vz*dz)/(mag*dm)) as f32 as f64;}s.previous[i*3]=x as f32;s.previous[i*3+2]=z as f32;}
    s.observations+=1;if s.observations<60{return 0}let mut best=0;for i in 1..60{if s.scores[i]>s.scores[best]{best=i}}s.slot=Some(best);best
}
fn integrate(s:&mut EvoDistance,packet:i32,speed:f64,km:f64,_lap:i32)->f64 {
    let delta=if s.previous_km<0.0 {0.0}else{km-s.previous_km};
    if s.previous_km>=0.0&&delta< -0.05 {s.anchor=km*1000.0;s.integral=0.0;s.calibration_integral=0.0;s.calibration_true=0.0;s.output=s.anchor;s.packet=Some(packet);s.speed=speed;s.previous_km=km;return s.output}
    let packet_delta=s.packet.map(|v|packet as i64-v as i64).unwrap_or(0);
    if packet_delta>0&&packet_delta<=10000 {let segment=0.5*(speed+s.speed)*packet_delta as f64;s.integral+=segment;s.calibration_integral+=segment;}
    if delta>0.0 {s.calibration_true+=delta*1000.0;if s.calibration_integral>0.0&&s.calibration_true>=5.0 {let sample=(s.calibration_true/s.calibration_integral).clamp(0.001,0.01);s.seconds_per_step=if s.seconds_per_step==0.0{sample}else{0.8*s.seconds_per_step+0.2*sample};s.calibration_true=0.0;s.calibration_integral=0.0;}s.anchor=km*1000.0;s.integral=0.0;}
    let k=if s.seconds_per_step>0.0{s.seconds_per_step}else{1.0/333.0};let candidate=if s.previous_km<0.0{km*1000.0}else{s.anchor+k*s.integral};s.output=s.output.max(candidate);s.packet=Some(packet);s.speed=speed;s.previous_km=km;s.output
}
