use serde_json::{Map, Number, Value};

const MAGIC: &[u8;8]=b"RQLMUSF\0";
 const H:usize=28;
 fn root(key:&str)->usize{crate::games::catalog::layout_constant("lmu",key).expect("generated LMU layout constant")}
 fn layout(group:&str,key:&str)->usize{crate::games::catalog::layout_number("lmu",group,key).expect("generated LMU layout field")}
 fn mem()->usize{root("LMU_SHARED_MEMORY_SIZE")} fn ti()->usize{root("LMU_TELEMETRY_INFO_OFFSET")} fn ts()->usize{root("LMU_TELEMETRY_INFO_SIZE")} fn si()->usize{root("LMU_SCORING_INFO_OFFSET")} fn ss()->usize{root("LMU_SCORING_INFO_SIZE")} fn sv()->usize{root("LMU_SCORING_VEHICLE_SIZE")} fn so()->usize{root("LMU_SCORING_VEHICLES_OFFSET")} fn maxv()->usize{root("LMU_MAX_VEHICLES")} fn wheels()->usize{layout("LMU_TELEMETRY","wheels")} fn ws()->usize{root("LMU_WHEEL_SIZE")}
fn slice(b:&[u8],o:usize,n:usize)->Result<&[u8],String>{b.get(o..o.checked_add(n).ok_or("LMU offset overflow")?).ok_or_else(||format!("short LMU source at {o}"))}
fn i32v(b:&[u8],o:usize)->i32{i32::from_le_bytes(b[o..o+4].try_into().unwrap())}
fn u32v(b:&[u8],o:usize)->u32{u32::from_le_bytes(b[o..o+4].try_into().unwrap())}
fn i16v(b:&[u8],o:usize)->i16{i16::from_le_bytes(b[o..o+2].try_into().unwrap())}
fn u16v(b:&[u8],o:usize)->u16{u16::from_le_bytes(b[o..o+2].try_into().unwrap())}
fn f64v(b:&[u8],o:usize)->f64{let x=f64::from_bits(u64::from_le_bytes(b[o..o+8].try_into().unwrap()));if x.is_finite(){x}else{0.}}
fn f64v_default(b:&[u8],o:usize,default:f64)->f64{let x=f64::from_bits(u64::from_le_bytes(b[o..o+8].try_into().unwrap()));if x.is_finite(){x}else{default}}
fn f32v(b:&[u8],o:usize)->f64{let x=f32::from_bits(u32v(b,o)) as f64;if x.is_finite(){x}else{0.}}
fn strv(b:&[u8],o:usize,n:usize)->String{let s=&b[o..o+n];let end=s.iter().position(|x|*x==0).unwrap_or(n);String::from_utf8_lossy(&s[..end]).trim().to_owned()}
fn putf(m:&mut Map<String,Value>,k:&str,v:f64){m.insert(k.into(),Number::from_f64(v).map(Value::Number).unwrap_or(Value::Null));}
fn puti(m:&mut Map<String,Value>,k:&str,v:i64){m.insert(k.into(),Value::Number(v.into()));}
fn clamp(v:f64,a:f64,b:f64)->f64{v.max(a).min(b)}
fn time(v:f64)->f64{if v>0.{v}else{0.}}

#[derive(Clone)] pub struct LmuFrame { pub schema:u16,pub game_version:i32,pub session_event:u32,pub timestamp_ms:f64,pub telemetry:Vec<u8>,pub scoring_info:Vec<u8>,pub player_scoring:Option<Vec<u8>>,pub raw:Option<Vec<u8>> }
 fn player_offset(raw:&[u8],vehicle_id:i32)->Option<usize>{let info=si();let vehicle=sv();let n=(i32v(raw,info+layout("LMU_SCORING_INFO","numberOfVehicles"))).clamp(0,maxv() as i32) as usize;let mut player=None;for i in 0..n{let o=so()+i*vehicle;if i32v(raw,o)==vehicle_id{return Some(o)}if raw[o+layout("LMU_SCORING_VEHICLE","isPlayer")]!=0{player=Some(o)}}player}
 pub fn decode_lmu_source_frame(b:&[u8])->Result<Option<LmuFrame>,String>{
  let (tele,scoring,vehicle)=(ts(),ss(),sv());if b.len()<12||b.get(..8)!=Some(MAGIC){return Ok(None)}let schema=u16v(b,8);let expected=match schema{1=>H+tele+scoring+vehicle,2=>H+mem(),_=>return Ok(None)};if b.len()!=expected{return Ok(None)}
  let stamp=f64::from_bits(u64::from_le_bytes(slice(b,20,8)?.try_into().unwrap()));if !stamp.is_finite()||stamp<0.{return Ok(None)}let raw=if schema==2{Some(b[H..].to_vec())}else{None};
  let (telemetry,scoring_info,player_scoring)=if let Some(r)=raw.as_ref(){let header=root("LMU_TELEMETRY_HEADER_OFFSET");let count=r[header].min(maxv() as u8);let idx=r[header+1];if idx>=count{return Ok(None)}let to=ti()+idx as usize*tele;let p=player_offset(r,i32v(r,to+layout("LMU_TELEMETRY","id")));(r[to..to+tele].to_vec(),r[si()..si()+scoring].to_vec(),p.map(|o|r[o..o+vehicle].to_vec()))}else{let t=b[H..H+tele].to_vec();let s=b[H+tele..H+tele+scoring].to_vec();let p=if u16v(b,10)&1!=0{Some(b[H+tele+scoring..].to_vec())}else{None};(t,s,p)};
  Ok(Some(LmuFrame{schema,game_version:i32v(b,12),session_event:u32v(b,16),timestamp_ms:stamp,telemetry,scoring_info,player_scoring,raw}))
 }
 pub fn encode_lmu_source_payload(game_version:i32,session_event:u32,capture_timestamp_ms:f64,telemetry:&[u8],scoring_info:&[u8],player_scoring:Option<&[u8]>)->Result<Vec<u8>,String>{let (ts,ss,sv)=(ts(),ss(),sv());if telemetry.len()!=ts||scoring_info.len()!=ss||player_scoring.is_some_and(|p|p.len()!=sv)||!capture_timestamp_ms.is_finite()||capture_timestamp_ms<0.{return Err("invalid LMU source payload structure/timestamp".into())}let mut b=vec![0;H+ts+ss+sv];b[..8].copy_from_slice(MAGIC);b[8..10].copy_from_slice(&1u16.to_le_bytes());b[10..12].copy_from_slice(&(if player_scoring.is_some(){1u16}else{0}).to_le_bytes());b[12..16].copy_from_slice(&game_version.to_le_bytes());b[16..20].copy_from_slice(&session_event.to_le_bytes());b[20..28].copy_from_slice(&capture_timestamp_ms.to_le_bytes());b[H..H+ts].copy_from_slice(telemetry);b[H+ts..H+ts+ss].copy_from_slice(scoring_info);if let Some(p)=player_scoring{b[H+ts+ss..].copy_from_slice(p)}Ok(b)}
 pub fn encode_lmu_source_frame(shared_memory:&[u8],capture_timestamp_ms:f64)->Option<Vec<u8>>{let size=mem();if shared_memory.len()<size||!capture_timestamp_ms.is_finite()||capture_timestamp_ms<0.{return None}let header=root("LMU_TELEMETRY_HEADER_OFFSET");let active=shared_memory[header].min(maxv() as u8);let idx=shared_memory[header+1];if shared_memory[header+2]==0||active==0||idx>=active{return None}let to=ti()+idx as usize*ts();let off=player_offset(shared_memory,i32v(shared_memory,to+layout("LMU_TELEMETRY","id")));let mut b=vec![0;H+size];b[..8].copy_from_slice(MAGIC);b[8..10].copy_from_slice(&2u16.to_le_bytes());b[10..12].copy_from_slice(&(if off.is_some(){1u16}else{0}).to_le_bytes());b[12..16].copy_from_slice(&i32v(shared_memory,root("LMU_GAME_VERSION_OFFSET")).to_le_bytes());b[16..20].copy_from_slice(&u32v(shared_memory,root("LMU_SESSION_EVENT_OFFSET")).to_le_bytes());b[20..28].copy_from_slice(&capture_timestamp_ms.to_le_bytes());b[H..].copy_from_slice(&shared_memory[..size]);Some(b)}

pub struct LmuParser;
impl LmuParser{pub fn new()->Self{Self} pub fn reset(&mut self){} pub fn feed(&mut self,frame:&[u8],_time_ms:u64)->Result<Option<Value>,String>{let Some(f)=decode_lmu_source_frame(frame)? else{return Ok(None)};Ok(Some(normalize(&f)))}}
fn normalize(f:&LmuFrame)->Value{
 let t=&f.telemetry;let s=&f.scoring_info;let p=f.player_scoring.as_deref();macro_rules! t{($k:literal)=>{layout("LMU_TELEMETRY",$k)}}macro_rules! si{($k:literal)=>{layout("LMU_SCORING_INFO",$k)}}macro_rules! sv{($k:literal)=>{layout("LMU_SCORING_VEHICLE",$k)}}let session=i32v(s,si!("session"));let car_name=strv(t,t!("vehicleName"),64);let car_model=strv(t,t!("vehicleModel"),30);let score_track=strv(s,si!("trackName"),64);let tele_track=strv(t,t!("trackName"),64);let car_key=if car_model.is_empty(){car_name.clone()}else{car_model.clone()};let track_key=if score_track.is_empty(){tele_track.clone()}else{score_track.clone()};
 let car=crate::games::catalog::resolve_lmu_car(&car_key,&car_name);let track=crate::games::catalog::resolve_lmu_track(&[&score_track,&tele_track]);let car_id=car.as_ref().and_then(|v|v.get("id").and_then(Value::as_str)).map(str::to_owned).unwrap_or_else(||car_key.clone());let track_id=track.as_ref().and_then(|v|v.get("id").and_then(Value::as_str)).map(str::to_owned).unwrap_or_else(||track_key.clone());
 let mut l=Map::new();for (k,v) in [("carId",Value::String(car_id.clone())),("trackId",Value::String(track_id.clone())),("gameVersion",Value::Number(f.game_version.into())),("sessionTypeOrdinal",Value::Number(session.into())),("vehicleId",Value::Number(i32v(t,t!("id")).into())),("driverName",Value::String(p.map_or_else(||strv(s,si!("playerName"),32),|q|strv(q,sv!("driverName"),32)))),("carName",Value::String(car_name.clone())),("carModel",Value::String(car_model.clone())),("trackName",Value::String(track_key.clone())),("vehicleClass",Value::Number((t[t!("vehicleClass")] as i64).into())),("lapInvalidated",Value::Bool(t[t!("lapInvalidated")]!=0)),("inPits",Value::Bool(p.is_some_and(|q|q[sv!("inPits")]!=0))),("rearFlapActivated",Value::Bool(t[t!("rearFlapActivated")]!=0)),("speedLimiterActive",Value::Bool(t[t!("speedLimiterActive")]!=0)),("tcActive",Value::Bool(t[t!("tcActive")]!=0)),("absActive",Value::Bool(t[t!("absActive")]!=0)),("pitState",Value::Number(p.map_or(0,|q|q[sv!("pitState")] as i64).into())),("frontTireCompound",Value::String(strv(t,t!("frontTireCompoundName"),18))),("rearTireCompound",Value::String(strv(t,t!("rearTireCompoundName"),18))) ]{l.insert(k.into(),v);}
 let types=["test-day","practice-1","practice-2","practice-3","practice-4","qualifying-1","qualifying-2","qualifying-3","qualifying-4","warmup","race","race-2","race-3","race-4"];
 let track_len=f64v(s,si!("lapDistance")).max(0.);let distance=p.map_or(0.,|q|f64v(q,sv!("lapDistance")).max(0.));let elapsed=f64v(t,t!("elapsedTime")).max(0.);let start=f64v(t,t!("lapStartElapsedTime")).max(0.);let lapnum=i32v(t,t!("lapNumber"));let sector=i32v(t,t!("currentSector"))&0x7fffffff;let rain=clamp(f64v(s,si!("raining")),0.,1.);let cloud=s[si!("cloudCoverage")];let weather=if rain>=0.66{4}else if rain>0.{3}else if cloud>=4{2}else if cloud>0{1}else{0};
 l.insert("sessionType".into(),Value::String(types.get(session as usize).unwrap_or(&"unknown").to_string()));putf(&mut l,"deltaBest",f64v(t,t!("deltaBest")));putf(&mut l,"trackLengthM",track_len);putf(&mut l,"lapDistanceM",distance);puti(&mut l,"currentSectorIndex",sector as i64);
 if let Some(q)=p{for (key,o) in [("bestSector1",sv!("bestSector1")),("bestSector2",sv!("bestSector2")),("lastSector1",sv!("lastSector1")),("lastSector2",sv!("lastSector2")),("currentSector1",sv!("currentSector1")),("currentSector2",sv!("currentSector2"))]{putf(&mut l,key,time(f64v(q,o)));}}
 for(k,o)in[("rearFlapLegalStatus",t!("rearFlapLegalStatus")),("tcLevel",t!("tc")),("tcCutLevel",t!("tcCut")),("absLevel",t!("abs")),("motorMap",t!("motorMap")),("migration",t!("migration")),("frontAntiSway",t!("frontAntiSway")),("rearAntiSway",t!("rearAntiSway")),("trackLimitsSteps",t!("trackLimitsSteps"))]{puti(&mut l,k,t[o] as i64)}putf(&mut l,"batteryChargeFraction",clamp(f64v(t,t!("batteryChargeFraction")),0.,1.));putf(&mut l,"stateOfCharge",f32v(t,t!("stateOfCharge")));putf(&mut l,"virtualEnergy",f32v(t,t!("virtualEnergy")));putf(&mut l,"regenKw",f32v(t,t!("regenKw")));puti(&mut l,"trackGripLevel",s[si!("trackGripLevel")] as i64);puti(&mut l,"cloudCoverage",cloud as i64);
 let mut out=Map::new();out.insert("gameId".into(),Value::String("lmu".into()));out.insert("lmu".into(),Value::Object(l));out.insert("sessionUID".into(),Value::String(serde_json::json!([f.game_version,f.session_event,session,car_id,track_id]).to_string()));puti(&mut out,"IsRaceOn",if s[si!("inRealtime")]!=0{1}else{0});puti(&mut out,"TimestampMS",f.timestamp_ms.round() as i64);
 for k in ["NormSuspensionTravelFL","NormSuspensionTravelFR","NormSuspensionTravelRL","NormSuspensionTravelRR","TireSlipRatioFL","TireSlipRatioFR","TireSlipRatioRL","TireSlipRatioRR","WheelRotationSpeedFL","WheelRotationSpeedFR","WheelRotationSpeedRL","WheelRotationSpeedRR","WheelOnRumbleStripFL","WheelOnRumbleStripFR","WheelOnRumbleStripRL","WheelOnRumbleStripRR","WheelInPuddleDepthFL","WheelInPuddleDepthFR","WheelInPuddleDepthRL","WheelInPuddleDepthRR","SurfaceRumbleFL_2","SurfaceRumbleFR_2","SurfaceRumbleRL_2","SurfaceRumbleRR_2","TireSlipCombinedFL_2","TireTempFL","TireTempFR","TireTempRL","TireTempRR","Boost","Fuel","FuelCapacity","BestLap","LastLap","CurrentLap","CurrentRaceTime","LapNumber","RacePosition","Accel","Brake","Clutch","HandBrake","Gear","Steer","NormDrivingLine","NormAIBrakeDiff","TireWearFL","TireWearFR","TireWearRL","TireWearRR","SurfaceRumbleFL","SurfaceRumbleFR","SurfaceRumbleRL","SurfaceRumbleRR","TireSlipAngleFL","TireSlipAngleFR","TireSlipAngleRL","TireSlipAngleRR","TireCombinedSlipFL","TireCombinedSlipFR","TireCombinedSlipRL","TireCombinedSlipRR","SuspensionTravelMFL","SuspensionTravelMFR","SuspensionTravelMRL","SuspensionTravelMRR","CarOrdinal","CarClass","CarPerformanceIndex","DrivetrainType","NumCylinders","PositionX","PositionY","PositionZ","Speed","Power","Torque","TrackOrdinal"] { putf(&mut out,k,0.); }
 let vels=[f64v(t,t!("localVelocity")),f64v(t,t!("localVelocity")+8),-f64v(t,t!("localVelocity")+16)];let acc=[f64v(t,t!("localAcceleration")),f64v(t,t!("localAcceleration")+8),-f64v(t,t!("localAcceleration")+16)];let pos=[f64v(t,t!("position")),f64v(t,t!("position")+8),f64v(t,t!("position")+16)];let orientation=t!("orientation");let o1=orientation+24;let o2=orientation+48;let forward=[-f64v(t,orientation+16),-f64v(t,o1+16),-f64v(t,o2+16)];let motor_rpm=f64v(t,t!("electricBoostMotorRpm"));let motor_torque=f64v(t,t!("electricBoostMotorTorque"));
 for(k,v)in[("EngineMaxRpm",f64v(t,t!("engineMaxRpm")).max(0.)),("EngineIdleRpm",0.),("CurrentEngineRpm",f64v(t,t!("engineRpm")).max(0.)),("AccelerationX",acc[0]),("AccelerationY",acc[1]),("AccelerationZ",acc[2]),("VelocityX",vels[0]),("VelocityY",vels[1]),("VelocityZ",vels[2]),("AngularVelocityX",f64v(t,t!("localRotation"))),("AngularVelocityY",f64v(t,t!("localRotation")+8)),("AngularVelocityZ",f64v(t,t!("localRotation")+16)),("Yaw",forward[0].atan2(forward[2])),("Pitch",forward[1].clamp(-1.,1.).asin()),("Roll",(-f64v(t,o1)).atan2(f64v(t,o1+8))),("Fuel",f64v(t,t!("fuel")).max(0.)),("FuelCapacity",f64v(t,t!("fuelCapacity")).max(0.)),("DistanceTraveled",(if let Some(q)=p{i16v(q,sv!("totalLaps")).max(0) as f64}else{(lapnum-1).max(0) as f64})*track_len+distance),("CurrentLap",(elapsed-start).max(0.)),("CurrentRaceTime",elapsed),("Power",f64v(t,t!("engineTorque"))*f64v(t,t!("engineRpm"))*std::f64::consts::TAU/60.+motor_torque*motor_rpm*std::f64::consts::TAU/60.),("Torque",f64v(t,t!("engineTorque"))+motor_torque),("PositionX",pos[0]),("PositionY",pos[1]),("PositionZ",pos[2]),("Speed",vels[0].hypot(vels[1]).hypot(vels[2])),("TrackTemp",f64v(s,si!("trackTemperature"))),("AirTemp",f64v(s,si!("ambientTemperature"))),("RainPercent",(rain*100.).round()),("WeatherType",weather as f64)]{putf(&mut out,k,v)}
 putf(&mut out,"BestLap",p.map_or(0.,|q|time(f64v(q,sv!("bestLapTime")))));putf(&mut out,"LastLap",p.map_or(0.,|q|time(f64v(q,sv!("lastLapTime")))));
 puti(&mut out,"LapNumber",(lapnum+1).max(1) as i64);puti(&mut out,"RacePosition",p.map_or(0,|q|q[sv!("place")]) as i64);for(k,o)in[("Accel",t!("throttle")),("Brake",t!("brake")),("Clutch",t!("clutch"))]{puti(&mut out,k,(clamp(f64v(t,o),0.,1.)*255.).round() as i64)}puti(&mut out,"HandBrake",0);puti(&mut out,"Gear",{let g=i32v(t,t!("gear"));if g<0{0}else if g==0{11}else{g}} as i64);puti(&mut out,"Steer",(clamp(f64v(t,t!("steering")),-1.,1.)*127.).round() as i64);
 macro_rules! w{($k:literal)=>{layout("LMU_WHEEL",$k)}}let names=["FL","FR","RL","RR"];for(i,n)in names.iter().enumerate(){let o=t!("wheels")+i*root("LMU_WHEEL_SIZE");let patch=f64v(t,o+w!("longitudinalPatchVelocity"));let ground=f64v(t,o+w!("longitudinalGroundVelocity"));let lat=f64v(t,o+w!("lateralPatchVelocity"));let slip=patch/ground.abs().max(1.);let angle=lat.atan2(ground.abs().max(0.1));let base=o+w!("temperature");let temp=[f64v(t,base)-273.15,f64v(t,base+8)-273.15,f64v(t,base+16)-273.15];let temps=[temp[2],temp[1],temp[0]];let side=match i{0=>"FrontLeft",1=>"FrontRight",2=>"RearLeft",_=>"RearRight"};let fields=[(format!("TireSlipRatio{n}"),slip),(format!("WheelRotationSpeed{n}"),f64v(t,o+w!("rotation"))),(format!("TireSlipAngle{n}"),angle),(format!("TireCombinedSlip{n}"),slip.hypot(angle.tan())),(format!("SuspensionTravelM{n}"),f64v(t,o+w!("suspensionDeflection"))),(format!("BrakeTemp{side}"),f64v(t,o+w!("brakeTemperature"))),(format!("TirePressure{side}"),f64v(t,o+w!("pressureKpa"))*0.1450377377),(format!("TireTemp{n}"),(temp[0]+temp[1]+temp[2])/3.),(format!("TireCarcassAverageTemp{n}"),f64v(t,o+w!("tireCarcassTemperature"))-273.15),(format!("TireSurfaceTempInner{n}"),temps[0]),(format!("TireSurfaceTempMiddle{n}"),temp[1]),(format!("TireSurfaceTempOuter{n}"),temps[2]),(format!("TireWear{n}"),1.-clamp(f64v(t,o+w!("wear")),0.,1.))];for(k,v)in fields{putf(&mut out,&k,v)}puti(&mut out,&format!("WheelOnRumbleStrip{n}"),if t[o+w!("surfaceType")]==5{1}else{0});for prefix in ["NormSuspensionTravel","WheelInPuddleDepth","SurfaceRumble","SurfaceRumble_2"]{puti(&mut out,&format!("{prefix}{n}"),0)} }
 for(i,n)in names.iter().enumerate(){let o=t!("wheels")+i*root("LMU_WHEEL_SIZE");let base=o+w!("temperature");let (inner,outer)=if i%2==0{(base+16,base)}else{(base,base+16)};putf(&mut out,&format!("TireSurfaceTempInner{n}"),f64v_default(t,inner,273.15)-273.15);putf(&mut out,&format!("TireSurfaceTempOuter{n}"),f64v_default(t,outer,273.15)-273.15);out.remove(&format!("SurfaceRumble_2{n}"));}
 putf(&mut out,"TireSlipCombinedFL_2",{let o=t!("wheels");let patch=f64v(t,o+w!("longitudinalPatchVelocity"));let ground=f64v(t,o+w!("longitudinalGroundVelocity"));let lateral=f64v(t,o+w!("lateralPatchVelocity"));let slip=patch/ground.abs().max(1.);slip.hypot(lateral.atan2(ground.abs().max(0.1)).tan())});
 for(k,v)in[("Boost",0), ("CarOrdinal",-1),("CarClass",t[t!("vehicleClass")] as i64),("CarPerformanceIndex",0),("DrivetrainType",1),("NumCylinders",0),("TrackOrdinal",-1),("NormDrivingLine",0),("NormAIBrakeDiff",0),("DrsActive",if t[t!("rearFlapActivated")]!=0{1}else{0})]{puti(&mut out,k,v)}
 out.into()
}
